<?php
function lookupType_init() {
}

function lookupType_perm() {
	return array('edit lookupType','administer lookupType', 'create lookupType', 'view lookupType');
}

function lookupType_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit lookupType', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create lookupType', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view lookupType', $account);
	}
	
}

function lookupType_menu() {
	
	
	$items['admin/dsje/listlookupType'] = array(
										'title' => t('List of Lookup Type'),
										'description' => 'Allow user to View Lookup Type',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewdsjelookupType',
										'access arguments' => array('administer lookupType'),
													 
									  );
	
	$items['admin/dsje/listlookupType/addlookupType'] = array(
										'title' => t('Add Lookup Type'),
										'description' => 'Allow user to add Lookup Type',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addlookupType',
										'access arguments' => array('administer lookupType'),
													 
									  );
									  
   	$items['admin/dsje/listlookupType/edit/lookupType/%'] = array(
								
										'title' => t('Edit Lookup Type'),
										'description' => 'Allow user to add Lookup Type',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addlookupTypeedit',
		                                'page arguments' => array(5),
		                                'access arguments' => array('administer lookupType'),
													 
									  );
		 $items['admin/dsje/listlookupType/view/lookupType/%'] = array(
								
										'title' => t('view Lookup Type'),
										'description' => 'Allow user to view Lookup Type',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_viewlookupType',
		                                'page arguments' => array(5),
		                                'access arguments' => array('administer lookupType'),
													 
									  );
    $items['admin/dsje/del/lookupType/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'dsjelookupType_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer lookupType'),
													 
									  );
  $items['admin/dsje/enable/lookupType/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'dsjelookupType_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer lookupType'),
													 
									  );
	return $items;
}


/**
 listing designation
 */
 function viewdsjelookupType(){
 global $user;
	global $base_url;
	global $xpathObj;
	$limit = (int)getMessage('dsjelookupType', 'code04', NULL);

   
  $header = array(
		array('data' => t('S. No.')),
        array('data' => t('Lookup Type'), 'field' => 'lookupType_name', 'sort' => 'asc'),
		//array('data' => t('Remarks')),
	    array('data' => t('Status'), 'field' => 'status', 'sort' => 'asc'),
		array('data' => t('Action'),'class' => 'addeditview',),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List of Lookup Type', 'admin/dsje/listlookupType/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']|| $_REQUEST['searchtextstatus']!=''){
		$val = '%'.strtoupper($_REQUEST['searchtext']).'%'; $val=addslashes($val);	
		
		 $status = $_REQUEST['searchtextstatus'];	
	 
	 if( $val && $status ==''){
	 $searchquery = " UPPER(lookupType_name) LIKE '".$val."'";
	 }
	 
	else if( $val=='' && $status){
	 $searchquery = " status='".$status."'";
	 }
	 
	 else if($val && ($status =='0' ||$status =='1') ){
	 $searchquery = "(UPPER(lookupType_name) LIKE '".$val."' AND status='".$status."')";
	 }
		 
		//$val=addslashes($val);
		$query = "SELECT lookupType_id, lookupType_name, status FROM {tbl_lookuptypes} where  ".$searchquery." ".tablesort_sql($header);
        $sqlcount = "SELECT COUNT(*) AS count FROM {tbl_lookuptypes} where ".$searchquery." ".tablesort_sql($header);
		
		
		$rscount = db_query($sqlcount);
		$rscounter = db_fetch_object($rscount);
	//	$_REQUEST['page']=0;
	}else{
	  	$query = "SELECT lookupType_id, lookupType_name, status FROM {tbl_lookuptypes}".tablesort_sql($header);
	}
	

	
global $base_url;
$action = $base_url.'/admin/dsje/listlookupType';

$selected0 ="";
$selected1 ="";

if($_REQUEST['searchtextstatus'] !=''){
	
	if($_REQUEST['searchtextstatus'] == 0){
	  $selected0 ="selected = selected"; 
	}
	
	if($_REQUEST['searchtextstatus'] == 1){
	  $selected1  ="selected =  selected"; 
	}
}else{
$selected0 ="";
$selected1 ="";
}

	$output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']|| $_REQUEST['searchtextstatus']!=''){
	$output .= t(getMessage('dsjelookupType', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listlookupType');
	}
	
	$output .='</td><td colspan="3"></td></tr>';
	
	$addurl = l(getMessage('dsjelookupType', 'code01', NULL),"admin/dsje/listlookupType/addlookupType");
   	$lising = getMessage('dsjelookupType', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight">Status:<select name="searchtextstatus">
	<option value="" selected = "selected">--Select--</option>
	<option value="0" '.$selected0.'>Disabled</option>
	<option value="1" '.$selected1.'>Enabled</option>
	
	</select>&nbsp;&nbsp;<input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';
	$result = pager_query($query,$limit);
	
	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listlookupType/edit/lookupType/".$row->lookupType_id);
		$viewurl = l("View","admin/dsje/listlookupType/view/lookupType/".$row->lookupType_id);
     if($row->status=='1'){
		$deleteurl = l("Disable","admin/dsje/del/lookupType/".$row->lookupType_id."/".$row->lookupType_name);
     }else{
		$deleteurl = l("Enable","admin/dsje/enable/lookupType/".$row->lookupType_id."/".$row->lookupType_name);
     }
		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->lookupType_name)),
			//array('data' => ucfirst($row->remarks)),
			array('data' => $st),
			array('data' => $viewurl." | ".$editurl." | ".$deleteurl),
		);
	}
	
	if($rows== NULL)
	$header=NULL;

	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }


function dsje_addlookupTypeedit($lookupType_id){
 return drupal_get_form('lookupType_form_edit',$lookupType_id);
}

function lookupType_form_edit(&$form_lookupTypes,$lookupType_id) {
			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Lookup Type', 'admin/dsje/listlookupType');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit Lookup Type', 'admin/dsje/listlookupType/edit/lookupType/'.$array[5].'');
  }
  drupal_set_breadcrumb($breadcrumb);
	$sqldesignation = "select * FROM {tbl_lookuptypes} where lookupType_id='$lookupType_id'";
	$resdesignation = db_query($sqldesignation);
	$rsdesignation = db_fetch_object($resdesignation);
	
	$form['lookupType_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsdesignation->lookupType_id,
	);
	
	$form['lookupType_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('Lookup Type Name'),
		'#required' => TRUE,
		'#default_value' =>$rsdesignation->lookupType_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return alphanumeric(event)'),
	);

	$form['prev_lookupType_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsdesignation->lookupType_name,
	);


	/*$form['remarks'] = array(
	    '#type' =>'textarea',
		'#title' => t('Remarks'),
		'#required' => FALSE,
		'#default_value' =>$rsdesignation->remarks,
		'#cols' =>30,
        '#rows' => 5,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
  
  /*$form['status'] = array(
		'#type' => 'hidden',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => $rsdesignation->status,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
	
	$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listlookupType'),
);
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		
	return $form;
}

function lookupType_form_edit_validate($form, &$form_lookupType) {
  $values = $form_lookupType['values'];
  $lookupType_name = parseData(trim($values['lookupType_name']));
  $remarks = parseData(trim($values['remarks']));
  $lookupType_id = $values['lookupType_id'];
$s = textonlyn('lookupType_name',$lookupType_name,'lookupType Name');
$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
if($s == 0 && $s1 == 0){
  $sql = "SELECT * FROM {tbl_lookuptypes} where UCASE(lookupType_name)= '".strtoupper($lookupType_name)."'  and lookupType_id !='".$lookupType_id."'";
   $res = db_query($sql);
  
  if($rs = db_fetch_object($res)){
		$message = getMessage('dsjelookupType', 'code06', array("0"=>$lookupType_name));
		form_set_error('lookupType_name', $message);
   }
}
	
}

function lookupType_form_edit_submit($form, &$form_lookupType) {
	global $user;
	$values = $form_lookupType['values'];
	
    $remarks = trim($values['remarks']);
    $status = $values['status'];
	$createdby = $user->uid;
	$lookupType_id = $values['lookupType_id'];
	$lookupType_name = parseData(trim($values['lookupType_name']));
	$prev_lookupType_name = parseData($values['prev_lookupType_name']);
	$createdon = time();
	$s = textonlyn('lookupType_name',$lookupType_name,'lookupType Name');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	if($s == 0 && $s1 == 0){
	$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_lookuptypes} where LOWER(lookupType_name)= '".strtolower($lookupType_name)."' GROUP BY lookupType_id"));
$count = $countObj->count;

if( strcmp(strtolower($prev_lookupType_name), strtolower($lookupType_name))==0){
		db_query("UPDATE {tbl_lookuptypes} set `lookupType_name` = '".$lookupType_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."'  where lookupType_id='".$lookupType_id."'");
		$message = getMessage('dsjelookupType', 'code10', array("0"=>$lookupType_name));
		drupal_set_message($message);
		drupal_goto("admin/dsje/listlookupType");	
		}
		else
		{
		if($count==0){
			db_query("UPDATE {tbl_lookuptypes} set `lookupType_name` = '".$lookupType_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."' where lookupType_id='".$lookupType_id."'");
			$message = getMessage('dsjelookupType', 'code10', array('0'=>$lookupType_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listlookupType");	
		
			}else{
			db_query("UPDATE {tbl_lookuptypes} set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."' where lookupType_id='".$lookupType_id."'");
			$message = getMessage('dsjelookupType', 'code10', array("0"=>$lookupType_name));
			form_set_error('lookupType_name', $message);
		 }	
	}
	}

}
function dsje_addlookupType(){
 return drupal_get_form('lookupType_form');
}
function lookupType_form() {
			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Lookup Type', 'admin/dsje/listlookupType');
  if($array[3] == 'addlookupType'){
     $breadcrumb[] = l('Add Lookup Type', 'admin/dsje/listlookupType/addlookupType');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['lookupType_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('Lookup Type Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>45,
		'#maxlength'=>45,
		 '#attributes' => array('onkeypress' => 'return alphanumeric(event)'),  
      
	);

	/*$form['remarks'] = array(
	    '#type' =>'textarea',
		'#title' => t('Remarks'),
		'#required' => FALSE,
		'#default_value' =>'',
		'#cols' => 30,
        '#rows' => 5,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
	
	$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listlookupType'),
);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		
	return $form;
}

function lookupType_form_validate($form, &$form_lookupType) {
  $values = $form_lookupType['values'];
  $lookupType_name = parseData(trim($values['lookupType_name']));
  $remarks = parseData(trim($values['remarks']));
  
	$s = textonlyn('lookupType_name',$lookupType_name,'lookupType Name');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	if($s == 0 && $s1 == 0){
	  $sql = "SELECT * FROM {tbl_lookuptypes} where UCASE(lookupType_name)= '".strtoupper($lookupType_name)."' AND status =1";
	   $res = db_query($sql);
	  if($rs = db_fetch_object($res)){
			$message = getMessage('dsjelookupType', 'code06', array("0"=>$lookupType_name));
			form_set_error('lookupType_name', $message);
	   }
 }	
}


function lookupType_form_submit($form, &$form_lookupType) {
	global $user;
	$values = $form_lookupType['values'];
    $lookupType_name = parseData(trim($values['lookupType_name']));
    $remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
    $sql = "SELECT * FROM {tbl_lookuptypes} where UCASE(lookupType_name)= '".strtoupper($lookupType_name)."' AND status !=1";
    $res = db_query($sql);
  
    if($rs = db_fetch_object($res)){
      db_query("UPDATE {tbl_lookuptypes} SET status=1 where lookupType_id=$rs->lookupType_id");
    }else{
	  db_query("INSERT INTO {tbl_lookuptypes} (`lookupType_name` ,`status` ,`createdby` ,`createdon`) VALUES('".$lookupType_name."','".$status."','".$createdby."','".$createdon."') ");
     }
	  $message = getMessage('dsjelookupType', 'code05', array('0'=>$lookupType_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listlookupType");	

}


function lookupType_theme() {
	
	return array(
				 
		'lookupType_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'lookupType_form',
                                 ),
        'lookupType_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'lookupType_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function lookupType_form_alter(&$form, &$form_lookupType, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='lookupType_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['lookupType_id']['#disabled'] = TRUE;
	}
	if($form_id =='lookupType_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['lookupType_id']['#disabled'] = TRUE;
	}
 }

  function dsjelookupType_delete($sid,$name){
	  $lookupType_id = $sid;
   db_query("UPDATE {tbl_lookuptypes} set `status`=0 where lookupType_id='".$lookupType_id."'");
 $message = getMessage('dsjelookupType', 'code07', array("0"=>$name));
 drupal_set_message($message);
 drupal_goto('admin/dsje/listlookupType');
 }

   function dsjelookupType_enable($sid,$name){
	  $lookupType_id = $sid;
   db_query("UPDATE {tbl_lookuptypes} set `status`=1 where lookupType_id='".$lookupType_id."'");
 $message = getMessage('dsjelookupType', 'code09', array("0"=>$name));
 drupal_set_message($message);
 drupal_goto('admin/dsje/listlookupType');
 }

function dsje_viewlookupType($lookupType_id){
$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Lookup Type', 'admin/dsje/listlookupType');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View Lookup Type', 'admin/dsje/listlookupType/view/lookupType/'.$array[5].'');
  }
  drupal_set_breadcrumb($breadcrumb);

	$sql = "select * FROM {tbl_lookuptypes} where lookupType_id = '$lookupType_id' ";
$res = db_query($sql);
 $rs = db_fetch_object($res);
 if($rs->status =='0'){
  $status ='Disabled';
}else{
  $status ='Enabled';
}


$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}




$output .='<table cellpadding="2" cellspacing="1" border="0" id="wrapper2">';
$output .='<tr class="oddrow"><td colspan="2" align="center"><h2>Lookup Type Details</h2></td></tr>';
$output .='<tr class="evenrow"><td width="50%">Lookup Type Name:</td><td class="normal">'.ucwords($rs->lookupType_name).'</td></tr>';
////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
$output .='<tr class="oddrow"><td width="50%">Status:</td><td class="normal">'.$status.'</td></tr>';
$output .='<tr class="evenrow"><td class="back" colspan="2" align="center">'.l(t('Back'), 'admin/dsje/listlookupType').'</td></tr>';
$output .='</table>';
return $output;
  }
