<?php
function dsje_block_init() {
}

function dsje_block_perm() {
	return array('edit dsje_block','administer dsje_block', 'create dsje_block', 'view dsje_block');
}

function dsje_block_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_block', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_block', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_block', $account);
	}
}

function dsje_block_menu() {

$items['rec/district'] = array(
										'page callback' => 'mydistrict',
										'type' => MENU_CALLBACK,
										'access arguments' => array('access content'),
										);
$items['rec/tehsil'] = array(
										'page callback' => 'mytehsil',
										'type' => MENU_CALLBACK,
										'access arguments' => array('access content'),
										);



	$items['dsje/district'] = array(
										'page callback' => 'selectblock',
										'type' => MENU_CALLBACK,
										'access arguments' => array('access content'),
										);
										
	$items['dsje/block'] = array(
										'page callback' => 'myblock',
										'type' => MENU_CALLBACK,
										'access arguments' => array('access content'),
										);									
								
	
	$items['dsje/listblock'] = array(
										'title' => t('List of Block'),
										'description' => 'Allow user to View Block',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewblock',
										'access arguments' => array('administer dsje_block'),
													 
									  );
	
	$items['dsje/listblock/addblock'] = array(
										'title' => t('Add Block'),
										'description' => 'Allow user to add Block',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addblock',
										'access arguments' => array('administer dsje_block'),
													 
									  );
   	$items['dsje/listblock/edit/block/%'] = array(
								
	                                    'title' => t('Edit Block'),
										'description' => 'Allow user to add Block',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addblockedit',
                                        'page arguments' => array(4),  
		                                'access arguments' => array('administer dsje_block'),
													 
									  );
     	$items['dsje/listblock/view/block/%'] = array(
								
	                                    'title' => t('View Block'),
										'description' => 'Allow user to add Block',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addblockview',
                                        'page arguments' => array(4), 
		                                'access arguments' => array('administer dsje_block'),
													 
									  );

      $items['dsje/del/block/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'block_delete',
		                                'page arguments' => array(3,4),
		                                'access arguments' => array('administer dsje_block'),
													 
									  );
      $items['dsje/enable/block/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'block_enable',
		                                'page arguments' => array(3,4),
		                                'access arguments' => array('administer dsje_block'),
													 
									  );
	return $items;
}


/** listing Tehsil */
function viewblock(){
global $user;
global $base_url;
global $xpathObj;
$limit = (int)getMessage( 'dsjeblock', 'code04', NULL);
$lising = 'List of Block';
$addurl = l("Add Tehsil","dsje/listblock");

$output = '<table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
<tr>
<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
</tr>
</table>';
 
  $header = array(
		array('data' => t('S. No.')),
        array('data' => t('Tehsil'), 'field' => 'tbl_tehsil.tehsil_name', 'sort' => 'asc'),
        array('data' => t('District'), 'field' => 'tbl_district.district_name', 'sort' => 'asc'),
	    array('data' => t('State'), 'field' => 'tbl_dsjestate.state_name', 'sort' => 'asc'),
		 array('data' => t('Block'), 'field' => 'tbl_block.block_name', 'sort' => 'asc'),
		//array('data' => t('Remarks')),
	    array('data' => t('Status'), 'field' => 'tbl_block.status', 'sort' => 'asc'),
		array('data' => t('Action'),'class' => 'addeditview',),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List of Block', 'dsje/listblock/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']|| $_REQUEST['searchtextstatus']!=''){
	$val = '%'.strtoupper($_REQUEST['searchtext']).'%'; $val=addslashes($val);	
	
	$status = $_REQUEST['searchtextstatus'];	
	 
	 if( $val && $status ==''){
	 $searchquery = "UPPER(tbl_dsjestate.state_name) LIKE '".$val."' OR UPPER(tbl_tehsil.tehsil_name) LIKE '".$val."' OR UPPER(tbl_district.district_name) LIKE '".$val."'  OR UPPER(tbl_block.block_name) LIKE '".$val."' ";
	 }
	 
	else if( $val=='' && $status){
	 $searchquery = "tbl_block.status='".$status."'";
	 }
	 
	 else if($val && ($status =='0' ||$status =='1') ){
	 $searchquery = "(UPPER(tbl_dsjestate.state_name) LIKE '".$val."' OR UPPER(tbl_tehsil.tehsil_name) LIKE '".$val."' OR UPPER(tbl_district.district_name) LIKE '".$val."'  OR UPPER(tbl_block.block_name) LIKE '".$val."') AND tbl_block.status='".$status."'";
	 }
	 
	$query = "SELECT tbl_tehsil.tehsil_id,tbl_tehsil.tehsil_name, tbl_dsjestate.state_id, tbl_dsjestate.state_name,tbl_district.district_id,tbl_district.district_name, tbl_block.status,tbl_block.block_name,tbl_block.block_id FROM {tbl_block} INNER JOIN tbl_district ON (tbl_district.district_id=tbl_block.district_id) INNER JOIN tbl_dsjestate ON (tbl_dsjestate.state_id=tbl_block.state_id) INNER JOIN tbl_tehsil  ON (tbl_tehsil.tehsil_id=tbl_block.tehsil_id) where  ". $searchquery."".tablesort_sql($header);
     $sqlcount = "SELECT COUNT(*) AS count FROM {tbl_block} INNER JOIN tbl_district ON (tbl_district.district_id=tbl_block.district_id) INNER JOIN tbl_dsjestate ON (tbl_dsjestate.state_id=tbl_block.state_id) INNER JOIN tbl_tehsil  ON (tbl_tehsil.tehsil_id=tbl_block.tehsil_id)  where ". $searchquery."".tablesort_sql($header);
	 $rscount = db_query($sqlcount);
	 $rscounter = db_fetch_object($rscount);
	 //$_REQUEST['page']=0;
	}else{
	  $query = "SELECT tbl_tehsil.tehsil_id,tbl_tehsil.tehsil_name, tbl_dsjestate.state_id, tbl_block.block_id,tbl_dsjestate.state_name,tbl_district.district_id,tbl_district.district_name,tbl_block.block_name,tbl_block.status FROM {tbl_block} INNER JOIN tbl_district ON (tbl_district.district_id=tbl_block.district_id) INNER JOIN tbl_dsjestate ON (tbl_dsjestate.state_id=tbl_block.state_id) INNER JOIN tbl_tehsil  ON (tbl_tehsil.tehsil_id=tbl_block.tehsil_id) ".tablesort_sql($header);
	}
global $base_url;
$action = $base_url.'/dsje/listblock';

$t1=$_POST['searchtextstatus'];
$selected0 ="";
$selected1 ="";

if($_REQUEST['searchtextstatus'] !=''){
	
	if($_REQUEST['searchtextstatus'] == 0){
	  $selected0 ="selected = selected"; 
	}
	
	if($_REQUEST['searchtextstatus'] == 1){
	  $selected1  ="selected =  selected"; 
	}
}else{
$selected0 ="";
$selected1 ="";
}
	$output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']|| $_REQUEST['searchtextstatus']!=''){
	$output .= t(getMessage( 'dsjeblock', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','dsje/listblock');
	}
	
	$output .='</td><td colspan="3"></td></tr>';
	
	$addurl = l(getMessage( 'dsjeblock', 'code01', NULL),"dsje/listblock/addblock");
   	$lising = getMessage( 'dsjeblock', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight">Status:<select name="searchtextstatus">
	<option value="" selected = "selected">--Select--</option>
	<option value="0" '.$selected0.'>Disabled</option>
	<option value="1" '.$selected1.'>Enabled</option>
	
	</select>&nbsp;&nbsp;<input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';
	$result = pager_query($query,$limit);

	
	if($_REQUEST['page']){
		 $counter = $_REQUEST['page']*$limit;
		}else{
		 $counter = 0;
	}
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","dsje/listblock/edit/block/".$row->block_id);
		$viewurl = l("View","dsje/listblock/view/block/".$row->block_id);
		if($row->status=='1'){
		  $deleteurl = l("Disable","dsje/del/block/$row->block_id/$row->block_name");
		}else{
		  $deleteurl = l("Enable","dsje/enable/block/$row->block_id/$row->block_name");
		}
		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		//$state_union_territory = $row->state_union_territory;
		
		
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->tehsil_name)),
            array('data' => ucwords($row->district_name)),
            array('data' => ucwords($row->state_name)),
			array('data' => ucwords($row->block_name)),
			//array('data' => $row->remarks),
			array('data' => $st),
			array('data' => $viewurl." | ".$editurl." | ".$deleteurl),
		);
	}
	
	if($rows== NULL)
	$header=NULL;
	
	
	$output .= ''.theme_table($header,$rows, $attributes = array(), $caption = NULL).'';
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }
 
 
 
function dsje_addblock(){
 return drupal_get_form('dsje_block_form');
}

/**
 *form creation
 */

function dsje_block_form() {
	$array = explode('/',$_GET['q']);
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Block', 'dsje/listblock');
  if($array[2] == 'addblock'){
     $breadcrumb[] = l('Add Block', 'dsje/listblock/addblock');
  }

  drupal_set_breadcrumb($breadcrumb);

	
	$sqlcountry = "select * from {tbl_dsjestate} WHERE status='1' ORDER BY state_name";
	$rescountry =db_query($sqlcountry);
	if($rescountry){
      $countryarray[''] = '--Select--'; 
	  while($rscountry = db_fetch_object($rescountry)){
	    $countryarray[$rscountry->state_id] = ucfirst($rscountry->state_name);
	  }
	}
	$form['state_id'] = array(
		'#type' => 'select',
		'#title' => t('State'),
		'#required' => TRUE,
		'#default_value' => '',
		'#options' => $countryarray,
		'#ahah' => array(
					  'path' => 'rec/district',
					  'method' => 'replace',
					  'effect' => 'slide',
					  'wrapper' =>'zone',
					  ),
	);
	
	
	
    $zonearray[''] = '--Select--';
	$form['district_id'] = array(
		'#type' => 'select',
		'#title' => t('District'),
		'#required' => TRUE,
		'#default_value' => '',
		'#options' =>$zonearray,
		'#ahah' => array(
					  'path' => 'rec/tehsil',
					  'method' => 'replace',
					  'effect' => 'slide',
					  'wrapper' =>'state',
					  ), 
	);
    
    $statearray[''] = '--Select--';
	$form['tehsil_id'] = array(
			'#type' => 'select',
			'#title' => t('Tehsil'),
			'#required' => TRUE,
			'#default_value' => '',
			'#options' => $statearray,
		);
	
	
	
	
	$form['block_name'] = array(
		'#type' => 'textfield',
		'#title' => t('Block'),
		'#required' => TRUE,
		'#default_value' => $form->block_name,
		'#maxlength'=>45,
		'#attributes' => array('onkeypress' => 'return alphanumeric(event)'),
	);
	
	
	/*$form['remarks'] = array(
	    '#type' =>'textarea',
		'#title' => t('Remarks'),
		'#required' => FALSE,
		'#default_value' =>'',
		'#cols' => 30,
        '#rows' => 5,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
	$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'dsje/listblock'),
);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		
	return $form;
}

/**
 *submit handler
 */

function dsje_block_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $state_id =$values['state_id'];
    $district_id = $values['district_id'];
    $tehsil_id = trim($values['tehsil_id']);
	$block_name = trim($values['block_name']);
	//$state_uid = trim($values['state_uid']);
	//$state_union_territory = parseData(trim($values['state_union_territory']));
    $remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
	$updatedby = $user->uid;
	$updatedon = $createdon;
     
	 if($district_id == '')
	 { form_set_error($district_id,t('District field is requried'));}
	 else{
   db_query("INSERT INTO {tbl_block} (`block_name`,`state_id` ,`district_id` ,`tehsil_id` , `status` ,`createdby` ,`createdon` ,`updatedby` ,`updatedon`) VALUES('".$block_name."', '".$state_id."','".$district_id."','".$tehsil_id."','".$status."','".$createdby."','".$createdon."','".$updatedby."','".$updatedon."') ");
	$message = getMessage('dsjeblock', 'code05', array("0"=>$block_name));
	drupal_set_message($message);
	drupal_goto('dsje/listblock');
}
}

function dsje_block_form_validate($form, &$form_state) {


$array = explode('/',$_GET['q']);
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Block', 'dsje/listblock');
  if($array[2] == 'addblock'){
     $breadcrumb[] = l('Add Block', 'dsje/listblock/addblock');
  }

  drupal_set_breadcrumb($breadcrumb);

	$values = $form_state['values'];
	$state_id = $values['state_id'];
	$district_id = $values['district_id'];
	$tehsil_id = $values['tehsil_id'];
	$block_name = parseData(trim($values['block_name']));
	//$state_uid = trim($values['state_uid']);
	$remarks = trim($values['remarks']);
		if($state_id==''){
			form_set_error('state_id', t('State field is required.'));
			$s3=1;
		}
		
		if($district_id==''){
			form_set_error('district_id', t('District field is required.'));
		$s2=2;
		}
		if($tehsil_id==''){
			form_set_error('tehsil_id', t('Tehsil field is required.'));
		$s1=3;
		}
		
	$s = textonlyn('block_name',$block_name,'Block Name');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	
		$sql = "SELECT * FROM {tbl_block} where LOWER(block_name)= '".strtolower($block_name)."' and tehsil_id = '".$tehsil_id."' ";
		$res = db_query($sql);
	  
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjeblock', 'code06', array("0"=>$block_name));	
			form_set_error('block_name', $message);
		
	}
}

function selectblock() {
    $state_id = $_POST['state_id'];
	$query = "SELECT district_id, district_name FROM {tbl_district} WHERE state_id = '".$state_id."' AND status='1' ORDER BY district_name" ;
	$result = db_query($query);

	$zonearray = array();
	$zonearray[''] = "--Select--";
	$counter = 0;
	while($row=db_fetch_object($result)) {
		$zonearray[$row->district_id] = ucfirst($row->district_name);
		$counter++;
		//$output.="<option value='$row->state_id'>$row->state_name</option>";
	}
	if($counter==0) {
		$zonearray[] = "--Select--";
	}
	$form_state = array('submitted' => FALSE);
	$form_build_id = $_POST['form_build_id'];
	$form = form_builder('dsje_block_form', $form, $form_state);
	$form['district_id'] = array (
							 '#type' => 'select',
							'#title' => t('District'),
							'#required' => TRUE,
							'#default_value' => $node->district_id,
							'#options' => $zonearray,
							'#id' => 'edit-district_id',
							'#name' => 'district_id',
						 );
	$output = drupal_render($form['district_id']);
	return drupal_json(array('status' => TRUE, 'data' => $output));
}





function dsje_addblockedit($id){
 return drupal_get_form('dsje_block_form_edit',$id);
}

function dsje_block_form_edit($form_state,$id) {
		$array = explode('/',$_GET['q']);
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Block', 'dsje/listblock');
  if($array[2] == 'edit'){
     $breadcrumb[] = l('Edit Block', 'dsje/listblock/edit/block/'.$array[4].'');
  }
    drupal_set_breadcrumb($breadcrumb);
	
	$sqlstate = "select * FROM {tbl_block} where block_id='$id' ";
	$resstate = db_query($sqlstate);
	$rsstate = db_fetch_object($resstate);
	
		//location details
  
	$form['state_id'] = array(
	'#type' => 'select',
	'#title' => t('State'),
	'#required' => TRUE,
	'#default_value' =>$rsstate->state_id,
	'#options' => selectstate(),
	'#ahah' => array(
				  'path' => 'rec/district',
				  'method' => 'replace',
				  'effect' => 'slide',
				  'wrapper' =>'zone',
				  ),
	);
	  $form['district_id'] = array(
		'#type' => 'select',
		'#title' => t('District'),
		'#required' => TRUE,
		'#default_value' => $rsstate->district_id,
		'#options' =>GetDistrictStateWise($rs->state_id),
		'#ahah' => array(
						  'path' => 'rec/tehsil',
						  'method' => 'replace',
						  'effect' => 'slide',
						  'wrapper' =>'state',
						  ), 
	);

	

	$form['tehsil_id'] = array(
			'#type' => 'select',
			'#title' => t('Tehsil'),
			'#required' => TRUE,
			'#default_value' => $rsstate->tehsil_id,
			'#options' =>GetTehsilDistrictWise($rs->dsitrict_id,$rs->state_id),
		   
		);
	//end
	
	
	
	$form['prev_state_uid'] = array(
		'#type' => 'hidden',
		'#default_value' => $rsstate->tehsil_uid,
		
	);
	
	$form['block_id'] = array(
		'#type' => 'hidden',
		'#default_value' => $id,
		
	);
	
	$form['prev_state_name'] = array(
		'#type' => 'hidden',
		'#default_value' => $rsstate->tehsil_name,
		
	);
    
	$form['block_name'] = array(
		'#type' => 'textfield',
		'#size' => '20',
		'#title' => t('Block'),
		'#required' => TRUE,
		'#default_value' =>$rsstate->block_name,
		'#maxlength'=>45,
		'#attributes' => array('onkeypress' => 'return alphanumeric(event)'),
	);
	
	
	
	$form['blockid'] = array(
		'#type' => 'hidden',
		'#default_value' => $rsstate->block_name,
		
	);
	
	$form['tehsilid'] = array(
		'#type' => 'hidden',
		'#default_value' => $rsstate->tehsil_id,
		
	);

   $form['districtid'] = array(
		'#type' => 'hidden',
		'#default_value' => $rsstate->district_id,
		
	);
	
	
	 $form['stateid'] = array(
		'#type' => 'hidden',
		'#default_value' => $rsstate->state_id,
		
	);
	/*$form['remarks'] = array(
	    '#type' =>'textarea',
		'#title' => t('Remarks'),
		'#required' => FALSE,
		'#default_value' =>$rsstate->remarks,
		'#cols' => 30,
        '#rows' => 5,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => $rsstate->status,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */

		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'dsje/listblock'),
);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
	
	return $form;
}
function dsje_block_form_edit_validate($form, &$form_state) { 



   global $user;
   
   $array = explode('/',$_GET['q']);
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Block', 'dsje/listblock');
  if($array[2] == 'edit'){
     $breadcrumb[] = l('Edit Block', 'dsje/listblock/edit/block/'.$array[4].'');
  }
    drupal_set_breadcrumb($breadcrumb);
	
	$values = $form_state['values'];
    $tehsil_id = $values['tehsil_id'];
	$block_id = $values['block_id'];
	$state_id =$values['state_id'];
    $district_id = $values['district_id'];
	$block_name = parseData(trim($values['block_name']));
    $district_name = trim($values['district_name']);
	$prev_state_name = $values['prev_state_name'];	
    $remarks = parseData(trim($values['remarks']));
	 $blockid = $values['blockid'];
	  $tehsilid = $values['tehsilid'];
	  
	  $districtid = $values['districtid'];
	   $stateid = $values['stateid'];
    //$status = $values['status'];
	$updatedby = $user->uid;
	$updatedon = time();
	
	
if($blockid == $block_name){}else{
		
		 $sql = "SELECT * FROM {tbl_block} where block_name= '".$block_name."' and tehsil_id = '".$tehsilid."' and district_id = '".$districtid."' and state_id = '".$stateid."'";
	   $res = db_query($sql);
	  
	  if($rs = db_fetch_object($res)){
			$message = getMessage('dsjeblock', 'code06', array("0"=>$block_name));
			form_set_error('block_name', $message);
	   }
	
}
	
	
	if($state_id==''){
			form_set_error('state_id', t('State field is required.'));
		}
		$s2=0;
		if($district_id==''){
			form_set_error('district_id', t('District field is required.'));
		$s2=1;
		}
		
		
		if($district_id == '0')
		{
		form_set_error('district_id', t('District field is required.'));	
			
			
		}
		
		if($tehsil_id == '0')
		{
		form_set_error('tehsil_id', t('Tehsil field is required.'));	
			
			
		}
		
	$s = textonlyn('block_name',$block_name,'Block Name');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	/*if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_tehsil} where LOWER(tehsil_name)= '".strtolower($tehsil_name)."'";
		$res = db_query($sql);
	  
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjeblock', 'code06', array("0"=>$tehsil_name));	
			form_set_error('tehsil_name', $message);
		}
	}*/
	
	 
	
   /* $countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_tehsil} where LOWER(tehsil_name)= '".strtolower($tehsil_name)."' GROUP BY tehsil_id"));
		    $count = $countObj->count;
			
			if( strcmp(strtolower($prev_state_name), strtolower($tehsil_name))==0){
							
			}else{
				if($count==0){
				
				}else{
				
					//db_query("UPDATE `tbl_states` set `state_name` ='".$state_name."'  , `remarks`='".$remarks."' ,`country_id`= '".$country_id."',`zone_id`= '".$zone_id."',updatedby='".$updatedby."'  ,updatedon='".$updatedon."' where state_id='$state_id'");
					//$message = getMessage('recState', 'code06', array("0"=>$state_name));
					//form_set_error('state_name', $message);
					form_set_error('state_name', 'The State Name '.$state_name.' alreday exist.');
					//drupal_goto("rec/liststate");	
				}
			}*/
	 
} 

function dsje_block_form_edit_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $tehsil_id = $values['tehsil_id'];
	$state_id =$values['state_id'];
    $district_id = $values['district_id'];
	//$state_uid = $values['state_uid'];
	$prev_state_uid = $values['prev_state_uid'];
    $block_name = parseData(trim($values['block_name']));
	//$state_union_territory = parseData(trim($values['state_union_territory']));
	$prev_state_name = $values['prev_state_name'];	
    $remarks = parseData(trim($values['remarks']));
	$block_id = $values['block_id'];
	
	$field = "";
	

	
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('block_name',$block_name,'Block Name');
    $s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
   $sql = "UPDATE {tbl_block} set `state_id` ='".$state_id."',`district_id`='".$district_id."' ,`tehsil_id`='".$tehsil_id."' ,`block_name`='".$block_name."' ,`updatedby` ='".$updatedby."',`updatedon`='".$updatedon."' where block_id='".$block_id."'"; 	
    db_query($sql);
	
	$message = getMessage('dsjeblock', 'code10', array("0"=>$block_name));
					drupal_set_message($message);
	
//	drupal_set_message(Block.$block_name .' has been updated successully.');
		drupal_goto('dsje/listblock');
}

/**
 *hook_theme
 */
function dsje_block_theme() {
	
	return array(
				 
		'dsje_block_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_block_form',
                                 ),
        'dsje_block_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_block_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
 function dsje_block_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_block_form_edit'){
	 // $form['zone_id']['#disabled'] = TRUE;
	}
 }


 function block_delete($id,$sno){
	$block_id =  $id;
	//$sql = "select district_id,status from tbl_tehsil WHERE district_id ='".$id."' and status=1";
    //$res = db_query($sql);
    //if($rs = db_fetch_object($res)){
     //form_set_error('form','The District '.$sno.' cannot be disabled as it has other entities mapped to it.');
	 //$st=1;
	 //The Country India cannot be disabled as it has other entities mapped to it.
   //}
   //if($st !=1){
		//db_query("UPDATE {tbl_district} SET status=0 WHERE district_id ='".$state_id."'");
		db_query("UPDATE {tbl_block} SET status=0 WHERE block_id ='".$block_id."'");
		
		$message = getMessage('dsjeblock', 'code07', array("0"=>$sno));
		drupal_set_message($message);
   //}
	drupal_goto("dsje/listblock");
 }

  function block_enable($id,$sno){
	$block_id =  $id;
	//db_query("UPDATE {tbl_states} SET status=1 WHERE state_id ='".$state_id."'");
	db_query("UPDATE {tbl_block} SET status=1 WHERE block_id ='".$block_id."'");
	
	$message = getMessage('dsjeblock', 'code09', array("0"=>$sno));
	drupal_set_message($message);
	drupal_goto("dsje/listblock");
 }


function dsje_addblockview($id){
		$array = explode('/',$_GET['q']);
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Block', 'dsje/listblock');
  if($array[2] == 'view'){
     $breadcrumb[] = l('View Block', 'dsje/listblock/view/block/'.$array[4].'');
  }
  
  
    drupal_set_breadcrumb($breadcrumb);
    $sql = "select * FROM {tbl_block} inner join tbl_tehsil on (tbl_tehsil.tehsil_id = tbl_block.tehsil_id) where block_id = $id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
	$status ='Enabled';
	}else{
	$status ='Disabled';
	}
	
	$remarks = ucfirst($rs->remarks);
	if($remarks==''){$remarks='N/A';}
	
	$state_uid = ucfirst($rs->state_uid);
	if($state_uid==''){$state_uid='N/A';}
	
	$statename = getState($rs->state_id);
	$districtname = getdistrict($rs->district_id);
	$output .='<table cellpadding="2" cellspacing="1" border="0" id="form-container">';
	$output .='<tr class="oddrow"><td colspan="2" align="center"><h2>Block Details</h2></td></tr>';
	$output .='<tr class="evenrow"><td width="50%">Block:</td><td class="normal">'.ucwords($rs->block_name).'</td></tr>';
	$output .='<tr class="oddrow"><td width="50%">Tehsil:</td><td class="normal">'.ucwords($rs->tehsil_name).'</td></tr>';
	$output .='<tr class="evenrow"><td width="50%">District:</td><td class="normal">'.ucwords($districtname).'</td></tr>';
	$output .='<tr class="oddrow"><td width="50%">State:</td><td class="normal">'.ucwords($statename).'</td></tr>';
	$output .='<tr class="evenrow"><td width="50%">Status:</td><td class="normal">'.$status.'</td></tr>';
	$output .='<tr class="oddrow"><td class="back" align="center" colspan="2">'.l(t('Back'), 'dsje/listblock').'</td></tr>';
	$output .='</table>';
	return $output;
}



  
  function myblock() {
    $tehsil_id = $_POST['tehsil_id'];
	$query = "SELECT block_id,	block_name FROM {tbl_block} WHERE tehsil_id = '$tehsil_id' AND status='1' ORDER BY block_name";
	$result = db_query($query);
	
	$statearray1 = array();
	$statearray1[''] = "--Select--";
	$counter = 0;
	while($row=db_fetch_object($result)) {
		$statearray1[$row->block_id] = ucfirst($row->block_name);
		$counter++;
	}
	
	if($counter==0) {
		$statearray1[''] = "--Select--";
	}
	
	$form_state = array('submitted' => FALSE);
	$form_build_id = $_POST['form_build_id'];
	$form = form_builder('dsje_panchayt_form', $form, $form_state);
	$form['block_name'] = array (
							'#type' => 'select',
							'#title' => t('Block'),
							'#required' => TRUE,
							'#default_value' => '',
							'#options' => $statearray1,
							'#id' => 'edit-block-name',
							'#name' => 'block_name',
							'#ahah' => array(
					                 'path' => 'dsje/panchayt',
					                 'method' => 'replace',
					                 'effect' => 'slide',
					       			 'wrapper' =>'panchayt_test',
					  ), 
						
		                    
						 );
	$output = drupal_render($form['block_name']);
	return drupal_json(array('status' => TRUE, 'data' => $output));
}
	
	