<?php

global $base_url;

/**
 *hook_perm
 */
 
function onlinestatement_perm() {
	return array('edit onlinestatement','administer onlinestatement', 'create onlinestatement', 'view onlinestatement');
}

function onlinestatement_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit onlinestatement', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create onlinestatement', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view onlinestatement', $account);
	}
	
}


function onlinestatement_menu(){

  $items['onlinestatementreport'] = array(
										'title' => t('Online Statement'),
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'onlinestatementreport',
										'access arguments' => array('view onlinestatement'),
													 
									  );
									
   $items['dsje/sector'] = array(
										'page callback' => 'mysector2',
										'type' => MENU_CALLBACK,
										'access arguments' => array('access content'),
										);
										
										
										
   return $items;
}

function onlinestatementreport(){
  $array = explode('/',$_GET['q']);
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Online Statement', 'onlinestatementreport');
  drupal_set_breadcrumb($breadcrumb);
  return drupal_get_form('onlinestatementreport_form');
}

function onlinestatementreport_form(){
  global $base_url;
  global $user;
  //print_r($user->roles); exit;
  foreach($user->roles as $value){
      if($value == 'Loanee'){
          $account_id = isset($user->name)?$user->name:'';
      }else{
          $account_id = NULL;
      }
  }
  
  $form['account'] = array(
                    '#type' => 'textfield',
                    '#default_value' => $account_id,
                    '#required' => TRUE,
                   // '#attributes' => array('class' => 'disable-text'),
                );
  
  $form['submit'] = array(
      '#type' =>'button',
      '#value' =>'Generate Report',
     // '#attributes' => array('class' => 'disable-text'),
      
  ); 
  return $form;
}

 function onlinestatement_theme() {	
	return array(
		'onlinestatementreport_form' => array(
				'arguments' => array('form' => NULL),
				'template' => 'onlinestatement_form',
                ),							 
 );
}
