<?php
function dsje_testModule_init() {
	//drupal_add_css(drupal_get_path('module', 'rec_language') .'/rec_language.css');
	
}


function dsje_testModule_perm() {
	return array('edit dsje_testModule','administer dsje_testModule', 'create dsje_testModule', 'view dsje_testModule');
}

function dsje_testModule_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_testModule', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_testModule', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_testModule', $account);
	}
	
}

function dsje_testModule_menu() {
	
	
	$items['dsje/listtestModule'] = array(
										'title' => t('List of testModule'),
										'description' => 'Allow user to View testModule',
										'type' => MENU_CALLBACK,
										'page callback' => 'viewtestModule',
										'access arguments' => array('administer dsje_testModule'),
													 
									  );
	
	$items['dsje/listtestModule/addtestModule'] = array(
										'title' => t('Create testModule'),
										'description' => 'Allow user to add testModule',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_testModule',
										'access arguments' => array('administer dsje_testModule'),
													 
									  );
   	$items['dsje/listtestModule/edit/testModule/%'] = array(
								
										'title' => t('Edit testModule'),
										'description' => 'Allow user to add testModule',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addtestModuleedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_testModule'),
													 
									  );
   $items['dsje/listtestModule/view/testModule/%'] = array(
								
										'title' => t('View testModule'),
										'description' => 'Allow user to add testModule',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addtestModuleview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_testModule'),
													 
									  );
     $items['dsje/del/testModule/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'testModule_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_testModule'),
													 
									  );
    $items['dsje/enable/testModule/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'testModule_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_testModule'),
													 
									  );
	return $items;
}


/**
 listing testModule
 */

function viewtestModule(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjetestModule', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('testModule'), 'field' => 'testModule_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT testModule_id, testModule_name, status FROM tbl_testModules where UPPER(testModule_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_testModules where UPPER(testModule_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT testModule_id, testModule_name, status FROM tbl_testModules ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjetestModule', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','dsje/listtestModule');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjetestModule', 'code01', NULL),"dsje/listtestModule/addtestModule");
   	$lising = getMessage( 'dsjetestModule', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","dsje/listtestModule/edit/testModule/".$row->testModule_id,array('attributes'=>array('id'=>'edit-testModule-id')));
		$viewurl = l("View","dsje/listtestModule/view/testModule/".$row->testModule_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","dsje/del/testModule/$row->testModule_id/$row->testModule_name");
        }else{
		  $deleteurl = l("Enable","dsje/enable/testModule/$row->testModule_id/$row->testModule_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->testModule_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_testModule(){
 return drupal_get_form('dsje_testModule_form');
}

function dsje_testModule_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of testModule', 'dsje/listtestModule');
  if($array[3] == 'addtestModule'){
     $breadcrumb[] = l('Add testModule', 'dsje/listtestModule/addtestModule');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['testModule_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('testModule Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,		
        '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	);

	
	$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	);
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
	return $form;
}

function dsje_testModule_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $testModule_name = trim($values['testModule_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('testModule_name',$testModule_name,'testModule');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_testModules` (`testModule_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$testModule_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjetestModule', 'code05', array("0"=>$testModule_name));
		drupal_set_message($message);
	   drupal_goto('dsje/listtestModule');
	}
}

function dsje_testModule_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$testModule_name = trim($values['testModule_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('testModule_name',$testModule_name,'testModule');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_testModules} where UCASE(testModule_name)= '".strtoupper($testModule_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjetestModule', 'code06', array("0"=>$testModule_name));
			form_set_error('testModule_name', $message);
		}
	}	
}

function rec_addtestModuleedit($testModule_id){
 return drupal_get_form('dsje_testModule_form_edit',$testModule_id);
}

function dsje_testModule_form_edit(&$form_states,$testModule_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List testModule', 'dsje/listtestModule');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit testModule', 'dsje/listtestModule/edit/testModule/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqltestModule = "select * from tbl_testModules where testModule_id=$testModule_id";
	$restestModule = db_query($sqltestModule);
	$rstestModule = db_fetch_object($restestModule);
	
	$form['testModule_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rstestModule->testModule_id,
	);
	
	$form['testModule_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('testModule Name'),
		'#required' => TRUE,
		'#default_value' =>$rstestModule->testModule_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_testModule_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rstestModule->testModule_name,
	);

	$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rstestModule->remarks,
		'#rows' =>5,
		'#cols' =>30,
		'#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
	return $form;
}

function dsje_testModule_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$testModule_id = $values['testModule_id'];
	$testModule_name = ParseData($values['testModule_name']);
	$prev_testModule_name = ParseData($values['prev_testModule_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('testModule_name',$testModule_name,'testModule');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_testModules} where LOWER(testModule_name)= '".strtolower($testModule_name)."' GROUP BY testModule_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_testModule_name), strtolower($testModule_name))==0){
			db_query("UPDATE `tbl_testModules` set `testModule_name` = '".$testModule_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where testModule_id='".$testModule_id."'");
			
			$message = getMessage('dsjetestModule', 'code05', array("0"=>$testModule_name));
			drupal_set_message($message);
			drupal_goto("dsje/listtestModule");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_testModules` set `testModule_name` = '".$testModule_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where testModule_id='".$testModule_id."'");
				
				$message = getMessage('dsjetestModule', 'code05', array("0"=>$testModule_name));
				drupal_set_message($message);
				drupal_goto("dsje/listtestModule");	
			
			}else{
				db_query("UPDATE `tbl_testModules` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where testModule_id='".$testModule_id."'");
				
				$message = getMessage('dsjetestModule', 'code06', array("0"=>$testModule_name));
				form_set_error('testModule_name', $message);
			}
		}
	}
}

function dsje_testModule_theme() {
	
	return array(
				 
		'dsje_testModule_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_testModule_form',
                                 ),
        'dsje_testModule_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_testModule_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_testModule_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_testModule_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_testModule_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function testModule_delete($sid, $sno){
  $testModule_id =  $sid;
  db_query("UPDATE {tbl_testModules} SET status=0 WHERE testModule_id ='".$testModule_id."'");
  $message = getMessage('dsjetestModule', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("dsje/listtestModule");
 }


  function testModule_enable($sid, $sno){
    $testModule_id =  $sid;
    db_query("UPDATE {tbl_testModules} SET status=1 WHERE testModule_id ='".$testModule_id."'");
  
    $message = getMessage('dsjetestModule', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("dsje/listtestModule");
  }

  function rec_addtestModuleview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List testModule', 'dsje/listtestModule');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View testModule', 'dsje/listtestModule/view/testModule/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_testModules where testModule_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>testModule Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>testModule:</td><td>'.ucwords($rs->testModule_name).'</td></tr>';
 $output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
 return $output;
  }
	
	