<?php

/**
 *@hook_menu
 */

function hpbc_cron_jobs_menu(){
	$items['apply_quarter_interest'] = array(
			'title' => 'Apply Quarter Interest',
			'page callback' => 'int_loan_db_write',
			'type' => MENU_NORMAL_ITEM,
			'access arguments' => array('access content'),
	);
	return $items;
}

function int_loan_db_write(){
	return drupal_get_form('int_loan_db_write_form');
}


function int_loan_db_write_form(){
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('Control Panel', 'node/211');
	$breadcrumb[] = l('Apply Quarter Interest', 'int-db-write');
	drupal_set_breadcrumb($breadcrumb);
	
	$form['submit'] = array(
			'#type' =>'button',
			'#default_value' =>'Apply Qaurter Interest on Live Loan Accounts',);
	return $form;
}

function int_loan_db_write_form_validate($form,&$form_state){
	// Write validation here.
}

/**
 *@ hook_theme
 */
function hpbc_cron_jobs_theme() {
	return array(
			'int_loan_db_write_form' => array(
					'arguments' => array('form' => NULL),
					'template' => 'int_loan_db_write_form',),);

}







/**
 * @File
 * Create custom cron jobs and check there execution
 */
function hpbc_cron_jobs_cron() {
	$live_loan_accounts = filter_live_loan_accounts();
	
	$file = drupal_get_path('module','hpbc_cron_jobs').'/tmp/interest_tmp.txt';
	if(file_exists($file)){
		return;
	}
	
	foreach($live_loan_accounts as $loan){
		global $base_url;
		$loan_id = $loan['loan_id'];
		$account_id = $loan['account_id'];
		$o_principal = $loan['o_principal'];
		$last_interest_calculated = $loan['last_interest_calculated'];
		$quarter_end_date = $loan['quarter_end_date'];
		$ROI = $loan['ROI'];
		$loanee_id = $loan['loanee_id']; 
		$project_cost = $loan['project_cost'];
		$o_principle = $loan['o_principle'];
		
		if (isset($o_principle)) {
			$interest_value = interest_calculation_regular($account_id, $o_principle, $last_interest_calculated, $quarter_end_date, $ROI);
		}else {
			// Interest must be calculated on total term loan value.
			$sqlp = "select amount
			            from tbl_loan_repayment
					    where loanee_id = '" . $loanee_id . "' AND paytype = 'Promoter Share'";
			$resp = db_query($sqlp);
			$rsp = db_fetch_object($resp);
		
			$o_principal = $project_cost - $rsp->amount;
			$interest_value = interest_calculation_first($account_id, $o_principal, $last_interest_calculated, $quarter_end_date, $ROI);
		}
		
		$final_principal = $o_principal + $interest_value;
		$result_text = $loan_id."|".$account_id."|".$interest_value."|".$last_interest_calculated."|".$quarter_end_date."|".$o_principal."\n";
		
		if(file_put_contents($file, $result_text, FILE_APPEND | LOCK_EX)){
			$backfile = drupal_get_path('module','hpbc_cron_jobs').'/int_records/int-'.date('Y-m-d').'.txt.bak';
			if (!copy($file, $backfile)) {
				echo "failed to copy $file...\n";
			}
		}
		
	}
}


/**
 * Interact with database and create business logic to filter live loan accounts in an array.
 */

function filter_live_loan_accounts(){
	$sqlg = "SELECT `account_id`,`loan_id`,`o_principal`,`last_interest_calculated`,`ROI`,`project_cost`,`loanee_id`
			 FROM `tbl_loan_detail` AS `tl`
			 LEFT JOIN `tbl_loanee_detail` AS `tle`
			 ON `tl`.reg_number=`tle`.reg_number WHERE `tl`.`o_principal` != 0.0";
	
	$resg = db_query($sqlg);
	while ($rsg = db_fetch_object($resg)) {
		db_query('START TRANSACTION');
		db_query('BEGIN');
		$loan['loan_id'] = $rsg->loan_id;
		$loan['loanee_id'] = $rsg->loanee_id;
		$loan['account_id'] = $rsg->account_id;
		$loan['project_cost'] = $rsg->project_cost;
		$loan['o_principal'] = $rsg->o_principal;
		$loan['last_interest_calculated'] = $rsg->last_interest_calculated;
		$loan['quarter_end_date'] = date('Y-m-d');
		$loan['ROI'] = $rsg->ROI;
		
		$sqlint = db_query("SELECT `o_principle` FROM `tbl_loan_interestld` WHERE account_id = '".$loan['account_id']."' ORDER BY id DESC LIMIT 1");
		$sqlin = db_fetch_object($sqlint);
		$loan['o_principle'] = $sqlin->o_principle;
		$live_loan_accounts[] = $loan;
	}
	return $live_loan_accounts;
}




