<?php
function dsje_payType_init() {
	//drupal_add_css(drupal_get_path('module', 'rec_language') .'/rec_language.css');
	
}


function dsje_payType_perm() {
	return array('edit dsje_payType','administer dsje_payType', 'create dsje_payType', 'view dsje_payType');
}

function dsje_payType_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_payType', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_payType', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_payType', $account);
	}
	
}

function dsje_payType_menu() {
	
	
	$items['admin/dsje/listpayType'] = array(
										'title' => t('List of Pay Type'),
										'description' => 'Allow user to View payType',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewpayType',
										'access arguments' => array('administer dsje_payType'),
													 
									  );
	
	$items['admin/dsje/listpayType/addpayType'] = array(
										'title' => t('Create Pay Type'),
										'description' => 'Allow user to add payType',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_payType',
										'access arguments' => array('administer dsje_payType'),
													 
									  );
   	$items['admin/dsje/listpayType/edit/payType/%'] = array(
								
										'title' => t('Edit Pay Type'),
										'description' => 'Allow user to add payType',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addpayTypeedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_payType'),
													 
									  );
   $items['admin/dsje/listpayType/view/payType/%'] = array(
								
										'title' => t('View Pay Type'),
										'description' => 'Allow user to add payType',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addpayTypeview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_payType'),
													 
									  );
     $items['admin/dsje/del/payType/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'payType_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_payType'),
													 
									  );
    $items['admin/dsje/enable/payType/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'payType_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_payType'),
													 
									  );
	return $items;
}


/**
 listing payType
 */

function viewpayType(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjepayType', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('payType'), 'field' => 'payType_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List payType', 'admin/dsje/listpayType/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT payType_id, payType_name, status FROM tbl_dsje_payTypes where UPPER(payType_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_dsje_payTypes where UPPER(payType_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT payType_id, payType_name, status FROM tbl_dsje_payTypes ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjepayType', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listpayType');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjepayType', 'code01', NULL),"admin/dsje/listpayType/addpayType");
   	$lising = getMessage( 'dsjepayType', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listpayType/edit/payType/".$row->payType_id,array('attributes'=>array('id'=>'edit-payType-id')));
		$viewurl = l("View","admin/dsje/listpayType/view/payType/".$row->payType_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/payType/$row->payType_id/$row->payType_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/payType/$row->payType_id/$row->payType_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->payType_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_payType(){
 return drupal_get_form('dsje_payType_form');
}

function dsje_payType_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of payType', 'admin/dsje/listpayType');
  if($array[3] == 'addpayType'){
     $breadcrumb[] = l('Add payType', 'admin/dsje/listpayType/addpayType');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['payType_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('payType Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listpayType'),
);
	return $form;
}

function dsje_payType_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $payType_name = trim($values['payType_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('payType_name',$payType_name,'payType');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_dsje_payTypes` (`payType_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$payType_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjepayType', 'code05', array("0"=>$payType_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listpayType');
	}
}

function dsje_payType_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$payType_name = trim($values['payType_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('payType_name',$payType_name,'payType');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_dsje_payTypes} where UCASE(payType_name)= '".strtoupper($payType_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjepayType', 'code06', array("0"=>$payType_name));
			form_set_error('payType_name', $message);
		}
	}	
}

function rec_addpayTypeedit($payType_id){
 return drupal_get_form('dsje_payType_form_edit',$payType_id);
}

function dsje_payType_form_edit(&$form_states,$payType_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List payType', 'admin/dsje/listpayType');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit payType', 'admin/dsje/listpayType/edit/payType/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlpayType = "select * from tbl_dsje_payTypes where payType_id=$payType_id";
	$respayType = db_query($sqlpayType);
	$rspayType = db_fetch_object($respayType);
	
	$form['payType_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rspayType->payType_id,
	);
	
	$form['payType_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('payType Name'),
		'#required' => TRUE,
		'#default_value' =>$rspayType->payType_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_payType_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rspayType->payType_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rspayType->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listpayType'),
);
	return $form;
}

function dsje_payType_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$payType_id = $values['payType_id'];
	$payType_name = ParseData($values['payType_name']);
	$prev_payType_name = ParseData($values['prev_payType_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('payType_name',$payType_name,'payType');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_dsje_payTypes} where LOWER(payType_name)= '".strtolower($payType_name)."' GROUP BY payType_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_payType_name), strtolower($payType_name))==0){
			db_query("UPDATE `tbl_dsje_payTypes` set `payType_name` = '".$payType_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where payType_id='".$payType_id."'");
			
			$message = getMessage('dsjepayType', 'code05', array("0"=>$payType_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listpayType");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_dsje_payTypes` set `payType_name` = '".$payType_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where payType_id='".$payType_id."'");
				
				$message = getMessage('dsjepayType', 'code05', array("0"=>$payType_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listpayType");	
			
			}else{
				db_query("UPDATE `tbl_dsje_payTypes` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where payType_id='".$payType_id."'");
				
				$message = getMessage('dsjepayType', 'code06', array("0"=>$payType_name));
				form_set_error('payType_name', $message);
			}
		}
	}
}

function dsje_payType_theme() {
	
	return array(
				 
		'dsje_payType_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_payType_form',
                                 ),
        'dsje_payType_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_payType_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_payType_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_payType_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_payType_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function payType_delete($sid, $sno){
  $payType_id =  $sid;
  db_query("UPDATE {tbl_dsje_payTypes} SET status=0 WHERE payType_id ='".$payType_id."'");
  $message = getMessage('dsjepayType', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listpayType");
 }


  function payType_enable($sid, $sno){
    $payType_id =  $sid;
    db_query("UPDATE {tbl_dsje_payTypes} SET status=1 WHERE payType_id ='".$payType_id."'");
  
    $message = getMessage('dsjepayType', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listpayType");
  }

  function rec_addpayTypeview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List payType', 'admin/dsje/listpayType');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View payType', 'admin/dsje/listpayType/view/payType/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_dsje_payTypes where payType_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>payType Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>payType:</td><td>'.ucwords($rs->payType_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listpayType');
 return $output;
  }
	
	