<?php
function dsje_grading_init() {
	//drupal_add_css(drupal_get_path('module', 'dsje_language') .'/dsje_language.css');
	
}


function dsje_grading_perm() {
	return array('edit dsje_grading','administer dsje_grading', 'create dsje_grading', 'view dsje_grading');
}

function dsje_grading_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_grading', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_grading', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_grading', $account);
	}
	
}

function dsje_grading_menu() {
	
	
	$items['admin/dsje/listgrading'] = array(
										'title' => t('List of grading'),
										'description' => 'Allow user to View grading',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewgrading',
										'access arguments' => array('administer dsje_grading'),
													 
									  );
	
	$items['admin/dsje/listgrading/addgrading'] = array(
										'title' => t('Create grading'),
										'description' => 'Allow user to add grading',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_grading',
										'access arguments' => array('administer dsje_grading'),
													 
									  );
   	$items['admin/dsje/listgrading/edit/grading/%'] = array(
								
										'title' => t('Edit grading'),
										'description' => 'Allow user to add grading',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addgradingedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_grading'),
													 
									  );
   $items['admin/dsje/listgrading/view/grading/%'] = array(
								
										'title' => t('View grading'),
										'description' => 'Allow user to add grading',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addgradingview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_grading'),
													 
									  );
     $items['admin/dsje/del/grading/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'grading_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_grading'),
													 
									  );
    $items['admin/dsje/enable/grading/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'grading_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_grading'),
													 
									  );
	return $items;
}


/**
 listing grading
 */

function viewgrading(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjegrading', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('grading'), 'field' => 'grading_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List grading', 'admin/dsje/listgrading/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT grading_id, grading_name, status FROM tbl_gradings where UPPER(grading_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_gradings where UPPER(grading_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT grading_id, grading_name, status FROM tbl_gradings ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjegrading', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listgrading');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjegrading', 'code01', NULL),"admin/dsje/listgrading/addgrading");
   	$lising = getMessage( 'dsjegrading', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listgrading/edit/grading/".$row->grading_id,array('attributes'=>array('id'=>'edit-grading-id')));
		$viewurl = l("View","admin/dsje/listgrading/view/grading/".$row->grading_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/grading/$row->grading_id/$row->grading_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/grading/$row->grading_id/$row->grading_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->grading_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_grading(){
 return drupal_get_form('dsje_grading_form');
}

function dsje_grading_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of grading', 'admin/dsje/listgrading');
  if($array[3] == 'addgrading'){
     $breadcrumb[] = l('Add grading', 'admin/dsje/listgrading/addgrading');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['grading_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('grading Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listgrading'),
);
	return $form;
}

function dsje_grading_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $grading_name = trim($values['grading_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('grading_name',$grading_name,'grading');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_gradings` (`grading_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$grading_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjegrading', 'code05', array("0"=>$grading_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listgrading');
	}
}

function dsje_grading_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$grading_name = trim($values['grading_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('grading_name',$grading_name,'grading');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_gradings} where UCASE(grading_name)= '".strtoupper($grading_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjegrading', 'code06', array("0"=>$grading_name));
			form_set_error('grading_name', $message);
		}
	}	
}

function dsje_addgradingedit($grading_id){
 return drupal_get_form('dsje_grading_form_edit',$grading_id);
}

function dsje_grading_form_edit(&$form_states,$grading_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List grading', 'admin/dsje/listgrading');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit grading', 'admin/dsje/listgrading/edit/grading/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlgrading = "select * from tbl_gradings where grading_id=$grading_id";
	$resgrading = db_query($sqlgrading);
	$rsgrading = db_fetch_object($resgrading);
	
	$form['grading_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsgrading->grading_id,
	);
	
	$form['grading_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('grading Name'),
		'#required' => TRUE,
		'#default_value' =>$rsgrading->grading_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_grading_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsgrading->grading_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rsgrading->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listgrading'),
);
	return $form;
}

function dsje_grading_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$grading_id = $values['grading_id'];
	$grading_name = ParseData($values['grading_name']);
	$prev_grading_name = ParseData($values['prev_grading_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('grading_name',$grading_name,'grading');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_gradings} where LOWER(grading_name)= '".strtolower($grading_name)."' GROUP BY grading_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_grading_name), strtolower($grading_name))==0){
			db_query("UPDATE `tbl_gradings` set `grading_name` = '".$grading_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where grading_id='".$grading_id."'");
			
			$message = getMessage('dsjegrading', 'code05', array("0"=>$grading_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listgrading");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_gradings` set `grading_name` = '".$grading_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where grading_id='".$grading_id."'");
				
				$message = getMessage('dsjegrading', 'code05', array("0"=>$grading_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listgrading");	
			
			}else{
				db_query("UPDATE `tbl_gradings` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where grading_id='".$grading_id."'");
				
				$message = getMessage('dsjegrading', 'code06', array("0"=>$grading_name));
				form_set_error('grading_name', $message);
			}
		}
	}
}

function dsje_grading_theme() {
	
	return array(
				 
		'dsje_grading_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_grading_form',
                                 ),
        'dsje_grading_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_grading_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_grading_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_grading_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_grading_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function grading_delete($sid, $sno){
  $grading_id =  $sid;
  db_query("UPDATE {tbl_gradings} SET status=0 WHERE grading_id ='".$grading_id."'");
  $message = getMessage('dsjegrading', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listgrading");
 }


  function grading_enable($sid, $sno){
    $grading_id =  $sid;
    db_query("UPDATE {tbl_gradings} SET status=1 WHERE grading_id ='".$grading_id."'");
  
    $message = getMessage('dsjegrading', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listgrading");
  }

  function dsje_addgradingview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List grading', 'admin/dsje/listgrading');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View grading', 'admin/dsje/listgrading/view/grading/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_gradings where grading_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>grading Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>grading:</td><td>'.ucwords($rs->grading_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listgrading');
 return $output;
  }
	
	