<?php
function dsje_disability_init() {
	//drupal_add_css(drupal_get_path('module', 'dsje_language') .'/dsje_language.css');
	
}


function dsje_disability_perm() {
	return array('edit dsje_disability','administer dsje_disability', 'create dsje_disability', 'view dsje_disability');
}

function dsje_disability_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_disability', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_disability', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_disability', $account);
	}
	
}

function dsje_disability_menu() {
	
	
	$items['admin/dsje/listdisability'] = array(
										'title' => t('List of disability'),
										'description' => 'Allow user to View disability',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewdisability',
										'access arguments' => array('administer dsje_disability'),
													 
									  );
	
	$items['admin/dsje/listdisability/adddisability'] = array(
										'title' => t('Create disability'),
										'description' => 'Allow user to add disability',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_disability',
										'access arguments' => array('administer dsje_disability'),
													 
									  );
   	$items['admin/dsje/listdisability/edit/disability/%'] = array(
								
										'title' => t('Edit disability'),
										'description' => 'Allow user to add disability',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_adddisabilityedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_disability'),
													 
									  );
   $items['admin/dsje/listdisability/view/disability/%'] = array(
								
										'title' => t('View disability'),
										'description' => 'Allow user to add disability',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_adddisabilityview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_disability'),
													 
									  );
     $items['admin/dsje/del/disability/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'disability_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_disability'),
													 
									  );
    $items['admin/dsje/enable/disability/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'disability_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_disability'),
													 
									  );
	return $items;
}


/**
 listing disability
 */

function viewdisability(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjedisability', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('disability'), 'field' => 'disability_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List disability', 'admin/dsje/listdisability/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT disability_id, disability_name, status FROM tbl_disabilitys where UPPER(disability_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_disabilitys where UPPER(disability_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT disability_id, disability_name, status FROM tbl_disabilitys ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjedisability', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listdisability');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjedisability', 'code01', NULL),"admin/dsje/listdisability/adddisability");
   	$lising = getMessage( 'dsjedisability', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listdisability/edit/disability/".$row->disability_id,array('attributes'=>array('id'=>'edit-disability-id')));
		$viewurl = l("View","admin/dsje/listdisability/view/disability/".$row->disability_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/disability/$row->disability_id/$row->disability_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/disability/$row->disability_id/$row->disability_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->disability_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_disability(){
 return drupal_get_form('dsje_disability_form');
}

function dsje_disability_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of disability', 'admin/dsje/listdisability');
  if($array[3] == 'adddisability'){
     $breadcrumb[] = l('Add disability', 'admin/dsje/listdisability/adddisability');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['disability_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('disability Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listdisability'),
);
	return $form;
}

function dsje_disability_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $disability_name = trim($values['disability_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('disability_name',$disability_name,'disability');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_disabilitys` (`disability_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$disability_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjedisability', 'code05', array("0"=>$disability_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listdisability');
	}
}

function dsje_disability_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$disability_name = trim($values['disability_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('disability_name',$disability_name,'disability');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_disabilitys} where UCASE(disability_name)= '".strtoupper($disability_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjedisability', 'code06', array("0"=>$disability_name));
			form_set_error('disability_name', $message);
		}
	}	
}

function dsje_adddisabilityedit($disability_id){
 return drupal_get_form('dsje_disability_form_edit',$disability_id);
}

function dsje_disability_form_edit(&$form_states,$disability_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List disability', 'admin/dsje/listdisability');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit disability', 'admin/dsje/listdisability/edit/disability/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqldisability = "select * from tbl_disabilitys where disability_id=$disability_id";
	$resdisability = db_query($sqldisability);
	$rsdisability = db_fetch_object($resdisability);
	
	$form['disability_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsdisability->disability_id,
	);
	
	$form['disability_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('disability Name'),
		'#required' => TRUE,
		'#default_value' =>$rsdisability->disability_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_disability_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsdisability->disability_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rsdisability->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listdisability'),
);
	return $form;
}

function dsje_disability_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$disability_id = $values['disability_id'];
	$disability_name = ParseData($values['disability_name']);
	$prev_disability_name = ParseData($values['prev_disability_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('disability_name',$disability_name,'disability');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_disabilitys} where LOWER(disability_name)= '".strtolower($disability_name)."' GROUP BY disability_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_disability_name), strtolower($disability_name))==0){
			db_query("UPDATE `tbl_disabilitys` set `disability_name` = '".$disability_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where disability_id='".$disability_id."'");
			
			$message = getMessage('dsjedisability', 'code05', array("0"=>$disability_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listdisability");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_disabilitys` set `disability_name` = '".$disability_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where disability_id='".$disability_id."'");
				
				$message = getMessage('dsjedisability', 'code05', array("0"=>$disability_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listdisability");	
			
			}else{
				db_query("UPDATE `tbl_disabilitys` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where disability_id='".$disability_id."'");
				
				$message = getMessage('dsjedisability', 'code06', array("0"=>$disability_name));
				form_set_error('disability_name', $message);
			}
		}
	}
}

function dsje_disability_theme() {
	
	return array(
				 
		'dsje_disability_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_disability_form',
                                 ),
        'dsje_disability_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_disability_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_disability_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_disability_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_disability_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function disability_delete($sid, $sno){
  $disability_id =  $sid;
  db_query("UPDATE {tbl_disabilitys} SET status=0 WHERE disability_id ='".$disability_id."'");
  $message = getMessage('dsjedisability', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listdisability");
 }


  function disability_enable($sid, $sno){
    $disability_id =  $sid;
    db_query("UPDATE {tbl_disabilitys} SET status=1 WHERE disability_id ='".$disability_id."'");
  
    $message = getMessage('dsjedisability', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listdisability");
  }

  function dsje_adddisabilityview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List disability', 'admin/dsje/listdisability');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View disability', 'admin/dsje/listdisability/view/disability/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_disabilitys where disability_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>disability Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>disability:</td><td>'.ucwords($rs->disability_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listdisability');
 return $output;
  }
	
	