<?php

function grievance_init() {
	//drupal_add_css(drupal_get_path('module', 'grievance') .'/grievance.css');
	drupal_add_js(drupal_get_path('module', 'rti_management') .'/rti_management.js');
}

function grievance_node_info() {
	return array (
					'grievance' => array (
										'name' => t('Grievance'),
										'module' => 'grievance',
										'description' => "Creates a New Grievance",
										'has_title' => TRUE,
										'title_label' => t('grievance Name'),
										'has_body' => FALSE,
										),
				);
}

function grievance_perm() {
	return array('edit grievance','administer grievance', 'create grievance', 'view grievance');
}

function grievance_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit grievance', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create grievance', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view grievance', $account);
	}
	
}

function grievance_menu() {

 $items['dsje/listgrievance'] = 	array(
	    'title' => t('List of Grievance'),
		'description' => 'Allow user to Grievance',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'grievance_list',
		'access arguments' => array('administer grievance'), 
	   
	   
	  );
	  
	  
$items['dsje/listgrievance/view'] = 	array(
	    'title' => t('List of Grievance'),
		'description' => 'Allow user to Grievance',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'grievance_listview',
		'access arguments' => array('administer grievance'), 
	   
	   
	  );	  
	  
$items['dsje/del/grievance/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'grievance_close',
		                                'page arguments' => array(3,4),
		                                'access arguments' => array('administer grievance'),
													 
									  );
 $items['dsje/enable/grievance/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'grievance_enable',
		                                'page arguments' => array(3,4),
		                                'access arguments' => array('administer grievance'),
													 
									  );  
									  
									  
									  
 	$items['dsje/close/grievance/%'] = array(
										'title' => t('Add Comment'),
										'description' => 'Allow user to add Grievance',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addclose',
										 'page arguments' => array(3),
										'access arguments' => array('administer grievance'),
													 
									  );  
	  
     
   
	
	
	

	return $items;
}


function grievance_listview(){

     global $user;
	global $base_url;
	global $xpathObj;
	
$uid=$user->uid;	
	
	$limit = (int)getMessage( 'dsjegrievance', 'code04', NULL);
  $cuser = user_load($user->uid);
  $roles = implode(',',array_flip($cuser->roles));
  
  /* $sqlrole = "select rid from users_roles where uid='".$uid."'";
$res = db_query($sqlrole);
$rs = db_fetch_object($res);
$as = $rs->rid;*/


$axs=db_query("select * from tbl_grievance where grievance_status ='Pending' ");
$acd=db_fetch_object($axs);
$wsd=$acd->nid;


$sqlrole = "select * from users_roles where uid='".$uid."'";
$res = db_query($sqlrole);
$rs = db_fetch_object($res);
$as = $rs->rid;	
	
	$dq="select * from tbl_workflow_details where role='$as'";
	$sql=db_query($dq);
	$sx=db_fetch_object($sql);
	$sdf=$sx->role;
	
	//if($sdf == 38 || $sdf == 5 || $sdf == 19 || $sdf == 6)
	
	if($sdf == 38)
	{
	
	$header = array(
		array('data' => t('S. No.')),
		array('data' => t('Application No.'), 'field' => 'ld.vid', 'sort' => 'asc'),
	     //array('data' => t('Office'), 'field' => 'tbl_corporations.corporation_name', 'sort' => 'asc'),
		  array('data' => t('Applicant Name'), 'field' => 'ld.application_name', 'sort' => 'asc'),
		 
		  array('data' => t('Status')),
       array('data' => t('Action')),
		
	);
	
	
	
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List of Grievance', 'dsje/listgrievance/view'.$array[2].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
 if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	
$query="SELECT * FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5' AND wdetail.level = wt.level AND wt.status = 0 AND (ld.application_name Like '$val' OR ld.appno like '".$val."' OR ld.grievance_status Like '$val' OR ld.remarks Like '$val' )".tablesort_sql($header); 

	
	$sqlcount="SELECT COUNT(*) as count  FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5' AND wdetail.level = wt.level AND wt.status = 0 AND (ld.application_name Like '$val' OR ld.appno like '".$val."' OR ld.grievance_status Like '$val' OR ld.remarks Like '$val')".tablesort_sql($header); 

	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
	 $_REQUEST['page']=0;
 
 }else{
     $query="SELECT ld.appno,ld.application_name,ld.remarks,ld.grievance_status,ld.nid FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5' AND wdetail.level = wt.level AND wt.status = 0".tablesort_sql($header);

 }
global $base_url;
$action = $base_url.'/dsje/listgrievance/view';
 
 $output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjegrievance', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','dsje/listgrievance/view');
	}
	$addurl = l(getMessage( 'dsjegrievance', 'code01', NULL),"node/add/grievance");
	$output .='</td><td colspan="3" class="tblHeaderRight"></td></tr>';
	 $viewall=l("View All",'dsje/listgrievance'); 
   	$lising = getMessage( 'dsjegrievance', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'&nbsp;'.$viewall.'</span></td>
	<td colspan="3" class="tblHeaderRight"><input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';
 
	$result =pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($rs=db_fetch_object($result)) {
	
	$counter++;
	
	if($rs->grievance_status  != 'Close'){
	
		
		$editurl = l("Edit","node/$rs->nid/edit");
		$viewurl = l("View","node/$rs->nid");
		$deleteurl = l("Delete","node/$rs->nid/delete");
		$close=l("Close","dsje/close/grievance/$rs->nid");
		$action = $viewurl." | ".$close;
		}
		
		else{
		
		$viewurl = l("View","node/$rs->nid");
		$action = $viewurl;
		}
		
		
		
		/*if($row->grievance_status=='Pending'){
		  $close = l("Pending","dsje/close/grievance/$rs->nid");
		}else{
		  $close = l("Close","dsje/close/grievance/$rs->nid");
		}*/
		
		if($rs->grievance_status=='Pending'){
		       $st='Pending';
		    }else{
			   $st ='Close';
			}
		
		
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => $rs->appno),
			array('data' => $rs->application_name),
			
			
			
			array('data' => $st),
			//array('data' => $viewurl." | ".$editurl." | ".$deleteurl),
array('data' => $action),
		);
	}
	 
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	
	$output .= theme('pager', NULL, $limit,0 );
	
	return $output;
	
	}
  else
  {
  
   $cuser = user_load($user->uid);
  $roles = implode(',',array_flip($cuser->roles));
  
 $header = array(
		array('data' => t('S. No.')),
		array('data' => t('Application No.'), 'field' => 'ld.vid', 'sort' => 'asc'),
	     //array('data' => t('Office'), 'field' => 'tbl_corporations.corporation_name', 'sort' => 'asc'),
		  array('data' => t('Applicant Name'), 'field' => 'ld.application_name', 'sort' => 'asc'),
		 
		  array('data' => t('Status')),
      array('data' => t('Action'),'class' => 'addeditview',),
		
	);
	
	
	
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List of Grievance', 'dsje/listgrievance/view'.$array[2].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
 if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	
	
	 
	
	$query="SELECT * FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5'  AND wdetail.level = wt.level AND wt.status = 0 and ld.createdby='".$uid."' AND (ld.application_name Like '$val' OR ld.appno like '".$val."' OR ld.grievance_status Like '$val' OR ld.remarks Like '$val')".tablesort_sql($header); 
	
	$sqlcount="SELECT COUNT(*) as count  FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5'  AND wdetail.level = wt.level AND wt.status = 0 and ld.createdby='".$uid."' AND (ld.application_name Like '$val' OR ld.appno like '".$val."' OR ld.grievance_status Like '$val' OR ld.remarks Like '$val')".tablesort_sql($header); 

	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 
 }else{
	 
	     $query="SELECT *  FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5'  AND wdetail.level = wt.level AND wt.status = 0 and ld.createdby='".$uid."'".tablesort_sql($header);
	   
      /* echo $query="SELECT *  FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5' AND wt.uid='$uid' AND wdetail.level = wt.level AND wt.status = 0".tablesort_sql($header);exit;*/

 }
global $base_url;
$action = $base_url.'/dsje/listgrievance/view';
 
 $output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjegrievance', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','dsje/listgrievance/view');
	}
	$addurl = l(getMessage( 'dsjegrievance', 'code01', NULL),"node/add/grievance");
	$output .='</td><td colspan="3" class="tblHeaderRight"></td></tr>';
	
   	$lising = getMessage( 'dsjegrievance', 'code02', NULL);
		
	 $output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight"><input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';
 
	$result =pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($rs=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","node/$rs->nid/edit",array('attributes'=>array('id'=>'edit-state')));
		$viewurl = l("View","node/$rs->nid",array('attributes'=>array('id'=>'edit-state')));
		$deleteurl = l("Delete","node/$rs->nid/delete",array('attributes'=>array('id'=>'edit-state')));
		//$close=l("Close","dsje/del/grievance/$rs->nid/$rs->application_name",array('attributes'=>array('id'=>'edit-state')))
		
		if($row->grievance_status=='Pending'){
		  $close = l("Pending","dsje/del/grievance/$rs->nid/$rs->application_name");
		}else{
		  $close = l("Close","dsje/del/grievance/$rs->nid/$rs->application_name");
		}
		if($rs->grievance_status=='Pending'){
		       $st='Pending';
		    }else{
			   $st ='Close';
			}
		
		
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => $rs->appno),
			array('data' => $rs->application_name),
			
			
			
			array('data' => $st),
			//array('data' => $viewurl." | ".$editurl." | ".$deleteurl),
array('data' => $viewurl),
		);
	}
	 
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	
	$output .= theme('pager', NULL, $limit,0 );
	
	return $output;
}
}




function grievance_list(){

    global $user;
	global $base_url;
	global $xpathObj;
	$limit = (int)getMessage( 'dsjegrievance', 'code04', NULL);
  
 $header = array(
		array('data' => t('S. No.')),
		array('data' => t('Application No.'), 'field' => 'tbl_grievance.vid', 'sort' => 'asc'),
	     //array('data' => t('Office'), 'field' => 'tbl_corporations.corporation_name', 'sort' => 'asc'),
		  array('data' => t('Applicant Name'), 'field' => 'tbl_grievance.application_name', 'sort' => 'asc'),
		  array('data' => t('Remarks/Action Taken') , 'field' => 'tbl_grievance.remarks', 'sort' => 'asc'),
		  array('data' => t('Status'), 'field' => 'tbl_grievance.remarks', 'sort' => 'asc'),
       array('data' => t('Action')),
		
	);
	
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List of Grievances', 'dsje/listgrievance'.$array[2].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
 if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	
	$query = "SELECT node.nid,tbl_grievance.application_name,tbl_grievance.appno,tbl_corporations.corporation_name, tbl_grievance.office,tbl_grievance.grievance_status,tbl_grievance.remarks FROM node
	 INNER JOIN tbl_grievance ON (node.nid=tbl_grievance.nid) INNER JOIN tbl_corporations ON (tbl_grievance.office=tbl_corporations.corporation_id) where UPPER(tbl_grievance.application_name) LIKE '".$val."' OR UPPER(tbl_grievance.appno) LIKE '".$val."' OR UPPER(tbl_grievance.grievance_status) LIKE '".$val."'".tablesort_sql($header);

	$sqlcount = "SELECT COUNT(*) AS count FROM node
	 INNER JOIN tbl_grievance ON (node.nid=tbl_grievance.nid) INNER JOIN tbl_corporations ON (tbl_grievance.office=tbl_corporations.corporation_id) where UPPER(tbl_grievance.application_name) LIKE '".$val."' OR UPPER(tbl_grievance.appno) LIKE '".$val."' OR UPPER(tbl_grievance.grievance_status) LIKE '".$val."'".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 
 }else{
    $query = "SELECT node.nid,tbl_grievance.application_name,tbl_grievance.appno,tbl_corporations.corporation_name, tbl_grievance.office,tbl_grievance.grievance_status,tbl_grievance.remarks FROM node
	 INNER JOIN tbl_grievance ON (node.nid=tbl_grievance.nid) INNER JOIN tbl_corporations ON (tbl_grievance.office=tbl_corporations.corporation_id)  ".tablesort_sql($header);
 }
 
global $base_url;
$action = $base_url.'/dsje/listgrievance';
 
 $output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjegrievance', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','dsje/listgrievance');
	}
	$addurl = l(getMessage( 'dsjegrievance', 'code01', NULL),"node/add/grievance");
	$output .='</td><td colspan="3" class="tblHeaderRight"></td></tr>';
	 
   	$lising = getMessage( 'dsjegrievance', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight"><input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';
 
	$result =pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($rs=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","node/$rs->nid/edit");
		$viewurl = l("View","node/$rs->nid");
		$deleteurl = l("Delete","node/$rs->nid/delete");
		//$close=l("Close","dsje/del/grievance/$rs->nid/$rs->application_name",array('attributes'=>array('id'=>'edit-state')))
		
		if($rs->grievance_status  != 'Close'){
	
		
		$editurl = l("Edit","node/$rs->nid/edit");
		$viewurl = l("View","node/$rs->nid");
		$deleteurl = l("Delete","node/$rs->nid/delete");
		$close=l("Close","dsje/close/grievance/$rs->nid");
		$action = $viewurl." | ".$close;
		}
		
		else{
		
		$viewurl = l("View","node/$rs->nid");
		$action = $viewurl;
		}
		
		if($rs->grievance_status=='Pending'){
		       $st='Pending';
		    }else{
			   $st ='Close';
			}
		
		
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => $rs->appno),
			array('data' => $rs->application_name),
			array('data' => $rs->remarks),
			
			array('data' => $st),
			//array('data' => $viewurl." | ".$editurl." | ".$deleteurl),
array('data' =>	$action),
		);
	}
	 
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	
	$output .= theme('pager', NULL, $limit,0 );
	
	return $output;
}


function grievance_form(&$node) {

global $user;
	$uid = $user->uid;
	
	//print_r($user);exit;
	
	
	//$rid = getRole($uid);
	//print_r($rid);exit;
	
	

    $breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
	 $breadcrumb[] = l('List Of Grievances', 'dsje/listgrievance/view');
   
    if($array[2] == '' ) {
     $breadcrumb[] = l('Add Grievance', 'dsje/listgrievance/view'.$array[2].'');
	 }  
	 
     drupal_set_breadcrumb($breadcrumb);
	 
	$type = node_get_types('type', $node);
	
$sqlrole = "select * from users_roles where uid='".$uid."'";
$res = db_query($sqlrole);
$rs = db_fetch_object($res);

   //return $rs->rid;
   
   
 //echo "select * from tbl_joinings where program_uid = '".$uid."'"exit;  	
	
//echo "select * from users left join tbl_joinings on (tbl_joinings.program_uid = users.uid) left join tbl_guestuser on (tbl_guestuser.username = users.name)    where users.uid = '".$uid."'";

 $df=db_query("select * from users left join tbl_joinings on (tbl_joinings.program_uid = users.uid)  where users.uid = '".$uid."'");
$Ty=db_fetch_object($df);


 $sqlDepartmentsquery= "SELECT lookupType_id FROM tbl_lookuptypes WHERE lookupType_id='19'";

$sqlDepartments= db_query($sqlDepartmentsquery);
$rsDepartments=db_fetch_object($sqlDepartments);
$sqlDepartmentslookquery = "SELECT * FROM tbl_lookups WHERE status=1 AND lookupType_id= '".$rsDepartments->lookupType_id."' ORDER BY lookup_name ASC";

$resDepartmentslookquery= db_query($sqlDepartmentslookquery);
$Departmentslookquery['']= '--Select--';
if($resDepartmentslookquery){

while($rssender1 = db_fetch_object($resDepartmentslookquery)){

$Departmentslookquery[$rssender1->lookup_id] = ucwords($rssender1->lookup_name);

}

}

$sqlApplicantsquery= "SELECT lookupType_id FROM tbl_lookuptypes WHERE lookupType_id='40'";

$sqlsqlApplicantsquery= db_query($sqlApplicantsquery);
$rsApplicantsquery=db_fetch_object($sqlsqlApplicantsquery);
$sqlApplicantsquerylookquery = "SELECT * FROM tbl_lookups WHERE status=1 AND lookupType_id= '".$rsApplicantsquery->lookupType_id."' ORDER BY lookup_name ASC";

$resApplicantsquerylookquery= db_query($sqlApplicantsquerylookquery);
$Applicantsquerylookquery['']= '--Select--';
if($resDepartmentslookquery){

while($rssender2 = db_fetch_object($resApplicantsquerylookquery)){

$Applicantsquerylookquery[$rssender2->lookup_id] = ucwords($rssender2->lookup_name);

}

}



   
  if(is_numeric(arg(1))){

	  $result = db_query("SELECT * from tbl_grievance WHERE nid =".arg(1));
	$row =  db_fetch_object($result);
  
  }


  

 
	

 $form['section'] = array (
							 '#type' => 'select',
							 '#title' => t('Section'),
							 '#required' => TRUE,
							 '#default_value' => '',
							 '#options' =>$Departmentslookquery,
							 
							 );
					
	

$applicaint= "SELECT lookupType_id FROM tbl_lookuptypes WHERE lookupType_id='32'";

$ttt= db_query($applicaint);
$rstt=db_fetch_object($ttt);
$sqlsenderr = "SELECT * FROM tbl_lookups WHERE status=1 AND lookupType_id= '".$rstt->lookupType_id."' ORDER BY lookup_name ASC";

$ressenderr= db_query($sqlsenderr);
$senderarrayy['']= '--Select--';
if($ressenderr){

while($rssenderr = db_fetch_object($ressenderr)){

$senderarrayy[$rssenderr->lookup_id] = ucwords($rssenderr->lookup_name);

}

}
   	
	
							 
  $form['application_type'] = array (
							 '#type' => 'select',
							 '#title' => t('Application Type'),
							 '#required' => TRUE,
							 '#default_value' => $row->application_type,
							 '#options' =>$senderarrayy,
							 
							 );

   /* $sqlcountry = "select * from tbl_dsjestate WHERE status='1' ORDER BY state_name";
	$rescountry =db_query($sqlcountry);
	if($rescountry){
      $countryarray[''] = '--Select--'; 
	  while($rscountry = db_fetch_object($rescountry)){
	    $countryarray[$rscountry->state_id] = ucfirst($rscountry->state_name);
	  }
	}
	$form['state_id'] = array(
		'#type' => 'select',
		'#title' => t('State'),
		'#required' => TRUE,
		'#default_value' => '',
		'#options' => $countryarray,
		'#ahah' => array(
					  'path' => 'rec/district',
					  'method' => 'replace',
					  'effect' => 'slide',
					  'wrapper' =>'zone',
					  ),
	);
	
	
	
    $zonearray[''] = '--Select--';
	$form['district_id'] = array(
		'#type' => 'select',
		'#title' => t('District'),
		'#required' => TRUE,
		'#default_value' => '',
		'#options' =>$zonearray,
		'#ahah' => array(
					  'path' => 'rec/tehsil',
					  'method' => 'replace',
					  'effect' => 'slide',
					  'wrapper' =>'state',
					  ), 
	);
    
    $statearray[''] = '--Select--';
	$form['tehsil_id'] = array(
			'#type' => 'select',
			'#title' => t('Tehsil'),
			'#required' => TRUE,
			'#default_value' => '',
			'#options' => $statearray,
		);*/
		
		
   $sqlcorporation = "select * from tbl_corporations where status = 1 order by corporation_name asc";
   $rescorporation = db_query($sqlcorporation);
   $corporation = array('' => t('--Select--'));
   while($rscorporation = db_fetch_object($rescorporation)){
     $corporation[$rscorporation->corporation_id] = ucwords($rscorporation->corporation_name);
   }
						   
	 $form['office'] = array(
						   '#type' => 'select',
						   '#title' => t('Office'),
						   '#required' => TRUE,
						    '#default_value' =>'',
						   '#options'  => $corporation,
						   );
						   
		/*$form['datecurrent'] = array(
	  '#type' =>'date_popup',
	  '#date_format' => 'd-m-Y',
	  '#title' =>'Date',
	  '#required' => false,
	  '#default_value' => $node->datecurrent,	
	);*/
						   				   
	 /* $form['application_detail'] = array(
						   '#type' => 'textarea',
						   '#title' => t('Application details'),
						   '#required' => False,
						   '#size' => '30',
						   '#default_value' => $node->application_detail,
						   );*/
						   
		
		   $form['application_name'] = array(
								 '#type' => 'textfield',
								 '#title' => t('Applicant Name'),
								 '#required' => False,
								 '#size' => '30',
								 '#default_value' => $Ty->employee_name,
								  '#attributes' => array('readonly' => 'readonly'),
								 );
		 
		
		 
		 
		 $kk= "SELECT lookupType_id FROM tbl_lookuptypes WHERE lookupType_id='8'";

$tt= db_query($kk);
$rst=db_fetch_object($tt);
$sqlsender = "SELECT * FROM tbl_lookups WHERE status=1 AND lookupType_id= '".$rst->lookupType_id."' ORDER BY lookup_name ASC";

$ressender= db_query($sqlsender);
$senderarray['']= '--Select--';
if($ressender){

while($rssender = db_fetch_object($ressender)){

$senderarray[$rssender->lookup_id] = ucwords($rssender->lookup_name);

}

}
		 
     $form['application_category'] = array(
								 '#type' => 'select',
								 '#title' => t('Applicant Category'),
								 '#required' => TRUE,
								 '#options' => $senderarray,
								 );
								 
		
		
								 
		//$sdf=$Ty->add_line1.$Ty->add_line2.gettehsil($Ty->tehsil_id).getdistrict($Ty->district_id).getstate($Ty->state_id);			 
								 
								 
      $form['permanent_address'] = array(
						   '#type' => 'textarea',
						   '#title' => t('Address'),
						   '#required' => TRUE,
						   '#size' => '30',
						   '#maxlength'=>100,
						   '#default_value' => t($Ty->add_line1.' '.$Ty->add_line2.' '.gettehsil($Ty->tehsil_id).' '.getdistrict($Ty->district_id).' '.getstate($Ty->state_id)),
						   '#attributes' => array('onkeypress' => 'return textonlywithdotnemax(event,"edit-permanent-address",100)','readonly' => 'readonly'),
						   ); 
	  $form['correspondence_address'] = array(
						   '#type' => 'textarea',
						   '#title' => t('Correspondence Address'),
						   '#required' => False,
						   '#size' => '30',
						   '#maxlength'=>100,
						   '#default_value' => $row->correspondence_address,
						   '#attributes' => array('onkeypress' => 'return textonlywithdotnemax(event,"edit-correspondence-address",100)'),
						   ); 
       $form['telephone_number'] = array(
						   '#type' => 'textfield',
						   '#title' => t('Telephone No.'),
						   '#required' => False,
						   '#size' => '30',
						   '#maxlength'=>15,
	                       '#minlenght'=>10,	
	                       '#attributes' => array('onkeypress' => 'return fononlyn12(event)'),
						   '#default_value' => $Ty->phone,
						   );
	    $form['mobile_number'] = array(
						   '#type' => 'textfield',
						   '#title' => t('Mobile No.'),
						   '#required' => False,
						   '#size' => '30',
						   '#default_value' => $Ty->mobile,
						   '#maxlength'=>15,
	                       '#minlenght'=>10,	
	                       '#attributes' => array('onkeypress' => 'return fononlyn12(event)'),
						  
						   );
						   
						   
						 
	   $form['email_address'] = array(
						   '#type' => 'textfield',
						   '#title' => t('E-mail Address'),
						   '#required' => FALSE,
						   '#size' => '30',
						   '#maxlength'=>40,
						   '#default_value' => $Ty->mail,
						   '#attributes' => array('readonly' => 'readonly'),
						   );
	  				 
								 				 
		$form['cancel'] = array(
        '#type' => "markup",
        '#value' => l(t('Back'), 'dsje/listgrievance/view'),
);   
		


 
   return $form;
}


function grievance_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	//echo '<pre>';
	//print_r($form);
	
	if($form_id == 'node_delete_confirm'){
	//print_r($form);
	
	}
	
	if($form_id =='grievance_node_form'){
	
	    $form['author']['#type'] = 'value';
    $form['author']['name'] = array('#type'=>'value', '#value'=>$form[
'author']['name']['#default_value']);
    $form['author']['date'] = array('#type'=>'value', '#value'=>$form[
'author']['date']['#default_value']);
	 $form['revision_information']['#type'] = hidden;
	 $form['options']['#type'] = hidden;
	 $form['buttons']['preview']['#type'] = hidden;
	 //$form['buttons']['delete']['#type'] = hidden;
	 $form['menu']['#type'] = hidden;
	 $form['comment_settings']['#type'] = hidden;
	 $form['title']['#required'] = FALSE;
	 $form['title']['#type'] = hidden;
	 $form['author_information']['#type'] = hidden;
	 $form['attachments']['#type'] = hidden;
	  $form['path']['#type'] = hidden;
	 
	
	
	}
	
 }


function grievance_validate($form, &$form_states) {

$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
	 $breadcrumb[] = l('List Grievance', 'dsje/listgrievance/view');
   
    if($array[2] == '' ) {
     $breadcrumb[] = l('Add Grievance', 'dsje/listgrievance/view'.$array[2].'');
	 }  
	 
     drupal_set_breadcrumb($breadcrumb);


$office=$form->office;
//$application_detail=$form->application_detail;
$application_name=$form->application_name;

alphanumeric('office',$office,'office');
alphanumeric('application_detail',$application_detail,'application_detail');
alphanumeric('application_name',$application_name,'application_name');
fononlyn('telephone_number',$form->telephone_number,'Telephone No.');
phonelength($form->telephone_number,'telephone_number');
//textonlywithdotne('permanent_address',$form->permanent_address,'Permanent Address.'); 
//textonlywithdotne('correspondence_address',$form->correspondence_address,'Correspondence Address.'); 
fononlyn('mobile_number',$form->mobile_number,'Mobile No.');
mobilelength($form->mobile_number,'mobile_number');
$email = $form->email_address;
if($email !=''){
	  $pattern = "^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$";
     
       if (eregi($pattern, $email)){
          return true;
       }
       else {
          form_set_error('email', t('You must enter valid Email Id.'));
       }    
	}
	
	if($form->office==0)
   { 
   form_set_error('office','Please select office.');
   
   }
   
   
  

  
}


function grievance_view($node, $teaser = FALSE, $page = FALSE) {


	$array = explode('/',$_GET['q']);
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Grievances', 'dsje/listgrievance/view');

     $breadcrumb[] = l('View Grievance', 'node/'.$array[1].'');
 
  drupal_set_breadcrumb($breadcrumb);


	$node = node_prepare($node, $teaser);
	
	
	$viewdistrict="select district_name from tbl_district where district_id='$node->district_id'";
	$sqlquery=db_query($viewdistrict);
	$sqldbfetch=db_fetch_object($sqlquery);
	
	
	$viewstate="select state_name from tbl_dsjestate where state_id='$node->state_id'";
	$sqlquery=db_query($viewstate);
	$sqldbfetchstate=db_fetch_object($sqlquery);
	
	$viewtehsil="select tehsil_name from tbl_tehsil where tehsil_id='$node->tehsil_id'";
	$sqlquery=db_query($viewtehsil);
	$sqldbfetchtehsil=db_fetch_object($sqlquery);
	
	$corporation="select corporation_name from tbl_corporations where corporation_id='$node->office'";
	$sqlquery=db_query($corporation);
	$sqldbfetchcorporation=db_fetch_object($sqlquery);
	
	
	
	$appno = $node->appno;
    $section = getLookupName($node->section);
   	$application_type = getLookupName($node->application_type);
   $office = $sqldbfetchcorporation->corporation_name;
	
	$datecurrent= date('d-m-Y',strtotime($node->datecurrent));
    $application_name = $node->application_name;
	$application_detail =$node->application_detail;
    $application_category = getLookupName($node->application_category);
    $permanent_address = ucwords($node->permanent_address);
    $correspondence_address = ucwords($node->correspondence_address);
	$state_id =$sqldbfetchstate->state_name;
	$district_id =$sqldbfetch->district_name;
	$tehsil_id =$sqldbfetchtehsil->tehsil_name;
	$telephone_number1 = $node->telephone_number;
	if($telephone_number1){
		
	$telephone_number = $node->telephone_number;	
	}
	else{
	$telephone_number = 'N/A';		
	}
    $mobile_number = $node->mobile_number;
    $email_address = $node->email_address;
	$grievance_status = $node->grievance_status;
	$remarks = $node->remarks;
  // print_r($node);exit;
    
		
	$node->content['grievance_info'] = array(
											 '#value' => theme('grievance_info',$appno,$section,$application_type,$office,$datecurrent,$application_name, $application_detail,$application_category, $permanent_address, $correspondence_address,$state_id,$district_id,$tehsil_id,$telephone_number, $mobile_number,$email_address,$grievance_status,$remarks,$node),
											 '#weight' => 1,
											 );
	return $node;
}


function grievance_theme() {
	
	return array(
				 'grievance_info' => array(
										   'template' => 'grievance_view',
										   'arguments' => array(
		                                                       	
																'appno' => NULL,	
																'section' => NULL,
																'application_type' => NULL,
																'office' => NULL,
																'datecurrent' => NULL,
																'application_name' => NULL,
																'application_detail' => NULL,
																'application_category' => NULL,
																'permanent_address' => NULL,
																'correspondence_address' => NULL,
																'state_id' => NULL,
																'district_id' => NULL,
																'tehsil_id' => NULL,
																'telephone_number' => NULL,
																'mobile_number' => NULL,
																'email_address' => NULL,
																'grievance_status' => NULL,
																'remarks' => NULL,
																'node' => NULL,
																),
										   ),
				 'grievance_node_form' => array(
        'arguments' => array('form' => NULL),
        'template' => 'grievance_node_form',
    ),
	
	
	 'grievance_misreport' => array(
        'arguments' => array('form' => NULL),
        'template' => 'grievance_misreport',
    ),
				
				'dsje_grievanceclose_form' => array(
        'arguments' => array('form' => NULL),
        'template' => 'dsje_grievanceclose_form',
    ),
				 );
				 			 
}


  
/**
 *hook_insert
 */

 function grievance_insert($node){
   
   global $user;
   $uid = $user->uid;
	//$vid = $node->vid;
	
	//echo "select * from users left join tbl_joinings on (tbl_joinings.program_uid = users.uid)  where users.uid = '".$uid."'";exit; 
	
	$df=db_query("select * from users left join tbl_joinings on (tbl_joinings.program_uid = users.uid)  where users.uid = '".$uid."'");
$Ty=db_fetch_object($df);

		 $district_id =$Ty->district_id;
		
	
   
	$vid = $node->vid;
	
	$appno = DsjeGREV.$node->vid;
	
	
	
    $nid = $node->nid;
	$section =ucwords($node->section);
    $application_type = $node->application_type;
	$office = $node->office;
	$datecurrent= date(Y-m-d);
    $application_detail = $node->application_detail;
	$application_name = ucwords($node->application_name);
	$application_category = $node->application_category;
    $permanent_address = $node->permanent_address;
    $correspondence_address1 =$node->correspondence_address;
	if($correspondence_address1)
	{
	$correspondence_address=	$node->mobile_number;
		
	}else{
		$correspondence_address = "N/A";
	}
	
	$state_id =$node->state_id;
	//$district_id =$node->district_id;
	$tehsil_id =$node->tehsil_id;
    $telephone_number = $node->telephone_number;
    $mobile_number1 = $node->mobile_number;
	$mobile_numbersms = '91'.$node->mobile_number;
	if($mobile_number1)
	{
	$mobile_number=	$node->mobile_number;
		
	}else{
		$mobile_number = "N/A";
	}
    $email_address = $node->email_address;
	$grievance_status = 'Pending';
    
	$time=time();
	
	$workflow_id=5;
	
	/*echo "insert into tbl_grievance (vid,nid,appno,section,application_type,office,datecurrent,application_detail,application_name,application_category,permanent_address,correspondence_address,state_id,district_id,tehsil_id,telephone_number,mobile_number,email_address,grievance_status) VALUES('".$vid."','".$nid."','".$appno."','".$section."','".$application_type."','".$office."',NOW(),'".$application_detail."','".$application_name."','".$application_category."','".$permanent_address."','".$correspondence_address."','".$state_id."','".$district_id."','".$tehsil_id."','".$telephone_number."','".$mobile_number."','".$email_address."','".$grievance_status."')";exit;*/
	
	db_query("insert into tbl_grievance (vid,nid,appno,section,application_type,office,datecurrent,application_detail,application_name,application_category,permanent_address,correspondence_address,state_id,district_id,tehsil_id,telephone_number,mobile_number,email_address,grievance_status,createdby) VALUES('".$vid."','".$nid."','".$appno."','".$section."','".$application_type."','".$office."',NOW(),'".$application_detail."','".$application_name."','".$application_category."','".$permanent_address."','".$correspondence_address."','".$state_id."','".$district_id."','".$tehsil_id."','".$telephone_number."','".$mobile_number."','".$email_address."','".$grievance_status."','".$uid."')");
	
	//insert docket
	
	 $officeid=getCorporationBranch($uid);
	
	$sxd=db_query("insert into tbl_workflow_docket(workflow_id,time,status) values('".$workflow_id."','".$time."','".$rti_management_status."')"); 
	
	
	
	 //$xcasddfsd=db_last_insert_id('tbl_grievance','nid');
	
	$d=db_last_insert_id('tbl_workflow_docket','doc_id');
	
	//echo "update tbl_grievance set doc_id = '".$d."' where nid ='".$nid."'";exit;
	
	$sd=db_query("update tbl_grievance set doc_id = '".$d."' where nid = '".$nid."'");
	 
	 
	
	
	
	global $user;
	$uid = $user->uid;
	
	//echo "select * from users_roles where uid='".$uid."'";exit;
	
	 $sqlrole = "select * from users_roles where uid='".$uid."'";
$res = db_query($sqlrole);
$rs = db_fetch_object($res);
 $as = $rs->rid;	
	
	 $dq="select * from tbl_workflow_details where role='$as'";
	 $sql=db_query($dq);
	 $sx=db_fetch_object($sql);
	
	 $level=$sx->level;
	 
	 $status=0;
	 $doc_id=db_last_insert_id('tbl_workflow_docket','doc_id');
	 
	global $user;
	$uid = $user->uid;
	
	$task_date=date("Y-m-d");
	 
	//createTask($level,$doc_id,'','',$uid,'','');

	
	
	//db_query("insert into tbl_workflow_task(level,status,doc_id,uid,task_date) values('1','".$status."','".$doc_id."','".$uid."','".$task_date."')");
	
	db_query("insert into tbl_workflow_task(level,status,doc_id,task_date) values('1','".$status."','".$doc_id."','".$task_date."')");
	
	$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 	

createMail('grievance', $email_address,'',$parameter);

//echo "select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.uid='".$uid."'";exit;

$emaisql=db_query("select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.rid='38'");
while($emaisqlquery=db_fetch_object($emaisql))
{
$toemail=$emaisqlquery->mail;	
	
$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 	


createMail('grievancpio', $toemail,'',$parameter);
}

$emaisql1=db_query("select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.rid='5'");
while($emaisqlquery1=db_fetch_object($emaisql1))
{
$toemail1=$emaisqlquery1->mail;	
	
$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 	


createMail('grievancehod', $toemail1,'',$parameter);
}

$emaisql2=db_query("select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.rid='19'");
while($emaisqlquery2=db_fetch_object($emaisql2))
{
$toemail2=$emaisqlquery2->mail;	
	
$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 	


createMail('grievancegm', $toemail2,'',$parameter);
}

$emaisql3=db_query("select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.rid='6'");
while($emaisqlquery3=db_fetch_object($emaisql3))
{
$toemail3=$emaisqlquery3->mail;	
	
$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 


createMail('grievancemd', $toemail3,'',$parameter);
}


 $message = getMessage('dsjegrievance', 'code10', array("0"=>$appno));
			drupal_set_message($message);			
drupal_goto("dsje/listgrievance/view");	

 }
  

 function grievance_load($node) {
	$result = db_query("SELECT * from tbl_grievance WHERE vid = $node->vid");
	return db_fetch_object($result);
}


/**
 *hook_update
 */

 function grievance_update($node){
    
    

	$vid = $node->vid;
    $nid = $node->nid;
	$section =$node->section;
    $application_type = $node->application_type;
	$district_id = $node->district_id;
    $office = $node->office;
	$datecurrent= $node->datecurrent;
    $application_detail = $node->application_detail;
    $application_category = $node->application_category;
    $permanent_address = $node->permanent_address;
    $correspondence_address =$node->correspondence_address;
    $telephone_number = $node->telephone_number;
    $mobile_number = $node->mobile_number;
    $email_address = $node->email_address;
    
	
	
	db_query("update tbl_grievance set section='".$section."',application_type='".$application_type."',,application_type='".$application_type."',district_id ='".$district_id."',office ='".$office."',datecurrent ='".$datecurrent."',application_detail='".$application_detail."',application_category='".$application_category."',permanent_address='".$permanent_address."',correspondence_address='".$correspondence_address."',telephone_number='".$telephone_number."',mobile_number='".$mobile_number."',email_address='".$email_address."' where vid='".$vid."'");

 }


function grievance_cron(){
 
 


$sqlque=db_query("select * from tbl_grievance inner join tbl_workflow_task on(tbl_workflow_task.doc_id=tbl_grievance.doc_id) where tbl_grievance.grievance_status='Close'");
$sx=db_fetch_object($sqlque);
$sdf=$sx->nid;
if(!$sdf)

{

/*$result=db_query("SELECT *  FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_grievance ld, tbl_workflow_details wdetail WHERE wt.doc_id = wd.doc_id AND ld.doc_id = wd.doc_id AND wd.workflow_id = w.workflow_id AND w.workflow_id = wdetail.workflow_id AND w.workflow_id = '5' AND wdetail.level = wt.level AND wt.status = 0")

$result=db_query("SELECT tbl_workflow_task.doc_id,tbl_workflow_details.hours
FROM tbl_workflow_task
INNER JOIN tbl_workflow_docket ON ( tbl_workflow_docket.doc_id = tbl_workflow_task.doc_id )
INNER JOIN tbl_workflow_details ON ( tbl_workflow_details.workflow_id = tbl_workflow_docket.workflow_id )
INNER JOIN tbl_grievance ON ( tbl_grievance.doc_id = tbl_workflow_task.doc_id )
WHERE tbl_workflow_task.status =0");*/


/*$result = db_query("SELECT tbl_grievance.doc_id,tbl_workflow_task.status,tbl_workflow_task.task_date from tbl_grievance inner join tbl_workflow_task on (tbl_workflow_task.doc_id=tbl_grievance.doc_id) inner join tbl_workflow_docket on(tbl_workflow_docket.doc_id=tbl_workflow_task.doc_id)   where tbl_workflow_task.status=0");*/




$emaisql=db_query("select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.rid='5'");

while($sqlquery=db_fetch_object($emaisql))

{

$toemail_address =$sqlquery->mail;
$application_name =$sqlquery->application_name;

$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 	

createMail('grievance', $toemail_address,'',$parameter);

global $user;
	$uid = $user->uid;
	
	//echo "select * from users_roles where uid='".$uid."'";exit;
	
	 $sqlrole = "select * from users_roles where uid='".$uid."'";
$res = db_query($sqlrole);
$rs = db_fetch_object($res);
 $as = $rs->rid;	
	
	 $dq="select * from tbl_workflow_details where role='$as'";
	$sql=db_query($dq);
	$sx=db_fetch_object($sql);
	
	 $level=$sx->level;
	 
	 $status=0;
	 $doc_id=db_last_insert_id('tbl_workflow_docket','doc_id');
	 
	global $user;
	$uid = $user->uid;
	
	$task_date=date("Y-m-d");
	 
	db_query("insert into tbl_workflow_task(level,status,doc_id,uid,task_date) values('".$level."','".$status."','".$doc_id."','".$uid."','".$task_date."')");




}





$sqlro=db_query("select * from role where rid = '19'");

 $rowfetch=$sqlro->rid;
if($rowfetch == 19)
{

$emaisql=db_query("select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.rid='19'");

while($sqlquery=db_fetch_object($emaisql))

{

$toemail_address =$sqlquery->mail;
$application_name =$sqlquery->application_name;

$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 	

createMail('grievance', $toemail_address,'',$parameter);






}

global $user;
	$uid = $user->uid;
	
	//echo "select * from users_roles where uid='".$uid."'";exit;
	
	 $sqlrole = "select * from users_roles where uid='".$uid."'";
$res = db_query($sqlrole);
$rs = db_fetch_object($res);
 $as = $rs->rid;	
	
	 $dq="select * from tbl_workflow_details where role='$as'";
	$sql=db_query($dq);
	$sx=db_fetch_object($sql);
	
	 $level=$sx->level;
	 
	 $status=0;
	 $doc_id=db_last_insert_id('tbl_workflow_docket','doc_id');
	 
	global $user;
	$uid = $user->uid;
	
	$task_date=date("Y-m-d");
	
	
	createTask($level,$doc_id,$uid,$assignedbyuid = '',$Is_escalation = '',$writ_level = '');


	 
	db_query("insert into tbl_workflow_task(level,status,doc_id,uid,task_date) values('".$level."','".$status."','".$doc_id."','".$uid."','".$task_date."')");

}

$sqlro=db_query("select * from role where rid = '6'");

 $rowfetch=$sqlro->rid;
if($rowfetch == 6)
{

$emaisql=db_query("select * from users inner join users_roles on(users.uid=users_roles.uid) where users_roles.rid='6'");

while($sqlquery=db_fetch_object($emaisql))

{

$toemail_address =$sqlquery->mail;
$application_name =$sqlquery->application_name;

$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>$application_name,1=>$appno,2=>$datecurrent)); 	

createMail('grievance', $toemail_address,'',$parameter);





}

global $user;
	$uid = $user->uid;
	
	//echo "select * from users_roles where uid='".$uid."'";exit;
	
	 $sqlrole = "select * from users_roles where uid='".$uid."'";
$res = db_query($sqlrole);
$rs = db_fetch_object($res);
 $as = $rs->rid;	
	
	 $dq="select * from tbl_workflow_details where role='$as'";
	$sql=db_query($dq);
	$sx=db_fetch_object($sql);
	
	 $level=$sx->level;
	 
	 $status=0;
	 $doc_id=db_last_insert_id('tbl_workflow_docket','doc_id');
	 
	global $user;
	$uid = $user->uid;
	
	$task_date=date("Y-m-d");
	 
	db_query("insert into tbl_workflow_task(level,status,doc_id,uid,task_date) values('".$level."','".$status."','".$doc_id."','".$uid."','".$task_date."')");


}

		
  } 
 }
 
 

 
 
function grievance_mail($key, &$message, $params) {
  if ($key == 'notification') {
    $message['subject'] = $params['subject'];
    $message['body']    = $params['body'];
    $message['headers']['Content-Transfer-Encoding'] = '8bit';
    $message['headers']['Content-Type'] = "text/html; charset='utf-8';";
  }
} 






 function grievance_close($id,$sno){
	$grievance_id =  $id;
	
		
		db_query("UPDATE {tbl_grievance} SET grievance_status= 'Close' WHERE nid ='".$grievance_id."'");
		
		$message = getMessage('dsjegrievance', 'code07', array("0"=>$sno));
		drupal_set_message($message);
  
	drupal_goto("dsje/listgrievance/view");
 }
 
function dsje_addclose($id){

 return drupal_get_form('dsje_grievanceclose_form',$id);
}
 


 
function dsje_grievanceclose_form($form1,$id)
{

//print_r($form);exit;

 $breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
	 $breadcrumb[] = l('List Grievance', 'dsje/listgrievance');
   
    if($array[2] == '' ) {
     $breadcrumb[] = l('Add Remarks', 'dsje/close/grievance'.$array[2].'');
	 }  
	 
     drupal_set_breadcrumb($breadcrumb);

$select1=db_query("select * from tbl_grievance where nid='$id'");
	$fetch1=db_fetch_object($select1);

$form['nid'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$id,
	
	);

$form['remarks'] = array(
	    '#type' =>'textarea',
		'#title' => t('Remarks/Action Taken'),
		'#required' => True,
		'#default_value' =>'',
		'#cols' => 30,
        '#rows' => 5,    
		'#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	);
	
	$select=db_query("select * from tbl_grievance where nid='$id'");
	$fetch=db_fetch_object($select);
	
	
/*$form['grievance_status'] = array(

     '#type' =>'select',
	 '#title' => t(Status),
	 '#required' => true,
	 '#default_value' =>$fetch->grievance_status,
	 '#options' => array('' => 'select Staus','Pending' => 'Pending','Close' => 'Close'),
	 
	 );*/
	 
	 $form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Close'),
	);
	
	$form['cancel'] = array(
        '#type' => "markup",
        '#value' => l(t('Back'), 'dsje/listgrievance/view'),
);   
	
	return $form;


}
  
 
function dsje_grievanceclose_form_submit($form, &$form_state)
{


    global $user;
	$values = $form_state['values'];
	
	$remarks=$values['remarks'];
	$grievance_status= 'Close';
    $createdby = $user->uid;
	$createdon = time();
	
	 $sqlname="select * from tbl_grievance where nid ='".$values['nid']."'";
	 
	 $assql=db_query($sqlname);
	 $sqll=db_fetch_object($assql);
	 $application_name=$sqll->application_name;
	  $appno=$sqll->appno;
	 
	 $doc=$sqll->doc_id;
	
	//echo $doc_id=db_last_insert_id('tbl_workflow_docket','doc_id');
	//$sql = "INSERT INTO `tbl_grievance` (`remarks` ,`grievance_status` ,`createdby` ,`createdon`) values('".$remarks."','".$grievance_status."','".$createdby."','".$createdon."')";
	//db_query($sql);
	//print_r($values);exit;
	
	//echo "UPDATE {tbl_grievance} SET grievance_status= '".$grievance_status."',remarks= '".$remarks."',createdby='".$createdby."',createdon='".$createdon."' WHERE nid ='".$values['nid']."'";exit;
	
	
	
	 $sql = db_query("UPDATE {tbl_grievance} SET grievance_status= '".$grievance_status."',remarks= '".$remarks."',createdby='".$createdby."',createdon='".$createdon."' WHERE nid ='".$values['nid']."'");
	 
	//echo "UPDATE {tbl_workflow_task} SET status= '1' where doc_id='".$doc."'";exit;
	 
	  $sql1 = db_query("UPDATE {tbl_workflow_task} SET status= '1' where doc_id='$doc'");
	
	 $message = getMessage('dsjegrievance', 'code05', array("0"=>$appno));
	 
	 $sqlmail="select * from tbl_grievance where nid ='".$values['nid']."'";
	 
	 $assql=db_query($sqlmail);
	 $sqll=db_fetch_object($assql);
	 $email_address=$sqll->email_address;
	 $application_name =$sqll->application_name;
	 $grievance_status =$sqll->grievance_status;
	 $date =$sqll->datecurrent;
	 $mobile_numbersms = '91'.($sqll->mobile_number);
    
	$smsmessage = 'Your Grivances has been successfully closed';
	
	
$parameter = '';
//$to = $u->mail;
$parameter = json_encode(array(0=>"$application_name",1=>"$appno",2=>"$date")); 
//$parameter .= json_encode(array(1=>$grievance_status));
	 
	 createMail('grievanceclose', $email_address,'',$parameter);
	 customsendsms($mobile_numbersms,$smsmessage);
	 
	drupal_set_message($message);
drupal_goto('dsje/listgrievance/view');




}




