<?php
function dsje_post_init() {
	//drupal_add_css(drupal_get_path('module', 'dsje_language') .'/dsje_language.css');
	
}


function dsje_post_perm() {
	return array('edit dsje_post','administer dsje_post', 'create dsje_post', 'view dsje_post');
}

function dsje_post_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_post', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_post', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_post', $account);
	}
	
}

function dsje_post_menu() {
	
	
	$items['admin/dsje/listpost'] = array(
										'title' => t('List of post'),
										'description' => 'Allow user to View post',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewpost',
										'access arguments' => array('administer dsje_post'),
													 
									  );
	
	$items['admin/dsje/listpost/addpost'] = array(
										'title' => t('Create post'),
										'description' => 'Allow user to add post',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_post',
										'access arguments' => array('administer dsje_post'),
													 
									  );
   	$items['admin/dsje/listpost/edit/post/%'] = array(
								
										'title' => t('Edit post'),
										'description' => 'Allow user to add post',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addpostedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_post'),
													 
									  );
   $items['admin/dsje/listpost/view/post/%'] = array(
								
										'title' => t('View post'),
										'description' => 'Allow user to add post',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addpostview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_post'),
													 
									  );
     $items['admin/dsje/del/post/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'post_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_post'),
													 
									  );
    $items['admin/dsje/enable/post/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'post_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_post'),
													 
									  );
	return $items;
}


/**
 listing post
 */

function viewpost(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjepost', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('Type of post'), 'field' => 'post_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List post', 'admin/dsje/listpost/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT post_id, post_name, status FROM tbl_posts where UPPER(post_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_posts where UPPER(post_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT post_id, post_name, status FROM tbl_posts ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjepost', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listpost');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjepost', 'code01', NULL),"admin/dsje/listpost/addpost");
   	$lising = getMessage( 'dsjepost', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listpost/edit/post/".$row->post_id,array('attributes'=>array('id'=>'edit-post-id')));
		$viewurl = l("View","admin/dsje/listpost/view/post/".$row->post_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/post/$row->post_id/$row->post_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/post/$row->post_id/$row->post_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->post_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_post(){
 return drupal_get_form('dsje_post_form');
}

function dsje_post_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of post', 'admin/dsje/listpost');
  if($array[3] == 'addpost'){
     $breadcrumb[] = l('Add post', 'admin/dsje/listpost/addpost');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['post_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('post Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listpost'),
);
	return $form;
}

function dsje_post_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $post_name = trim($values['post_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('post_name',$post_name,'post');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_posts` (`post_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$post_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjepost', 'code05', array("0"=>$post_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listpost');
	}
}

function dsje_post_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$post_name = trim($values['post_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('post_name',$post_name,'post');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_posts} where UCASE(post_name)= '".strtoupper($post_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjepost', 'code06', array("0"=>$post_name));
			form_set_error('post_name', $message);
		}
	}	
}

function dsje_addpostedit($post_id){
 return drupal_get_form('dsje_post_form_edit',$post_id);
}

function dsje_post_form_edit(&$form_states,$post_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List post', 'admin/dsje/listpost');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit post', 'admin/dsje/listpost/edit/post/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlpost = "select * from tbl_posts where post_id=$post_id";
	$respost = db_query($sqlpost);
	$rspost = db_fetch_object($respost);
	
	$form['post_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rspost->post_id,
	);
	
	$form['post_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('post Name'),
		'#required' => TRUE,
		'#default_value' =>$rspost->post_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_post_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rspost->post_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rspost->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listpost'),
);
	return $form;
}

function dsje_post_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$post_id = $values['post_id'];
	$post_name = ParseData($values['post_name']);
	$prev_post_name = ParseData($values['prev_post_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('post_name',$post_name,'post');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_posts} where LOWER(post_name)= '".strtolower($post_name)."' GROUP BY post_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_post_name), strtolower($post_name))==0){
			db_query("UPDATE `tbl_posts` set `post_name` = '".$post_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where post_id='".$post_id."'");
			
			$message = getMessage('dsjepost', 'code05', array("0"=>$post_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listpost");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_posts` set `post_name` = '".$post_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where post_id='".$post_id."'");
				
				$message = getMessage('dsjepost', 'code05', array("0"=>$post_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listpost");	
			
			}else{
				db_query("UPDATE `tbl_posts` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where post_id='".$post_id."'");
				
				$message = getMessage('dsjepost', 'code06', array("0"=>$post_name));
				form_set_error('post_name', $message);
			}
		}
	}
}

function dsje_post_theme() {
	
	return array(
				 
		'dsje_post_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_post_form',
                                 ),
        'dsje_post_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_post_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_post_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_post_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_post_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function post_delete($sid, $sno){
  $post_id =  $sid;
  db_query("UPDATE {tbl_posts} SET status=0 WHERE post_id ='".$post_id."'");
  $message = getMessage('dsjepost', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listpost");
 }


  function post_enable($sid, $sno){
    $post_id =  $sid;
    db_query("UPDATE {tbl_posts} SET status=1 WHERE post_id ='".$post_id."'");
  
    $message = getMessage('dsjepost', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listpost");
  }

  function dsje_addpostview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List post', 'admin/dsje/listpost');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View post', 'admin/dsje/listpost/view/post/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_posts where post_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>post Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>post:</td><td>'.ucwords($rs->post_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listpost');
 return $output;
  }
	
	