<?php
function dsje_statusFixedAsset_init() {
	//drupal_add_css(drupal_get_path('module', 'dsje_language') .'/dsje_language.css');
	
}


function dsje_statusFixedAsset_perm() {
	return array('edit dsje_statusFixedAsset','administer dsje_statusFixedAsset', 'create dsje_statusFixedAsset', 'view dsje_statusFixedAsset');
}

function dsje_statusFixedAsset_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_statusFixedAsset', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_statusFixedAsset', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_statusFixedAsset', 'admin');
	}
	
}

function dsje_statusFixedAsset_menu() {
	
	
	$items['admin/dsje/liststatusFixedAsset'] = array(
										'title' => t('List of  Fixed asset status on sale'),
										'description' => 'Allow user to View  Fixed asset status on sale',
										'type' => NORMAL_MENU_ITEM,
										'page callback' => 'viewstatusFixedAsset',
										'access arguments' => array('administer dsje_statusFixedAsset'),
													 
									  );
	
	$items['admin/dsje/liststatusFixedAsset/addstatusFixedAsset'] = array(
										'title' => t('Create  Fixed asset status on sale'),
										'description' => 'Allow user to add  Fixed asset status on sale',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_statusFixedAsset',
										'access arguments' => array('administer dsje_statusFixedAsset'),
													 
									  );
   	$items['admin/dsje/liststatusFixedAsset/edit/statusFixedAsset/%'] = array(
								
										'title' => t('Edit  Fixed asset status on sale'),
										'description' => 'Allow user to add  Fixed asset status on sale',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addstatusFixedAssetedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_statusFixedAsset'),
													 
									  );
   $items['admin/dsje/liststatusFixedAsset/view/statusFixedAsset/%'] = array(
								
										'title' => t('View  Fixed asset status on sale'),
										'description' => 'Allow user to add  Fixed asset status on sale',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addstatusFixedAssetview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_statusFixedAsset'),
													 
									  );
     $items['admin/dsje/del/statusFixedAsset/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'statusFixedAsset_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_statusFixedAsset'),
													 
									  );
    $items['admin/dsje/enable/statusFixedAsset/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'statusFixedAsset_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_statusFixedAsset'),
													 
									  );
	return $items;
}


/**
 listing statusFixedAsset
 */

function viewstatusFixedAsset(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjestatusFixedAsset', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('statusFixedAsset'), 'field' => 'statusFixedAsset_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	
	
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List statusFixedAsset', 'admin/dsje/liststatusFixedAsset/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT statusFixedAsset_id, statusFixedAsset_name, status FROM tbl_statusFixedAssets where UPPER(statusFixedAsset_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_statusFixedAssets where UPPER(statusFixedAsset_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT statusFixedAsset_id, statusFixedAsset_name, status FROM tbl_statusFixedAssets ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjestatusFixedAsset', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/liststatusFixedAsset');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjestatusFixedAsset', 'code01', NULL),"admin/dsje/liststatusFixedAsset/addstatusFixedAsset");
   	$lising = getMessage( 'dsjestatusFixedAsset', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/liststatusFixedAsset/edit/statusFixedAsset/".$row->statusFixedAsset_id,array('attributes'=>array('id'=>'edit-statusFixedAsset-id')));
		$viewurl = l("View","admin/dsje/liststatusFixedAsset/view/statusFixedAsset/".$row->statusFixedAsset_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/statusFixedAsset/$row->statusFixedAsset_id/$row->statusFixedAsset_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/statusFixedAsset/$row->statusFixedAsset_id/$row->statusFixedAsset_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->statusFixedAsset_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_statusFixedAsset(){

 return drupal_get_form('dsje_statusFixedAsset_form');
}

function dsje_statusFixedAsset_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of statusFixedAsset', 'admin/dsje/liststatusFixedAsset');
  if($array[3] == 'addstatusFixedAsset'){
     $breadcrumb[] = l('Add statusFixedAsset', 'admin/dsje/liststatusFixedAsset/addstatusFixedAsset');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['statusFixedAsset_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('statusFixedAsset Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	);*/ 

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/liststatusFixedAsset'),
);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/liststatusFixedAsset'),
);
	return $form;
}

function dsje_statusFixedAsset_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $statusFixedAsset_name = trim($values['statusFixedAsset_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('statusFixedAsset_name',$statusFixedAsset_name,'statusFixedAsset');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_statusFixedAssets` (`statusFixedAsset_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$statusFixedAsset_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage( 'dsjestatusFixedAsset', 'code05', array("0"=>$statusFixedAsset_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/liststatusFixedAsset');
	}
}

function dsje_statusFixedAsset_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$statusFixedAsset_name = trim($values['statusFixedAsset_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('statusFixedAsset_name',$statusFixedAsset_name,'statusFixedAsset');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_statusFixedAssets} where UCASE(statusFixedAsset_name)= '".strtoupper($statusFixedAsset_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage( 'dsjestatusFixedAsset', 'code06', array("0"=>$statusFixedAsset_name));
			form_set_error('statusFixedAsset_name', $message);
		}
	}	
}

function dsje_addstatusFixedAssetedit($statusFixedAsset_id){
 return drupal_get_form('dsje_statusFixedAsset_form_edit',$statusFixedAsset_id);
}

function dsje_statusFixedAsset_form_edit(&$form_states,$statusFixedAsset_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';




 $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List statusFixedAsset', 'admin/dsje/liststatusFixedAsset');

 if($array[3] == 'edit'){
   $breadcrumb[] = l('Edit statusFixedAsset', 'admin/dsje/liststatusFixedAsset/edit/statusFixedAsset/'.$array[5].'');
  }
  drupal_set_breadcrumb($breadcrumb);

	$sqlstatusFixedAsset = "select * from tbl_statusFixedAssets where statusFixedAsset_id=$statusFixedAsset_id";
	$resstatusFixedAsset = db_query($sqlstatusFixedAsset);
	$rsstatusFixedAsset = db_fetch_object($resstatusFixedAsset);
	
	$form['statusFixedAsset_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsstatusFixedAsset->statusFixedAsset_id,
	);
	
	$form['statusFixedAsset_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('statusFixedAsset Name'),
		'#required' => TRUE,
		'#default_value' =>$rsstatusFixedAsset->statusFixedAsset_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_statusFixedAsset_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsstatusFixedAsset->statusFixedAsset_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rsstatusFixedAsset->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); 
	*/
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/liststatusFixedAsset'),
);
	$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/liststatusFixedAsset'),
);
	return $form;
}

function dsje_statusFixedAsset_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$statusFixedAsset_id = $values['statusFixedAsset_id'];
	$statusFixedAsset_name = ParseData($values['statusFixedAsset_name']);
	$prev_statusFixedAsset_name = ParseData($values['prev_statusFixedAsset_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('statusFixedAsset_name',$statusFixedAsset_name,'statusFixedAsset');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_statusFixedAssets} where LOWER(statusFixedAsset_name)= '".strtolower($statusFixedAsset_name)."' GROUP BY statusFixedAsset_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_statusFixedAsset_name), strtolower($statusFixedAsset_name))==0){
			db_query("UPDATE `tbl_statusFixedAssets` set `statusFixedAsset_name` = '".$statusFixedAsset_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where statusFixedAsset_id='".$statusFixedAsset_id."'");
			
			$message = getMessage( 'dsjestatusFixedAsset', 'code05', array("0"=>$statusFixedAsset_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/liststatusFixedAsset");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_statusFixedAssets` set `statusFixedAsset_name` = '".$statusFixedAsset_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where statusFixedAsset_id='".$statusFixedAsset_id."'");
				
				$message = getMessage( 'dsjestatusFixedAsset', 'code05', array("0"=>$statusFixedAsset_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/liststatusFixedAsset");	
			
			}else{
				db_query("UPDATE `tbl_statusFixedAssets` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where statusFixedAsset_id='".$statusFixedAsset_id."'");
				
				$message = getMessage( 'dsjestatusFixedAsset', 'code06', array("0"=>$statusFixedAsset_name));
				form_set_error('statusFixedAsset_name', $message);
			}
		}
	}
}

function dsje_statusFixedAsset_theme() {
	
	return array(
				 
		'dsje_statusFixedAsset_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_statusFixedAsset_form',
                                 ),
        'dsje_statusFixedAsset_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_statusFixedAsset_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_statusFixedAsset_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_statusFixedAsset_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_statusFixedAsset_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function statusFixedAsset_delete($sid, $sno){
  $statusFixedAsset_id =  $sid;
  db_query("UPDATE {tbl_statusFixedAssets} SET status=0 WHERE statusFixedAsset_id ='".$statusFixedAsset_id."'");
  $message = getMessage( 'dsjestatusFixedAsset', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/liststatusFixedAsset");
 }


  function statusFixedAsset_enable($sid, $sno){
    $statusFixedAsset_id =  $sid;
    db_query("UPDATE {tbl_statusFixedAssets} SET status=1 WHERE statusFixedAsset_id ='".$statusFixedAsset_id."'");
  
    $message = getMessage( 'dsjestatusFixedAsset', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/liststatusFixedAsset");
  }

  function dsje_addstatusFixedAssetview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List statusFixedAsset', 'admin/dsje/liststatusFixedAsset');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View statusFixedAsset', 'admin/dsje/liststatusFixedAsset/view/statusFixedAsset/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_statusFixedAssets where statusFixedAsset_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>statusFixedAsset Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>statusFixedAsset:</td><td>'.ucwords($rs->statusFixedAsset_name).'</td></tr>';
// $output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/liststatusFixedAsset');


 return $output;
 
 

  }
	
	