<?php
function dsje_sector_init() {
	//drupal_add_css(drupal_get_path('module', 'rec_language') .'/rec_language.css');
	
}


function dsje_sector_perm() {
	return array('edit dsje_sector','administer dsje_sector', 'create dsje_sector', 'view dsje_sector');
}

function dsje_sector_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_sector', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_sector', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_sector', $account);
	}
	
}

function dsje_sector_menu() {
	
	
	$items['admin/dsje/listsector'] = array(
										'title' => t('List Of Sectors'),
										'description' => 'Allow user to View sector',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewsector',
										'access arguments' => array('administer dsje_sector'),
													 
									  );
	
	$items['admin/dsje/listsector/addsector'] = array(
										'title' => t('Create sector'),
										'description' => 'Allow user to add sector',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_sector',
										'access arguments' => array('administer dsje_sector'),
													 
									  );
   	$items['admin/dsje/listsector/edit/sector/%'] = array(
								
										'title' => t('Edit Sector'),
										'description' => 'Allow user to add sector',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addsectoredit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_sector'),
													 
									  );
   $items['admin/dsje/listsector/view/sector/%'] = array(
								
										'title' => t('View Sector'),
										'description' => 'Allow user to add sector',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addsectorview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_sector'),
													 
									  );
     $items['admin/dsje/del/sector/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'sector_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_sector'),
													 
									  );
    $items['admin/dsje/enable/sector/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'sector_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_sector'),
													 
									  );
	return $items;
}


/**
 listing sector
 */

function viewsector(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjesector', 'code04', NULL);
  
  $header = array(
		array('data' => t('S. No.')),
        array('data' => t('Sector Type'), 'field' => 'sector_name', 'sort' => 'asc'),
		array('data' => t('Status'), 'field' => 'status', 'sort' => 'asc'),
		array('data' => t('Action'), 'class' => 'addeditview',),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List of Sectors', 'admin/dsje/listsector/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']|| $_REQUEST['searchtextstatus']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 $val=addslashes($val);
	
	$status = $_REQUEST['searchtextstatus'];	
	 
	 if( $val && $status ==''){
	 $searchquery = "UPPER(sector_name) LIKE '".$val."' ";
	 }
	 
	else if( $val=='' && $status){
	 $searchquery = "status='".$status."'";
	 }
	 
	 else if($val && ($status =='0' ||$status =='1') ){
	 $searchquery = "(UPPER(sector_name) LIKE '".$val."' AND status='".$status."')";
	 }
	
	 $query = "SELECT sector_id, sector_name, status FROM {tbl_sectors} where ".$searchquery." ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM {tbl_sectors} where ".$searchquery." ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
	$_REQUEST['page']=0;
 }else{
    $query = "SELECT sector_id, sector_name, status FROM {tbl_sectors} ".tablesort_sql($header);
 }
 
 global $base_url;
$action = $base_url.'/admin/dsje/listsector';

$t1=$_POST['searchtextstatus'];
$selected0 ="";
$selected1 ="";

if($_REQUEST['searchtextstatus'] !=''){
	
	if($_REQUEST['searchtextstatus'] == 0){
	  $selected0 ="selected = selected"; 
	}
	
	if($_REQUEST['searchtextstatus'] == 1){
	  $selected1  ="selected =  selected"; 
	}
}else{
$selected0 ="";
$selected1 ="";
}

 $output = '<form method="post" action=""><table width="940px" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']|| $_REQUEST['searchtextstatus']!=''){
	$output .= t(getMessage( 'dsjesector', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listsector');
	}	
	$output .='</td><td colspan="3" class="tblHeaderRight"></td></tr>';	
	$addurl = l(getMessage( 'dsjesector', 'code01', NULL),"admin/dsje/listsector/addsector");
   	$lising = getMessage( 'dsjesector', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight">Status:<select name="searchtextstatus">
	<option value="" selected = "selected">--Select--</option>
	<option value="0" '.$selected0.'>Disabled</option>
	<option value="1" '.$selected1.'>Enabled</option>
	
	</select>&nbsp;&nbsp;<input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listsector/edit/sector/".$row->sector_id);
		$viewurl = l("View","admin/dsje/listsector/view/sector/".$row->sector_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/sector/$row->sector_id/$row->sector_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/sector/$row->sector_id/$row->sector_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->sector_name)),
			array('data' => $st),
			array('data' => $viewurl." | ".$editurl." | ".$deleteurl),
		);
	}
	if($rows== NULL)
	$header=NULL;
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_sector(){
 return drupal_get_form('dsje_sector_form');
}

function dsje_sector_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Sectors', 'admin/dsje/listsector');
  if($array[3] == 'addsector'){
     $breadcrumb[] = l('Add Sector', 'admin/dsje/listsector/addsector');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['sector_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('Sector Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    $form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listsector'),
);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		
	return $form;
}

function dsje_sector_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $sector_name = trim($values['sector_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('sector_name',$sector_name,'sector');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO {tbl_sectors} (`sector_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$sector_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjesector', 'code05', array("0"=>$sector_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listsector');
	}
}

function dsje_sector_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$sector_name = trim($values['sector_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('sector_name',$sector_name,'sector');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_sectors} where UCASE(sector_name)= '".strtoupper($sector_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjesector', 'code06', array("0"=>$sector_name));
			form_set_error('sector_name', $message);
		}
	}	
}

function rec_addsectoredit($sector_id){
 return drupal_get_form('dsje_sector_form_edit',$sector_id);
}

function dsje_sector_form_edit(&$form_states,$sector_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Sector', 'admin/dsje/listsector');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit Sector', 'admin/dsje/listsector/edit/sector/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlsector = "select * FROM {tbl_sectors} where sector_id=$sector_id";
	$ressector = db_query($sqlsector);
	$rssector = db_fetch_object($ressector);
	
	$form['sector_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rssector->sector_id,
	);
	
	$form['sector_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('Sector Name'),
		'#required' => TRUE,
		'#default_value' =>$rssector->sector_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_sector_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rssector->sector_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rssector->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listsector'),
);
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		
	return $form;
}

function dsje_sector_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$sector_id = $values['sector_id'];
	$sector_name = ParseData($values['sector_name']);
	$prev_sector_name = ParseData($values['prev_sector_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('sector_name',$sector_name,'sector');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_sectors} where LOWER(sector_name)= '".strtolower($sector_name)."' GROUP BY sector_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_sector_name), strtolower($sector_name))==0){
			db_query("UPDATE {tbl_sectors} set `sector_name` = '".$sector_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where sector_id='".$sector_id."'");
			
			$message = getMessage('dsjesector', 'code11', array("0"=>$sector_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listsector");	
			
		}else{
			if($count==0){
				db_query("UPDATE {tbl_sectors} set `sector_name` = '".$sector_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where sector_id='".$sector_id."'");
				
				$message = getMessage('dsjesector', 'code11', array("0"=>$sector_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listsector");	
			
			}else{
				db_query("UPDATE {tbl_sectors} set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where sector_id='".$sector_id."'");
				
				$message = getMessage('dsjesector', 'code06', array("0"=>$sector_name));
				form_set_error('sector_name', $message);
			}
		}
	}
}

function dsje_sector_theme() {
	
	return array(
				 
		'dsje_sector_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_sector_form',
                                 ),
        'dsje_sector_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_sector_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_sector_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_sector_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_sector_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function sector_delete($sid, $sno){
  $sector_id =  $sid;
  db_query("UPDATE {tbl_sectors} SET status=0 WHERE sector_id ='".$sector_id."'");
  $message = getMessage('dsjesector', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listsector");
 }


  function sector_enable($sid, $sno){
    $sector_id =  $sid;
    db_query("UPDATE {tbl_sectors} SET status=1 WHERE sector_id ='".$sector_id."'");
  
    $message = getMessage('dsjesector', 'code10', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listsector");
  }

  function rec_addsectorview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List of Sector', 'admin/dsje/listsector');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View Sector', 'admin/dsje/listsector/view/sector/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * FROM {tbl_sectors} where sector_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<table width="100%" cellpadding="2" cellspacing="1" border="0" id="form-container">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>Sector Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td width="50%">Sector:</td><td class="normal">'.ucwords($rs->sector_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="oddrow"><td width="50%">Status:</td><td class="normal">'.$status.'</td></tr>';
 $output .='<tr class="evenrow"><td colspan="2" align="center" class="back">'.l(t('Back'), 'admin/dsje/listsector').'</td></tr>';
 $output .='</table>';
 return $output;
  }
	
	