<?php
function dsje_remittanceMode_init() {
	//drupal_add_css(drupal_get_path('module', 'dsje_language') .'/dsje_language.css');
	
}


function dsje_remittanceMode_perm() {
	return array('edit dsje_remittanceMode','administer dsje_remittanceMode', 'create dsje_remittanceMode', 'view dsje_remittanceMode');
}

function dsje_remittanceMode_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_remittanceMode', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_remittanceMode', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_remittanceMode', $account);
	}
	
}

function dsje_remittanceMode_menu() {
	
	
	$items['admin/dsje/listremittanceMode'] = array(
										'title' => t('List of remittanceMode'),
										'description' => 'Allow user to View remittanceMode',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewremittanceMode',
										'access arguments' => array('administer dsje_remittanceMode'),
													 
									  );
	
	$items['admin/dsje/listremittanceMode/addremittanceMode'] = array(
										'title' => t('Create remittanceMode'),
										'description' => 'Allow user to add remittanceMode',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_remittanceMode',
										'access arguments' => array('administer dsje_remittanceMode'),
													 
									  );
   	$items['admin/dsje/listremittanceMode/edit/remittanceMode/%'] = array(
								
										'title' => t('Edit remittanceMode'),
										'description' => 'Allow user to add remittanceMode',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addremittanceModeedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_remittanceMode'),
													 
									  );
   $items['admin/dsje/listremittanceMode/view/remittanceMode/%'] = array(
								
										'title' => t('View remittanceMode'),
										'description' => 'Allow user to add remittanceMode',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addremittanceModeview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_remittanceMode'),
													 
									  );
     $items['admin/dsje/del/remittanceMode/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'remittanceMode_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_remittanceMode'),
													 
									  );
    $items['admin/dsje/enable/remittanceMode/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'remittanceMode_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_remittanceMode'),
													 
									  );
	return $items;
}


/**
 listing remittanceMode
 */

function viewremittanceMode(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjeremittanceMode', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('Mode of Remittance'), 'field' => 'remittanceMode_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List remittanceMode', 'admin/dsje/listremittanceMode/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT remittanceMode_id, remittanceMode_name, status FROM tbl_remittanceModes where UPPER(remittanceMode_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_remittanceModes where UPPER(remittanceMode_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT remittanceMode_id, remittanceMode_name, status FROM tbl_remittanceModes ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjeremittanceMode', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listremittanceMode');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjeremittanceMode', 'code01', NULL),"admin/dsje/listremittanceMode/addremittanceMode");
   	$lising = getMessage( 'dsjeremittanceMode', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listremittanceMode/edit/remittanceMode/".$row->remittanceMode_id,array('attributes'=>array('id'=>'edit-remittanceMode-id')));
		$viewurl = l("View","admin/dsje/listremittanceMode/view/remittanceMode/".$row->remittanceMode_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/remittanceMode/$row->remittanceMode_id/$row->remittanceMode_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/remittanceMode/$row->remittanceMode_id/$row->remittanceMode_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->remittanceMode_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_remittanceMode(){
 return drupal_get_form('dsje_remittanceMode_form');
}

function dsje_remittanceMode_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of remittanceMode', 'admin/dsje/listremittanceMode');
  if($array[3] == 'addremittanceMode'){
     $breadcrumb[] = l('Add remittanceMode', 'admin/dsje/listremittanceMode/addremittanceMode');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['remittanceMode_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('remittanceMode Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listremittanceMode'),
);
	return $form;
}

function dsje_remittanceMode_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $remittanceMode_name = trim($values['remittanceMode_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('remittanceMode_name',$remittanceMode_name,'remittanceMode');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_remittanceModes` (`remittanceMode_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$remittanceMode_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjeremittanceMode', 'code05', array("0"=>$remittanceMode_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listremittanceMode');
	}
}

function dsje_remittanceMode_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$remittanceMode_name = trim($values['remittanceMode_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('remittanceMode_name',$remittanceMode_name,'remittanceMode');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_remittanceModes} where UCASE(remittanceMode_name)= '".strtoupper($remittanceMode_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjeremittanceMode', 'code06', array("0"=>$remittanceMode_name));
			form_set_error('remittanceMode_name', $message);
		}
	}	
}

function dsje_addremittanceModeedit($remittanceMode_id){
 return drupal_get_form('dsje_remittanceMode_form_edit',$remittanceMode_id);
}

function dsje_remittanceMode_form_edit(&$form_states,$remittanceMode_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List remittanceMode', 'admin/dsje/listremittanceMode');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit remittanceMode', 'admin/dsje/listremittanceMode/edit/remittanceMode/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlremittanceMode = "select * from tbl_remittanceModes where remittanceMode_id=$remittanceMode_id";
	$resremittanceMode = db_query($sqlremittanceMode);
	$rsremittanceMode = db_fetch_object($resremittanceMode);
	
	$form['remittanceMode_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsremittanceMode->remittanceMode_id,
	);
	
	$form['remittanceMode_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('remittanceMode Name'),
		'#required' => TRUE,
		'#default_value' =>$rsremittanceMode->remittanceMode_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_remittanceMode_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsremittanceMode->remittanceMode_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rsremittanceMode->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listremittanceMode'),
);
	return $form;
}

function dsje_remittanceMode_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$remittanceMode_id = $values['remittanceMode_id'];
	$remittanceMode_name = ParseData($values['remittanceMode_name']);
	$prev_remittanceMode_name = ParseData($values['prev_remittanceMode_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('remittanceMode_name',$remittanceMode_name,'remittanceMode');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_remittanceModes} where LOWER(remittanceMode_name)= '".strtolower($remittanceMode_name)."' GROUP BY remittanceMode_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_remittanceMode_name), strtolower($remittanceMode_name))==0){
			db_query("UPDATE `tbl_remittanceModes` set `remittanceMode_name` = '".$remittanceMode_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where remittanceMode_id='".$remittanceMode_id."'");
			
			$message = getMessage('dsjeremittanceMode', 'code05', array("0"=>$remittanceMode_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listremittanceMode");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_remittanceModes` set `remittanceMode_name` = '".$remittanceMode_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where remittanceMode_id='".$remittanceMode_id."'");
				
				$message = getMessage('dsjeremittanceMode', 'code05', array("0"=>$remittanceMode_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listremittanceMode");	
			
			}else{
				db_query("UPDATE `tbl_remittanceModes` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where remittanceMode_id='".$remittanceMode_id."'");
				
				$message = getMessage('dsjeremittanceMode', 'code06', array("0"=>$remittanceMode_name));
				form_set_error('remittanceMode_name', $message);
			}
		}
	}
}

function dsje_remittanceMode_theme() {
	
	return array(
				 
		'dsje_remittanceMode_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_remittanceMode_form',
                                 ),
        'dsje_remittanceMode_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_remittanceMode_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_remittanceMode_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_remittanceMode_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_remittanceMode_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function remittanceMode_delete($sid, $sno){
  $remittanceMode_id =  $sid;
  db_query("UPDATE {tbl_remittanceModes} SET status=0 WHERE remittanceMode_id ='".$remittanceMode_id."'");
  $message = getMessage('dsjeremittanceMode', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listremittanceMode");
 }


  function remittanceMode_enable($sid, $sno){
    $remittanceMode_id =  $sid;
    db_query("UPDATE {tbl_remittanceModes} SET status=1 WHERE remittanceMode_id ='".$remittanceMode_id."'");
  
    $message = getMessage('dsjeremittanceMode', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listremittanceMode");
  }

  function dsje_addremittanceModeview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List remittanceMode', 'admin/dsje/listremittanceMode');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View remittanceMode', 'admin/dsje/listremittanceMode/view/remittanceMode/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_remittanceModes where remittanceMode_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>remittanceMode Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>remittanceMode:</td><td>'.ucwords($rs->remittanceMode_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listremittanceMode');
 return $output;
  }
	
	