<?php
function dsje_month_init() {
	//drupal_add_css(drupal_get_path('module', 'rec_language') .'/rec_language.css');
	
}


function dsje_month_perm() {
	return array('edit dsje_month','administer dsje_month', 'create dsje_month', 'view dsje_month');
}

function dsje_month_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_month', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_month', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_month', $account);
	}
	
}

function dsje_month_menu() {
	
	
	$items['admin/dsje/listmonth'] = array(
										'title' => t('List of month'),
										'description' => 'Allow user to View month',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewmonth',
										'access arguments' => array('administer dsje_month'),
													 
									  );
	
	$items['admin/dsje/listmonth/addmonth'] = array(
										'title' => t('Create month'),
										'description' => 'Allow user to add month',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_month',
										'access arguments' => array('administer dsje_month'),
													 
									  );
   	$items['admin/dsje/listmonth/edit/month/%'] = array(
								
										'title' => t('Edit month'),
										'description' => 'Allow user to add month',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addmonthedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_month'),
													 
									  );
   $items['admin/dsje/listmonth/view/month/%'] = array(
								
										'title' => t('View month'),
										'description' => 'Allow user to add month',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addmonthview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_month'),
													 
									  );
     $items['admin/dsje/del/month/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'month_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_month'),
													 
									  );
    $items['admin/dsje/enable/month/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'month_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_month'),
													 
									  );
	return $items;
}


/**
 listing month
 */

function viewmonth(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjemonth', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('month'), 'field' => 'month_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List month', 'admin/dsje/listmonth/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT month_id, month_name, status FROM tbl_months where UPPER(month_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_months where UPPER(month_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT month_id, month_name, status FROM tbl_months ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjemonth', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listmonth');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjemonth', 'code01', NULL),"admin/dsje/listmonth/addmonth");
   	$lising = getMessage( 'dsjemonth', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listmonth/edit/month/".$row->month_id,array('attributes'=>array('id'=>'edit-month-id')));
		$viewurl = l("View","admin/dsje/listmonth/view/month/".$row->month_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/month/$row->month_id/$row->month_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/month/$row->month_id/$row->month_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->month_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_month(){
 return drupal_get_form('dsje_month_form');
}

function dsje_month_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of month', 'admin/dsje/listmonth');
  if($array[3] == 'addmonth'){
     $breadcrumb[] = l('Add month', 'admin/dsje/listmonth/addmonth');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['month_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('month Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listmonth'),
);
	return $form;
}

function dsje_month_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $month_name = trim($values['month_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('month_name',$month_name,'month');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_months` (`month_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$month_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjemonth', 'code05', array("0"=>$month_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listmonth');
	}
}

function dsje_month_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$month_name = trim($values['month_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('month_name',$month_name,'month');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_months} where UCASE(month_name)= '".strtoupper($month_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjemonth', 'code06', array("0"=>$month_name));
			form_set_error('month_name', $message);
		}
	}	
}

function rec_addmonthedit($month_id){
 return drupal_get_form('dsje_month_form_edit',$month_id);
}

function dsje_month_form_edit(&$form_states,$month_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List month', 'admin/dsje/listmonth');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit month', 'admin/dsje/listmonth/edit/month/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlmonth = "select * from tbl_months where month_id=$month_id";
	$resmonth = db_query($sqlmonth);
	$rsmonth = db_fetch_object($resmonth);
	
	$form['month_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsmonth->month_id,
	);
	
	$form['month_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('month Name'),
		'#required' => TRUE,
		'#default_value' =>$rsmonth->month_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_month_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsmonth->month_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rsmonth->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listmonth'),
);
	return $form;
}

function dsje_month_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$month_id = $values['month_id'];
	$month_name = ParseData($values['month_name']);
	$prev_month_name = ParseData($values['prev_month_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('month_name',$month_name,'month');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_months} where LOWER(month_name)= '".strtolower($month_name)."' GROUP BY month_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_month_name), strtolower($month_name))==0){
			db_query("UPDATE `tbl_months` set `month_name` = '".$month_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where month_id='".$month_id."'");
			
			$message = getMessage('dsjemonth', 'code05', array("0"=>$month_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listmonth");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_months` set `month_name` = '".$month_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where month_id='".$month_id."'");
				
				$message = getMessage('dsjemonth', 'code05', array("0"=>$month_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listmonth");	
			
			}else{
				db_query("UPDATE `tbl_months` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where month_id='".$month_id."'");
				
				$message = getMessage('dsjemonth', 'code06', array("0"=>$month_name));
				form_set_error('month_name', $message);
			}
		}
	}
}

function dsje_month_theme() {
	
	return array(
				 
		'dsje_month_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_month_form',
                                 ),
        'dsje_month_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_month_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_month_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_month_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_month_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function month_delete($sid, $sno){
  $month_id =  $sid;
  db_query("UPDATE {tbl_months} SET status=0 WHERE month_id ='".$month_id."'");
  $message = getMessage('dsjemonth', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listmonth");
 }


  function month_enable($sid, $sno){
    $month_id =  $sid;
    db_query("UPDATE {tbl_months} SET status=1 WHERE month_id ='".$month_id."'");
  
    $message = getMessage('dsjemonth', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listmonth");
  }

  function rec_addmonthview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List month', 'admin/dsje/listmonth');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View month', 'admin/dsje/listmonth/view/month/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_months where month_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>month Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>month:</td><td>'.ucwords($rs->month_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listmonth');
 return $output;
  }
	
	