<?php
function dsje_religion_init() {
	//drupal_add_css(drupal_get_path('module', 'rec_language') .'/rec_language.css');
	
}


function dsje_religion_perm() {
	return array('edit dsje_religion','administer dsje_religion', 'create dsje_religion', 'view dsje_religion');
}

function dsje_religion_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_religion', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_religion', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_religion', $account);
	}
	
}

function dsje_religion_menu() {
	
	
	$items['admin/dsje/listreligion'] = array(
										'title' => t('List of religion'),
										'description' => 'Allow user to View religion',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewreligion',
										'access arguments' => array('administer dsje_religion'),
													 
									  );
	
	$items['admin/dsje/listreligion/addreligion'] = array(
										'title' => t('Create religion'),
										'description' => 'Allow user to add religion',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_religion',
										'access arguments' => array('administer dsje_religion'),
													 
									  );
   	$items['admin/dsje/listreligion/edit/religion/%'] = array(
								
										'title' => t('Edit religion'),
										'description' => 'Allow user to add religion',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addreligionedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_religion'),
													 
									  );
   $items['admin/dsje/listreligion/view/religion/%'] = array(
								
										'title' => t('View religion'),
										'description' => 'Allow user to add religion',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addreligionview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_religion'),
													 
									  );
     $items['admin/dsje/del/religion/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'religion_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_religion'),
													 
									  );
    $items['admin/dsje/enable/religion/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'religion_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_religion'),
													 
									  );
	return $items;
}


/**
 listing religion
 */

function viewreligion(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjereligion', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('religion'), 'field' => 'religion_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List religion', 'admin/dsje/listreligion/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT religion_id, religion_name, status FROM tbl_religions where UPPER(religion_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_religions where UPPER(religion_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT religion_id, religion_name, status FROM tbl_religions ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjereligion', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listreligion');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjereligion', 'code01', NULL),"admin/dsje/listreligion/addreligion");
   	$lising = getMessage( 'dsjereligion', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listreligion/edit/religion/".$row->religion_id,array('attributes'=>array('id'=>'edit-religion-id')));
		$viewurl = l("View","admin/dsje/listreligion/view/religion/".$row->religion_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/religion/$row->religion_id/$row->religion_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/religion/$row->religion_id/$row->religion_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->religion_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_religion(){
 return drupal_get_form('dsje_religion_form');
}

function dsje_religion_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of religion', 'admin/dsje/listreligion');
  if($array[3] == 'addreligion'){
     $breadcrumb[] = l('Add religion', 'admin/dsje/listreligion/addreligion');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['religion_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('religion Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listreligion'),
);
	return $form;
}

function dsje_religion_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $religion_name = trim($values['religion_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('religion_name',$religion_name,'religion');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_religions` (`religion_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$religion_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjereligion', 'code05', array("0"=>$religion_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listreligion');
	}
}

function dsje_religion_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$religion_name = trim($values['religion_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('religion_name',$religion_name,'religion');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_religions} where UCASE(religion_name)= '".strtoupper($religion_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjereligion', 'code06', array("0"=>$religion_name));
			form_set_error('religion_name', $message);
		}
	}	
}

function rec_addreligionedit($religion_id){
 return drupal_get_form('dsje_religion_form_edit',$religion_id);
}

function dsje_religion_form_edit(&$form_states,$religion_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List religion', 'admin/dsje/listreligion');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit religion', 'admin/dsje/listreligion/edit/religion/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlreligion = "select * from tbl_religions where religion_id=$religion_id";
	$resreligion = db_query($sqlreligion);
	$rsreligion = db_fetch_object($resreligion);
	
	$form['religion_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsreligion->religion_id,
	);
	
	$form['religion_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('religion Name'),
		'#required' => TRUE,
		'#default_value' =>$rsreligion->religion_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_religion_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rsreligion->religion_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rsreligion->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listreligion'),
);
	return $form;
}

function dsje_religion_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$religion_id = $values['religion_id'];
	$religion_name = ParseData($values['religion_name']);
	$prev_religion_name = ParseData($values['prev_religion_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('religion_name',$religion_name,'religion');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_religions} where LOWER(religion_name)= '".strtolower($religion_name)."' GROUP BY religion_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_religion_name), strtolower($religion_name))==0){
			db_query("UPDATE `tbl_religions` set `religion_name` = '".$religion_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where religion_id='".$religion_id."'");
			
			$message = getMessage('dsjereligion', 'code05', array("0"=>$religion_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listreligion");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_religions` set `religion_name` = '".$religion_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where religion_id='".$religion_id."'");
				
				$message = getMessage('dsjereligion', 'code05', array("0"=>$religion_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listreligion");	
			
			}else{
				db_query("UPDATE `tbl_religions` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where religion_id='".$religion_id."'");
				
				$message = getMessage('dsjereligion', 'code06', array("0"=>$religion_name));
				form_set_error('religion_name', $message);
			}
		}
	}
}

function dsje_religion_theme() {
	
	return array(
				 
		'dsje_religion_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_religion_form',
                                 ),
        'dsje_religion_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_religion_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_religion_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_religion_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_religion_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function religion_delete($sid, $sno){
  $religion_id =  $sid;
  db_query("UPDATE {tbl_religions} SET status=0 WHERE religion_id ='".$religion_id."'");
  $message = getMessage('dsjereligion', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listreligion");
 }


  function religion_enable($sid, $sno){
    $religion_id =  $sid;
    db_query("UPDATE {tbl_religions} SET status=1 WHERE religion_id ='".$religion_id."'");
  
    $message = getMessage('dsjereligion', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listreligion");
  }

  function rec_addreligionview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List religion', 'admin/dsje/listreligion');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View religion', 'admin/dsje/listreligion/view/religion/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_religions where religion_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>religion Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>religion:</td><td>'.ucwords($rs->religion_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listreligion');
 return $output;
  }
	
	