<?php
function dsje_citizenship_init() {
	//drupal_add_css(drupal_get_path('module', 'rec_language') .'/rec_language.css');
	
}


function dsje_citizenship_perm() {
	return array('edit dsje_citizenship','administer dsje_citizenship', 'create dsje_citizenship', 'view dsje_citizenship');
}

function dsje_citizenship_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_citizenship', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_citizenship', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_citizenship', $account);
	}
	
}

function dsje_citizenship_menu() {
	
	
	$items['admin/dsje/listcitizenship'] = array(
										'title' => t('List of citizenship'),
										'description' => 'Allow user to View citizenship',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewcitizenship',
										'access arguments' => array('administer dsje_citizenship'),
													 
									  );
	
	$items['admin/dsje/listcitizenship/addcitizenship'] = array(
										'title' => t('Create citizenship'),
										'description' => 'Allow user to add citizenship',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_citizenship',
										'access arguments' => array('administer dsje_citizenship'),
													 
									  );
   	$items['admin/dsje/listcitizenship/edit/citizenship/%'] = array(
								
										'title' => t('Edit citizenship'),
										'description' => 'Allow user to add citizenship',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addcitizenshipedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_citizenship'),
													 
									  );
   $items['admin/dsje/listcitizenship/view/citizenship/%'] = array(
								
										'title' => t('View citizenship'),
										'description' => 'Allow user to add citizenship',
										'type' => MENU_CALLBACK,
										'page callback' => 'rec_addcitizenshipview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_citizenship'),
													 
									  );
     $items['admin/dsje/del/citizenship/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'citizenship_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_citizenship'),
													 
									  );
    $items['admin/dsje/enable/citizenship/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'citizenship_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_citizenship'),
													 
									  );
	return $items;
}


/**
 listing citizenship
 */

function viewcitizenship(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjecitizenship', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('citizenship'), 'field' => 'citizenship_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List citizenship', 'admin/dsje/citizenship/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT citizenship_id, citizenship_name, status FROM tbl_citizenships where UPPER(citizenship_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_citizenships where UPPER(citizenship_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT citizenship_id, citizenship_name, status FROM tbl_citizenships ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjecitizenship', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listcitizenship');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjecitizenship', 'code01', NULL),"admin/dsje/listcitizenship/addcitizenship");
   	$lising = getMessage( 'dsjecitizenship', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listcitizenship/edit/citizenship/".$row->citizenship_id,array('attributes'=>array('id'=>'edit-citizenship-id')));
		$viewurl = l("View","admin/dsje/listcitizenship/view/citizenship/".$row->citizenship_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/citizenship/$row->citizenship_id/$row->citizenship_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/citizenship/$row->citizenship_id/$row->citizenship_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->citizenship_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_citizenship(){
 return drupal_get_form('dsje_citizenship_form');
}

function dsje_citizenship_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of citizenship', 'admin/dsje/listcitizenship');
  if($array[3] == 'addcitizenship'){
     $breadcrumb[] = l('Add citizenship', 'admin/dsje/listcitizenship/addcitizenship');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['citizenship_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('citizenship Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listcitizenship'),
);
	return $form;
}

function dsje_citizenship_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $citizenship_name = trim($values['citizenship_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('citizenship_name',$citizenship_name,'citizenship');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_citizenships` (`citizenship_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$citizenship_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjecitizenship', 'code05', array("0"=>$citizenship_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listcitizenship');
	}
}

function dsje_citizenship_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$citizenship_name = trim($values['citizenship_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('citizenship_name',$citizenship_name,'citizenship');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_citizenships} where UCASE(citizenship_name)= '".strtoupper($citizenship_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjecitizenship', 'code06', array("0"=>$citizenship_name));
			form_set_error('citizenship_name', $message);
		}
	}	
}

function rec_addcitizenshipedit($citizenship_id){
 return drupal_get_form('dsje_citizenship_form_edit',$citizenship_id);
}

function dsje_citizenship_form_edit(&$form_states,$citizenship_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List citizenship', 'admin/dsje/listcitizenship');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit citizenship', 'admin/dsje/listcitizenship/edit/citizenship/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlcitizenship = "select * from tbl_citizenships where citizenship_id=$citizenship_id";
	$rescitizenship = db_query($sqlcitizenship);
	$rscitizenship = db_fetch_object($rescitizenship);
	
	$form['citizenship_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rscitizenship->citizenship_id,
	);
	
	$form['citizenship_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('citizenship Name'),
		'#required' => TRUE,
		'#default_value' =>$rscitizenship->citizenship_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_citizenship_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rscitizenship->citizenship_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rscitizenship->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listcitizenship'),
);
	return $form;
}

function dsje_citizenship_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$citizenship_id = $values['citizenship_id'];
	$citizenship_name = ParseData($values['citizenship_name']);
	$prev_citizenship_name = ParseData($values['prev_citizenship_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('citizenship_name',$citizenship_name,'citizenship');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_citizenships} where LOWER(citizenship_name)= '".strtolower($citizenship_name)."' GROUP BY citizenship_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_citizenship_name), strtolower($citizenship_name))==0){
			db_query("UPDATE `tbl_citizenships` set `citizenship_name` = '".$citizenship_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where citizenship_id='".$citizenship_id."'");
			
			$message = getMessage('dsjecitizenship', 'code05', array("0"=>$citizenship_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listcitizenship");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_citizenships` set `citizenship_name` = '".$citizenship_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where citizenship_id='".$citizenship_id."'");
				
				$message = getMessage('dsjecitizenship', 'code05', array("0"=>$citizenship_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listcitizenship");	
			
			}else{
				db_query("UPDATE `tbl_citizenships` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where citizenship_id='".$citizenship_id."'");
				
				$message = getMessage('dsjecitizenship', 'code06', array("0"=>$citizenship_name));
				form_set_error('citizenship_name', $message);
			}
		}
	}
}

function dsje_citizenship_theme() {
	
	return array(
				 
		'dsje_citizenship_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_citizenship_form',
                                 ),
        'dsje_citizenship_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_citizenship_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_citizenship_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_citizenship_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_citizenship_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function citizenship_delete($sid, $sno){
  $citizenship_id =  $sid;
  db_query("UPDATE {tbl_citizenships} SET status=0 WHERE citizenship_id ='".$citizenship_id."'");
  $message = getMessage('dsjecitizenship', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listcitizenship");
 }


  function citizenship_enable($sid, $sno){
    $citizenship_id =  $sid;
    db_query("UPDATE {tbl_citizenships} SET status=1 WHERE citizenship_id ='".$citizenship_id."'");
  
    $message = getMessage('dsjecitizenship', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listcitizenship");
  }

  function rec_addcitizenshipview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List citizenship', 'admin/dsje/listcitizenship');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View citizenship', 'admin/dsje/listcitizenship/view/citizenship/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_citizenships where citizenship_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>citizenship Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>citizenship:</td><td>'.ucwords($rs->citizenship_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listcitizenship');
 return $output;
  }
	
	