<?php
function dsje_section_init() {
	//drupal_add_css(drupal_get_path('module', 'dsje_language') .'/dsje_language.css');
	
}


function dsje_section_perm() {
	return array('edit dsje_section','administer dsje_section', 'create dsje_section', 'view dsje_section');
}

function dsje_section_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit dsje_section', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create dsje_section', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view dsje_section', $account);
	}
	
}

function dsje_section_menu() {
	
	
	$items['admin/dsje/listsection'] = array(
										'title' => t('List of sections'),
										'description' => 'Allow user to View section',
										'type' => MENU_NORMAL_ITEM,
										'page callback' => 'viewsection',
										'access arguments' => array('administer dsje_section'),
													 
									  );
	
	$items['admin/dsje/listsection/addsection'] = array(
										'title' => t('Create section'),
										'description' => 'Allow user to add section',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_section',
										'access arguments' => array('administer dsje_section'),
													 
									  );
   	$items['admin/dsje/listsection/edit/section/%'] = array(
								
										'title' => t('Edit section'),
										'description' => 'Allow user to add section',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addsectionedit',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_section'),
													 
									  );
   $items['admin/dsje/listsection/view/section/%'] = array(
								
										'title' => t('View section'),
										'description' => 'Allow user to add section',
										'type' => MENU_CALLBACK,
										'page callback' => 'dsje_addsectionview',
                                        'page arguments' => array(5),
		                                'access arguments' => array('administer dsje_section'),
													 
									  );
     $items['admin/dsje/del/section/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'section_delete',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_section'),
													 
									  );
    $items['admin/dsje/enable/section/%/%'] =  array(
										'type' => MENU_CALLBACK,
										'page callback' => 'section_enable',
		                                'page arguments' => array(4,5),
		                                'access arguments' => array('administer dsje_section'),
													 
									  );
	return $items;
}


/**
 listing section
 */

function viewsection(){
global $user;
global $base_url;
$limit = (int)getMessage( 'dsjesection', 'code04', NULL);
  
  $header = array(
		array('data' => t('S.No')),
        array('data' => t('section'), 'field' => 'section_name', 'sort' => 'asc'),
		array('data' => t('Status')),
		array('data' => t('Action')),
	);
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List section', 'admin/dsje/listsection/'.$array[3].'');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
	
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	 $query = "SELECT section_id, section_name, status FROM tbl_sections where UPPER(section_name) LIKE '".$val."' ".tablesort_sql($header);
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_sections where UPPER(section_name) LIKE '".$val."' ".tablesort_sql($header);
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
 }else{
    $query = "SELECT section_id, section_name, status FROM tbl_sections ".tablesort_sql($header);
 }
 $output = '<form method="POST" action=""><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="tblHeaderLeft">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'dsjesection', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','admin/dsje/listsection');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight">
	<input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Go"></td></tr>';
	
	$addurl = l(getMessage( 'dsjesection', 'code01', NULL),"admin/dsje/listsection/addsection");
   	$lising = getMessage( 'dsjesection', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'</td>
	<td colspan="3" class="tblHeaderRight">'.$addurl.'</td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		$editurl = l("Edit","admin/dsje/listsection/edit/section/".$row->section_id,array('attributes'=>array('id'=>'edit-section-id')));
		$viewurl = l("View","admin/dsje/listsection/view/section/".$row->section_id);
		
		if($row->status=='1'){
		  $deleteurl = l("Disable","admin/dsje/del/section/$row->section_id/$row->section_name");
        }else{
		  $deleteurl = l("Enable","admin/dsje/enable/section/$row->section_id/$row->section_name");
		
		}


		if($row->status=='1'){
		       $st='Enabled';
		    }else{
			   $st ='Disabled';
			}
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => ucwords($row->section_name)),
			array('data' => $st),
			array('data' => $viewurl."|".$editurl."|".$deleteurl),
		);
	}
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	return $output;
 }

function dsje_section(){
 return drupal_get_form('dsje_section_form');
}

function dsje_section_form() {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List Of section', 'admin/dsje/listsection');
  if($array[3] == 'addsection'){
     $breadcrumb[] = l('Add section', 'admin/dsje/listsection/addsection');
  }

  drupal_set_breadcrumb($breadcrumb);
   $form['section_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('section Name'),
		'#required' => TRUE,
		'#default_value' =>'',
		'#size' =>41,
	    '#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */

	
	/*$form['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#required' => False,
		'#default_value' => 1,
		'#options' => array('0'=>'Disable','1'=>'Enable'),
	); */
    
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listsection'),
);
	return $form;
}

function dsje_section_form_submit($form, &$form_state) {
	global $user;
	$values = $form_state['values'];
    $section_name = trim($values['section_name']);
	$remarks = parseData(trim($values['remarks']));
    $status = $values['status'];
	$status = 1;
	$createdby = $user->uid;
	$createdon = time();
   
	
	$s = textonlyn('section_name',$section_name,'section');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
		db_query("INSERT INTO `tbl_sections` (`section_name`,`status` ,`createdby` ,`createdon`,`updatedby` ,`updatedon`,`remarks`) VALUES('".$section_name."','".$status."','".$createdby."','".$createdon."','".$createdby."','".$createdon."','".$remarks."') ");
	   
		$message = getMessage('dsjesection', 'code05', array("0"=>$section_name));
		drupal_set_message($message);
	   drupal_goto('admin/dsje/listsection');
	}
}

function dsje_section_form_validate($form, &$form_state) {
	$values = $form_state['values'];
	$section_name = trim($values['section_name']);
	$remarks = parseData(trim($values['remarks']));
	
	$s = textonlyn('section_name',$section_name,'section');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$sql = "SELECT * FROM {tbl_sections} where UCASE(section_name)= '".strtoupper($section_name)."' ";
		$res = db_query($sql);
		
		if($rs = db_fetch_object($res)){
			$message = getMessage('dsjesection', 'code06', array("0"=>$section_name));
			form_set_error('section_name', $message);
		}
	}	
}

function dsje_addsectionedit($section_id){
 return drupal_get_form('dsje_section_form_edit',$section_id);
}

function dsje_section_form_edit(&$form_states,$section_id) {
				$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List section', 'admin/dsje/listsection');
  if($array[3] == 'edit'){
     $breadcrumb[] = l('Edit section', 'admin/dsje/listsection/edit/section/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
	$sqlsection = "select * from tbl_sections where section_id=$section_id";
	$ressection = db_query($sqlsection);
	$rssection = db_fetch_object($ressection);
	
	$form['section_id'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rssection->section_id,
	);
	
	$form['section_name'] = array(
	    '#type' =>'textfield',
		'#title' => t('section Name'),
		'#required' => TRUE,
		'#default_value' =>$rssection->section_name,
		'#size' =>41,
		'#attributes' => array('onkeypress' => 'return textonlyn(event)'),
	);
	
	$form['prev_section_name'] = array(
	    '#type' =>'hidden',
		'#default_value' =>$rssection->section_name,
	);

	/*$form['remarks'] = array(
	    '#type' => 'textarea',
		'#title' => t('Remarks'),
		'#default_value' => $rssection->remarks,
		'#rows' =>5,
		'#cols' =>30,    '#attributes' => array('onkeypress' =>'return  textonlywithdotne(event)'),
	); */
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#default_value' => t('Save')
	);
		$form['cancel'] = array(
	'#type' => "markup",
	'#value' => l(t('Back'), 'admin/dsje/listsection'),
);
	return $form;
}

function dsje_section_form_edit_submit($form, &$form_state) {
	global $user;
	
	$values = $form_state['values'];
    $status = $values['status'];
	$section_id = $values['section_id'];
	$section_name = ParseData($values['section_name']);
	$prev_section_name = ParseData($values['prev_section_name']);
	$remarks = parseData($values['remarks']);
	$updatedby = $user->uid;
	$updatedon = time();
	
	$s = textonlyn('section_name',$section_name,'section');
	$s1 = textonlywithdotne('remarks',$remarks, 'Remarks');
	
	if($s == 0 && $s1 == 0){
	
		$countObj = db_fetch_object(db_query("SELECT COUNT(*) AS count FROM {tbl_sections} where LOWER(section_name)= '".strtolower($section_name)."' GROUP BY section_id"));
		$count = $countObj->count;
		
		if( strcmp(strtolower($prev_section_name), strtolower($section_name))==0){
			db_query("UPDATE `tbl_sections` set `section_name` = '".$section_name."' ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where section_id='".$section_id."'");
			
			$message = getMessage('dsjesection', 'code05', array("0"=>$section_name));
			drupal_set_message($message);
			drupal_goto("admin/dsje/listsection");	
			
		}else{
			if($count==0){
				db_query("UPDATE `tbl_sections` set `section_name` = '".$section_name."'  ,`updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where section_id='".$section_id."'");
				
				$message = getMessage('dsjesection', 'code05', array("0"=>$section_name));
				drupal_set_message($message);
				drupal_goto("admin/dsje/listsection");	
			
			}else{
				db_query("UPDATE `tbl_sections` set `updatedby`='".$updatedby."' ,`updatedon`='".$updatedon."',remarks='".$remarks."' where section_id='".$section_id."'");
				
				$message = getMessage('dsjesection', 'code06', array("0"=>$section_name));
				form_set_error('section_name', $message);
			}
		}
	}
}

function dsje_section_theme() {
	
	return array(
				 
		'dsje_section_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_section_form',
                                 ),
        'dsje_section_form_edit' => array(
								'arguments' => array('form' => NULL),
								'template' => 'dsje_section_form_edit',
                                 ),

				 );
}


/**
 *hook_form_alter
 */
  function dsje_section_form_alter(&$form, &$form_state, $form_id){
    //drupal_set_message($form_id);
	if($form_id =='dsje_section_form'){
	 // $form['zone_id']['#disabled'] = TRUE;
	 // $form['state_id']['#disabled'] = TRUE;
	}
	if($form_id =='dsje_section_form_edit'){
	  //$form['zone_id']['#disabled'] = TRUE;
	  //$form['state_id']['#disabled'] = TRUE;
	}
 }

function section_delete($sid, $sno){
  $section_id =  $sid;
  db_query("UPDATE {tbl_sections} SET status=0 WHERE section_id ='".$section_id."'");
  $message = getMessage('dsjesection', 'code07', array("0"=>$sno));
  drupal_set_message($message);
  drupal_goto("admin/dsje/listsection");
 }


  function section_enable($sid, $sno){
    $section_id =  $sid;
    db_query("UPDATE {tbl_sections} SET status=1 WHERE section_id ='".$section_id."'");
  
    $message = getMessage('dsjesection', 'code09', array("0"=>$sno));
	drupal_set_message($message);
    drupal_goto("admin/dsje/listsection");
  }

  function dsje_addsectionview($id){
	  			$array = explode('/',$_GET['q']);
//echo '<pre>';
//print_r($array);
//echo '<pre>';

  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('List section', 'admin/dsje/listsection');
  if($array[3] == 'view'){
     $breadcrumb[] = l('View section', 'admin/dsje/listsection/view/section/'.$array[5].'');
  }

  drupal_set_breadcrumb($breadcrumb);
    $sql = "select * from tbl_sections where section_id=$id";
	$res = db_query($sql);
	$rs = db_fetch_object($res);
	if($rs->status ==1){
   $status ='Enable';
 }else{
   $status ='Disable';
 }
 
 
$remarks = ucfirst($rs->remarks);
 if($remarks==''){$remarks='N/A';}
 
 $output .='<div id="dms-agreement"><table cellpadding="0" cellspacing="0" border="0" id="wrapper">';
 $output .='<tr class="oddrow"><td colspan="2"><h2>section Details</h2></td></tr>';
  $output .='<tr class="evenrow"><td>section:</td><td>'.ucwords($rs->section_name).'</td></tr>';
 ////$output .='<tr class="oddrow"><td>Remarks:</td><td>'.$remarks.'</td></tr>';
 $output .='<tr class="evenrow"><td>Status:</td><td>'.$status.'</td></tr>';
 $output .='</table></div>';
$output .=  l(t('Back'), 'admin/dsje/listsection');
 return $output;
  }
	
	