<?php
global $base_url;

function interestleadger_perm() {
	return array('edit interestleadger','administer interestleadger', 'create interestleadger', 'view interestleadger');
}

function interestleadger_access($op, $node, $account) {
	if($op == 'update' || $op == 'delete') {
		//&& ($account->uid == $node->uid)
		if (user_access('edit interestleadger', $account) ) {
			return TRUE;
		}
	}
	if (($op=='create') && ($op='list')) {
		return user_access('create interestleadger', $account);
	}
	if (($op=='view') or ($op=='list')) {
		return user_access('view interestleadger', $account);
	}
	
}

function interestleadger_menu(){

	$items['interestleadger'] = array(
			'title' => t('Interest'),
			'type' => MENU_CALLBACK,
			'page callback' => 'interestleadger',
			'access arguments' => array('administer interestleadger'),
						 
		  );
		  
		  $items['defaulter'] = array(
			'title' => t('Defaulter List Within Loan Period'),
			'type' => MENU_CALLBACK,
			'page callback' => 'defaulterlist',
			'access arguments' => array('administer interestleadger'),
						 
		  );
		  
		    $items['defaulter6'] = array(
			'title' => t('Defaulter List Beyond Loan Period'),
			'type' => MENU_CALLBACK,
			'page callback' => 'defaulterlist6',
			'access arguments' => array('administer interestleadger'),
						 
		  );
		  
		  
		  
		   return $items;
}


function selectscheme(){
global $user;
 $use="select * from tbl_scheme_master";
$usq = db_query($use);
$scheme = array('all'=>'All');
 while($usre = db_fetch_array($usq)){
 $scheme_id=$usre['loan_scheme_id'];
   $scheme[$scheme_id] = $usre[scheme_name];
  }
 
  return $scheme;
}

function interestleadger(){
  return drupal_get_form('interestleadger_form');
}

function interestleadger_form(){
	global $user;
	
	$array = explode('/',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('Interest Ledger', 'interestleadger');
	
	drupal_set_breadcrumb($breadcrumb);
	
	
	$form['schemename'] = array(
	'#type' =>'select',
	'#title' => t('Scheme Name'),
	'#required' =>TRUE,
	'#default_value' =>'', 
	'#options' => selectscheme(),
	
		
	);
	
	$form['startdate'] = array(
	'#type' =>'date_popup',
	'#title' => t('Start Date'),
	'#required' =>TRUE,
	'#default_value' =>'', 
	'#size' => 10,
	'#date_format' => 'd-m-Y',
		
	);
	$form['enddate'] = array(
	'#type' =>'date_popup',
	'#title' => t('End Date'),
	'#required' =>TRUE,
	'#default_value' =>'', 
	'#size' =>10,
	'#date_format' => 'd-m-Y',
		
	);
	
	$form['submit'] = array(
	'#type' => 'button',
	'#default_value' => t('Generate')
	);
	return $form;
	}
	
	
	function defaulterlist(){
     return drupal_get_form('defaulterlist_form');
   }

function defaulterlist_form(){
	global $user;
	
	$array = explode('/',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('Defaulter List', 'defaulter');
	
	drupal_set_breadcrumb($breadcrumb);

    // District Array
	$sqldistrict = "select * from tbl_district WHERE status='1'";
    $resdistrict =db_query($sqldistrict);
    if($resdistrict){
        $districtarray[''] = '-SELECT DISTRICT-';
        while($rsdistrict = db_fetch_object($resdistrict)){
            $districtarray[$rsdistrict->district_id] = ucfirst($rsdistrict->district_name);
        }
    }

    // Tehsil Array
    $sqltehsil = "select * from tbl_tehsil WHERE status='1'";
    $restehsil =db_query($sqltehsil);
    if($restehsil){
        $tehsilarray[''] = '-SELECT TEHSIL-';
        while($rstehsil = db_fetch_object($restehsil)){
            $tehsilarray[$rstehsil->tehsil_id] = ucfirst($rstehsil->tehsil_name);
        }
    }

    // Panchayat Array
    $sqlpanchayat = "select * from tbl_panchayt WHERE status='1'";
    $respanchayat =db_query($sqlpanchayat);
    if($respanchayat){
        $panchayatarray[''] = '-SELECT PANCHAYAT-';
        while($rspanchayat = db_fetch_object($respanchayat)){
            $panchayatarray[$rspanchayat->panchayt_id] = ucfirst($rspanchayat->panchayt_name);
        }
    }
	
	$form['type'] = array(
	'#type' =>'select',
	'#title' => '',
	'#required' =>TRUE,
	'#default_value' =>'', 
	'#options' => array('' => '-SELECT TYPE-','alr' => 'ALR', 'defaulter' => 'Defaulter'),
	
		
	);

    $form['district_id'] = array(
        '#type' => 'select',
        '#title' => t(''),
        '#required' => false,
        '#default_value' => '',
        '#options' => $districtarray,

    );

    $form['tehsil_id'] = array(
        '#type' => 'select',
        '#title' => t(''),
        '#required' => false,
        '#default_value' => '',
        '#options' => $tehsilarray,

    );

    $form['panchayat_id'] = array(
        '#type' => 'select',
        '#title' => t(''),
        '#required' => false,
        '#default_value' => '',
        '#options' => $panchayatarray,

    );
	
	$form['startdate'] = array(
	'#type' =>'date_popup',
	'#title' => '',
	'#required' =>TRUE,
	'#default_value' =>'-START DATE-',
	'#size' => 10,
	'#date_format' => 'd-m-Y',
		
	);
	$form['enddate'] = array(
	'#type' =>'date_popup',
    '#title' => '',
	'#required' =>TRUE,
	'#default_value' =>'-END DATE-',
	'#size' =>10,
	'#date_format' => 'd-m-Y',
		
	);
	
	$form['submit'] = array(
	'#type' => 'button',
	'#default_value' => t('Generate')
	);
	return $form;
	}
	

function defaulterlist_form_validate($form,&$form_state){
    $startdate= $form_state['values']['startdate'];
    $enddate= $form_state['values']['enddate'];
    $type =$form_state['values']['type'];

    if((strtotime($startdate)) > (strtotime($enddate))) {
	    form_set_error('form','Start Date Can Not Be Greater Than To Date');
    }

	}
	
	///Nishant Report//

function defaulterlist6(){
  return drupal_get_form('defaulterlist6_form');
}

function defaulterlist6_form(){
	global $user;
	
	$array = explode('/',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('Defaulter List Beyond Loan Period', 'defaulter6');
	
	drupal_set_breadcrumb($breadcrumb);
    // District Array
    $sqldistrict = "select * from tbl_district WHERE status='1'";
    $resdistrict =db_query($sqldistrict);
    if($resdistrict){
        $districtarray[''] = '-SELECT DISTRICT-';
        while($rsdistrict = db_fetch_object($resdistrict)){
            $districtarray[$rsdistrict->district_id] = ucfirst($rsdistrict->district_name);
        }
    }

    // Tehsil Array
    $sqltehsil = "select * from tbl_tehsil WHERE status='1'";
    $restehsil =db_query($sqltehsil);
    if($restehsil){
        $tehsilarray[''] = '-SELECT TEHSIL-';
        while($rstehsil = db_fetch_object($restehsil)){
            $tehsilarray[$rstehsil->tehsil_id] = ucfirst($rstehsil->tehsil_name);
        }
    }

    // Panchayat Array
    $sqlpanchayat = "select * from tbl_panchayt WHERE status='1'";
    $respanchayat =db_query($sqlpanchayat);
    if($respanchayat){
        $panchayatarray[''] = '-SELECT PANCHAYAT-';
        while($rspanchayat = db_fetch_object($respanchayat)){
            $panchayatarray[$rspanchayat->panchayt_id] = ucfirst($rspanchayat->panchayt_name);
        }
    }

    $form['type'] = array(
        '#type' =>'select',
        '#title' => '',
        '#required' =>TRUE,
        '#default_value' =>'',
        '#options' => array('' => '-SELECT TYPE-','alr' => 'ALR', 'defaulter' => 'Defaulter'),


    );

    $form['district_id'] = array(
        '#type' => 'select',
        '#title' => t(''),
        '#required' => false,
        '#default_value' => '',
        '#options' => $districtarray,

    );

    $form['tehsil_id'] = array(
        '#type' => 'select',
        '#title' => t(''),
        '#required' => false,
        '#default_value' => '',
        '#options' => $tehsilarray,

    );

    $form['panchayat_id'] = array(
        '#type' => 'select',
        '#title' => t(''),
        '#required' => false,
        '#default_value' => '',
        '#options' => $panchayatarray,

    );
	
	$form['submit'] = array(
	'#type' => 'button',
	'#default_value' => t('Generate')
	);
	return $form;
	}
	
	
function defaulterlist6_form_validate($form,&$form_state){
	

 $startdate= $form_state['values']['startdate'];
 $enddate= $form_state['values']['enddate'];
$type =$form_state['values']['type'];

 if((strtotime($startdate)) > (strtotime($enddate)))
 { 
	 form_set_error('form','Start Date Can Not Be Greater Than To Date'); 
 }

	}
	
	function interestleadger_theme() {
	
	return array(
				 
		'interestleadger_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'interestleadger_form',
                                 ),
								 
		'defaulterlist_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'defaulterlist_form',
                                 ),							 
						 
       'defaulterlist6_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'defaulterlist6_form',
                                 ),							 
						 

				 );
}


