<?php
global $user;
global $root_path, $xpathObj;

function alr_init() {
	global $root_path, $xpathObj, $emailObj;
	$xpathObj = simplexml_load_file("app_msg.xml");
	

}
function createTask1($level = '',$doc_id = '',$comment = '',$uid = '',$assignedbyuid = '',$Is_escalation = '',$writ_level = '')
{
	$tasksql = "INSERT INTO tbl_workflow_task (level, doc_id, comment, uid, assignedbyuid, Is_escalation, writ_level) VALUES ($level,$doc_id, '".$comment."','".$uid."','".$assignedbyuid."','".$Is_escalation."','".$writ_level."')";
	if(!db_query($tasksql))
		return 1;
	else
		return 0;
}
function createMail1($module = '',$to = '',$cc = '',$parameter = '',$attachment = '',$from = '')
{  
	global $emailObj;
	$emailObj = simplexml_load_file("email_config.xml");
	$bcc = '';
	$from_name = '';
	$to_name = '';
	if(!$from){
		$from = variable_get('site_mail',$default);
	}
	$fieldstr = "subject, body, emailfrom, emailto, cc, bcc, attachment, from_name, to_name, priority";
	foreach($emailObj->children() as $node => $child)
	{
		
		if($child[0]['name'] == $module)
		{
			foreach($child->children() as $nchild)
			{
			  	
				if($nchild[0]['id'] == 'Body')
				{
					$body = $nchild;
				}
				if($nchild[0]['id'] == 'Subject')
				{
					$subject = $nchild;
				}
				if($nchild[0]['id'] == 'Prority')
				{
					$priority = $nchild;
				}
			}
			
			if($parameter)
			{
				$parameterarr = json_decode($parameter,true);
				for($i = 0; $i < count($parameterarr); $i++){
					$body = str_replace("{".$i."}", $parameterarr[$i], $body);
				}	
			}


	
		  

			 $valuestr = "'".$subject."','".$body."','".$from."','".$to."','".$cc."','".$bcc."','".$attachment."','".$from_name."','".$to_name."','".$priority."'";
			 $sql = "INSERT INTO tbl_email ($fieldstr) VALUES ($valuestr)";
			if(!db_query($sql)){
				return 0;
			}else{
				return 1;
            }
		}
	}
}


function getRole1($uid){
   $sqlrole = "select * from users_roles where uid='".$uid."'";
  $res = db_query($sqlrole);
  $rs = db_fetch_object($res);

   return $rs->rid;
}

function getLoanDM($accountno){

  $sql ="select corp_branch from tbl_loanee_detail where account_id='".$accountno."'";
$res = db_query($sql);
$rs = db_fetch_object($res);
  $branch = $rs->corp_branch;

 $hsql = "select program_uid from tbl_joinings where current_officeid='".$branch."'";
$hres = db_query($hsql);
while($hrs = db_fetch_object($hres)){

	if(getRole1($hrs->program_uid)==13){

	 	$dmuid = $hrs->program_uid;
		}
	}

	return $dmuid;

}

/**  ROLE LIST

Workflow name : Arrear of Land Revenue (ALR) Recovery   workflowid of ALR = 10

DM Est (HOD Est) (13)               Level  1   
Hod Loans (18)        Level  2
GM(19)              Level  3
MD(6)			     Level  4
DRO(22)		     Level  5
Dealing Hand(37)    Level  6



DM => Hod Loans => GM => MD => DRO => Dealing Hand


//Approved   20
//Reject     21
//query      22
//l approved 23
//q reply 0 level  24
//q reply other 25


Table   tbl_loanee_detail
alr_status = 0 you can proceed this account for alr
alr_status = 1 on alr 
alr_status = 2 alr successfully approved


user list hodloan => hodloan, dmloan=>dmloan,gmloan=>gmloan,mdloan=>mdloan,droloan=>droloan,dealinhloan => dealinhloan

**/






/**
*@hook_menu
*/

function alr_menu(){
   
  
  $items['workflowpending'] = array(
          'title' => 'All Pending Task',
	      'page callback' => 'workflowpending',
	      'type' => MENU_NORMAL_ITEM,
	      'access arguments' => array('access content'),
  );

    $items['pendingdetails/%'] = array(
          'title' => 'Pending Details',
	      'page callback' => 'pendingdetails',
	      'type' => MENU_NORMAL_ITEM,
		  'page arguments' => array(1),
	      'access arguments' => array('access content'),
  );
  //pendingdetails
  
  $items['alr'] = array(
          'title' => 'Arrear of Land Revenue (ALR) Recovery',
	      'page callback' => 'alr',
	      'type' => MENU_NORMAL_ITEM,
	      'access arguments' => array('access content'),
  );
  //viewdetails

$items['viewdetails/%'] = array(
	'title' => 'View Details',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'viewdetails',
	'page arguments' => array(1),
	'access arguments' => array('access content'),
	
);

//allalrilst
  $items['allalrilst'] = array(
          'title' => 'Arrear of Land Revenue (ALR) Recovery List',
	      'page callback' => 'allalrilst',
	      'type' => MENU_NORMAL_ITEM,
	      'access arguments' => array('access content'),
  );
   $items['alr_pending'] = array(
          'title' => 'Arrear of Land Revenue (ALR) Recovery  (Pending)',
	      'page callback' => 'alr_pending',
	      'type' => MENU_NORMAL_ITEM,
	      'access arguments' => array('access content'),
  );
 
  $items['action_arl/%/%/%/%'] = array(
          'title' => 'Arrear of Land Revenue (ALR) Recovery  (Action)',
	      'page callback' => 'action_arl',
	      'type' => MENU_NORMAL_ITEM,
	      'page arguments' => array(1,2,3,4),
	      'access arguments' => array('access content'),
  ); 


//commnet

$items['allcomments/%'] = array(
	'title' => 'All Comments',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'allcomments',
	'page arguments' => array(1),
	'access arguments' => array('access content'),
	
);

$items['allco/%'] = array(
	'title' => 'Comment List',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'alr_comment_list_page',
	'page arguments' => array(1),
	'access arguments' => array('access content'),
	
);

$items['alr_comment-search-list/%/%'] = array(
	'title' => 'Search Comment',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'alr_comment_search_page',
	'page arguments' => array(1,2),
	'access arguments' => array('access content'),

);

$items['alr_comment-reply-form/%/%/%'] = array(
	'title' => 'Comment Reply',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'alr_comment_creply_page',
	'page arguments' => array(1,2,3),
	'access arguments' => array('access content'),

);


$items['alr_send-comment/%/%'] = array(
	'title' => 'Send Comment',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'alr_send_comment_page',
	'page arguments' => array(1,2),
	'access arguments' => array('access content'),
	
);
	$items['alr_pending-comment-list'] = array(
	'title' => 'Pending Comment List',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'alr_pending_comment_page',
	//'page arguments' => array(1,2),
	'access arguments' => array('access content'),

);



$items['alrtasksearch'] = array(
	'title' => 'ALR Task Search',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'alrtasksearch',
	'access arguments' => array('access content'),

);

$items['accountdetails/%/%'] = array(
	'title' => 'Account Details',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'accountdetails',
	'page arguments' => array(1,2),
	'access arguments' => array('access content'),
	
);
//getloanview($lid)
  return $items;
}


function accountdetails($account_id,$doc_id){
  
  	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	$breadcrumb[] = l('All Comments', 'allcomments/'.$doc_id);
	$breadcrumb[] = l('Account Details', 'accountdetails/'.$account_id.'/'.$doc_id);
   drupal_set_breadcrumb($breadcrumb);
   
  // return getalrview($account_id);
  return getloanview(getLoanId($account_id));
 /* $query = "SELECT  tbl_loan_detail.scheme_name,tbl_loan_detail.project_cost,tbl_loan_detail.loan_requirement,tbl_loan_detail.work_place,tbl_loan_detail.loan_amount,tbl_loan_detail.reg_number,tbl_loan_detail.application_date,tbl_loan_detail.application_date,tbl_loan_detail.physical_verification_date,tbl_loan_detail.sanction_date,tbl_loan_detail.aggrement_date,tbl_loan_detail.licenseno,tbl_loan_detail.licenseexpiry,tbl_loan_detail.loan_status,tbl_loan_detail.agreement,tbl_loan_detail.documents, 
	
	tbl_loanee_detail.account_id,	tbl_loanee_detail.fname,tbl_loanee_detail.lname,tbl_loanee_detail.fh_name,tbl_loanee_detail.dob,tbl_loanee_detail.gender,tbl_loanee_detail.education,tbl_loanee_detail.religion,tbl_loanee_detail.category,	tbl_loanee_detail.caste,tbl_loanee_detail.disability,tbl_loanee_detail.family_income,tbl_loanee_detail.income_cat,tbl_loanee_detail.UID,tbl_loanee_detail.email,tbl_loanee_detail.	mobile,	tbl_loanee_detail.landline,tbl_loanee_detail.address_type,tbl_loanee_detail.address1,tbl_loanee_detail.village,	tbl_loanee_detail.post_office,	tbl_loanee_detail.district,tbl_loanee_detail.tehsil,	tbl_loanee_detail.block,tbl_loanee_detail.panchayat,tbl_loanee_detail.pincode,	tbl_loanee_detail.corp_branch,
tbl_tehsil.tehsil_name,
tbl_cast.cast_name,
tbl_district.district_name,
tbl_block.block_name,
tbl_panchayt.panchayt_name,
tbl_schemenames.schemeName_name,
tbl_corporations.corporation_name,
tbl_guarantor_detail.gname,tbl_guarantor_detail.gamount,tbl_guarantor_detail.unit_name,tbl_guarantor_detail.gtype,	tbl_guarantor_detail.gnature,	tbl_guarantor_detail.basic_pay,tbl_guarantor_detail.total_pay,tbl_guarantor_detail.address,tbl_guarantor_detail.designation,tbl_guarantor_detail.superannuation_date
	 
	 FROM tbl_loanee_detail 
	INNER JOIN tbl_loan_detail ON  (tbl_loanee_detail.reg_number=tbl_loan_detail.reg_number)
	INNER JOIN tbl_tehsil ON  (tbl_loanee_detail.tehsil=tbl_tehsil.tehsil_id) 
    INNER JOIN tbl_cast ON  (tbl_loanee_detail.caste=tbl_cast.cast_id) 
	INNER JOIN tbl_district ON  (tbl_loanee_detail.district=tbl_district.district_id) 
	INNER JOIN tbl_block ON  (tbl_loanee_detail.block=tbl_block.block_id)
	LEFT OUTER  JOIN tbl_panchayt ON  (tbl_loanee_detail.panchayat=tbl_panchayt.panchayt_id)
    INNER JOIN tbl_schemenames ON  (tbl_loan_detail.scheme_name=tbl_schemenames.schemeName_id)
	 INNER JOIN tbl_corporations  ON  (tbl_loanee_detail.corp_branch=tbl_corporations.corporation_id)
	 LEFT OUTER JOIN tbl_guarantor_detail  ON  (tbl_loanee_detail.loanee_id=tbl_guarantor_detail.loanee_id)
	 where tbl_loanee_detail.account_id ='".$account_id."' ";
	$res = db_query($query);
	$row = db_fetch_object($res);
		
		function getemptyloan($val)
		{
		if($val != '')
		  {
		  return $val;
		  }
		  else
		  {
		  return 'NA';
		  }
		}
			
		
		
		
		$output = <<<EOD
 	
EOD;

    $path = $_SERVER['DOCUMENT_ROOT']."sites/default/files/loan/loanee/"; 	
	$gender=getLookupName($row->gender);
	$caste=getLookupName($row->caste);
	$addtype=getLookupName($row->address_type);
	$religion=getLookupName($row->religion);
	$category=getLookupName($row->category);
	$gtype=getLookupName($row->gtype);
	$gnature=getLookupName($row->gnature);
	$income=getLookupName($row->income_cat);
	$income=getLookupName($row->income_cat);
	
	global $base_url;
	$fileurl = $base_url.'/sites/default/files/loan/loanee/';
	
		$output .='<table >';
		$output .='<tr class="oddrow"><td align="center" colspan="2"><h2>View Loan</h2></td></tr>';
		$output .='</table ><BR>';
		$output .='<table >';
		$output .='<tr class="oddrow"><td align="center" colspan="4"><h2>Personal Detail</h2></td></tr>';
		$output .='<tr class="evenrow" width="25%"><td>First Name</td><td width="25%" class="normal">'.getemptyloan($row->fname).'</td><td width="25%">Last Name</td><td width="25%" class="normal">'.getemptyloan($row->lname).'</td></tr>';
		$output .='<tr class="oddrow"><td>Father/Husband Name</td><td class="normal">'.getemptyloan($row->fh_name).'</td><td >Reg No.</td><td class="normal">'.getemptyloan($row->reg_number).'</td></tr>';

		$output .= '<tr class="evenrow"><td>Date of Birth</td><td class="normal">'.getemptyloan($row->dob).'</td><td>Gender</td><td class="normal">'.getemptyloan($gender).'</td></tr>';
		$output .='<tr class="oddrow"><td>Education</td><td class="normal">'.getemptyloan($row->education).'</td><td>Disability</td><td class="normal">'.getemptyloan($row->disability).'</td></tr>';
		$output .='<tr class="evenrow"><td>Category</td><td class="normal">'.getemptyloan($category).'</td><td>Annual Family Income</td><td class="normal">'.getemptyloan($row->family_income).'</td></tr>';
		$output .='<tr class="oddrow"><td>Income Category</td><td class="normal">'.getemptyloan($income).'</td><td>Religion</td><td class="normal">'.getemptyloan($religion).'</td></tr>';
		$output .='<tr class="evenrow"><td>Caste</td><td class="normal">'.getemptyloan($row->cast_name).'</td><td>UID(Adhar Card No.)</td><td class="normal">'.getemptyloan($row->UID).'</td></tr>';
		$output .='<tr class="oddrow"><td>Email</td><td class="normal">'.getemptyloan($row->email).'</td><td>Mobile</td><td class="normal">'.getemptyloan($row->mobile).'</td></tr>';
			$output .='</table ><BR>';
			
		$output .='<table >';
		$output .='<tr class="oddrow"><td align="center" colspan="4"><h2>Address Detail</h2></td></tr>';
		$output .='<tr class="oddrow"><td width="25%">Address Type</td><td width="25%" class="normal">'.getemptyloan($addtype).'</td><td width="25%">Village</td><td width="25%" class="normal">'.getemptyloan($row->village).'</td></tr>';
		$output .='<tr class="evenrow"><td>Post Office</td><td class="normal">'.getemptyloan($row->post_office).'</td><td>District</td><td class="normal">'.getemptyloan($row->district_name).'</td></tr>';
		$output .='<tr class="oddrow"><td>Tehsil</td><td class="normal">'.getemptyloan($row->tehsil_name).'</td><td>Block</td><td class="normal">'.getemptyloan($row->block_name).'</td></tr>';
		$output .='<tr class="evenrow"><td>Panchayat</td><td class="normal">'.getemptyloan($row->panchayt_name).'</td><td>Pincode</td><td class="normal">'.getemptyloan($row->pincode).'</td></tr>';		
		$output .='</table ><BR>';
		
		$output .='<table >';
		$output .='<tr class="oddrow"><td align="center" colspan="4"><h2>Project Detail</h2></td></tr>';
		$output .='<tr class="oddrow"><td width="25%">Scheme</td><td width="25%" class="normal">'.getemptyloan($row->schemeName_name).'</td><td width="25%">Project Cost</td><td width="25%" class="normal">'.getemptyloan($row->project_cost).'</td></tr>';
		$output .='<tr class="evenrow"><td>Branch Office</td><td class="normal">'.getemptyloan($row->corporation_name).'</td><td>Place of Work</td><td class="normal">'.getemptyloan($row->work_place).'</td></tr>';
		$output .='<tr class="oddrow"><td>Loan Amount</td><td class="normal">'.getemptyloan($row->loan_amount).'</td><td>Loan Requirement</td><td class="normal">'.getemptyloan($row->loan_requirement).'</td></tr>';
	$output .='</table ><BR>';
	
		$output .='<table >'; 
		$output .='<tr class="oddrow"><td align="center" colspan="4"><h2>Guarantor Detail</h2></td></tr>';
	    $output .='<tr class="oddrow"><td width="25%">Guarantor Type</td><td class="normal" width="25%">'.getemptyloan($gtype).'</td><td width="25%">Nature of Guaranty </td><td width="25%" class="normal">'.getemptyloan($gnature).'</td></tr>';
		$output .='<tr class="evenrow"><td>Guarantor Name</td><td class="normal">'.getemptyloan($row->gname).'</td><td>Amount of Guaranty</td><td class="normal">'.getemptyloan($row->gamount).'</td></tr>';
		$output .='<tr class="oddrow"><td>Name of Unit</td><td class="normal">'.getemptyloan($row->unit_name).'</td><td>Basic Pay</td><td class="normal">'.getemptyloan($row->basic_pay).'</td></tr>';
		$output .='<tr class="evenrow"><td>Total Pay</td><td class="normal">'.getemptyloan($row->total_pay).'</td><td>Superannuation Date</td><td class="normal">'.getemptyloan($row->superannuation_date).'</td></tr>';
		$output .='<tr class="oddrow"><td>Address </td><td class="normal">'.getemptyloan($row->address).'</td><td>Designation</td><td class="normal">'.getemptyloan($row->designation).'</td></tr>';
		$output .='</table ><BR>';
		
		$output .='<table >'; 
		$output .='<tr class="oddrow"><td align="center" colspan="4"><h2>Other Details</h2></td></tr>';
		$output .='<tr class="evenrow"><td width="25%">License No.</td><td lass="normal" width="25%">'.getemptyloan($row->licenseno).'</td><td width="25%">Expiry Date</td><td class="normal" width="25%">'.getemptyloan($row->licenseexpiry).'</td></tr>';
		$output .='<tr class="oddrow"><td colspan="2">Document Required</td><td class="normal" colspan="2"><a href="'.$fileurl.getemptyloan($row->documents).'" target="_blank">Download here</a></td></tr>';

	
		
		
		
		$output .='<tr class="evenrow"><td colspan="4" align="center">
	<input type="hidden" value="Bank" name="loan_typetext" id="loan_typetextid">
	<input type="button" class="form-submit" value="Back" id="back" name="back" onClick="history.back(-1)"/>

	</td></tr>';
	
		
		
	
	$output .='
	
	</table>';
	
	return $output;*/
}

function alrtasksearch(){
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('Search Alr', 'alrtasksearch');
	drupal_set_breadcrumb($breadcrumb);
  return drupal_get_form('alrtasksearch_form');
}




function workflowpending(){
    global $user;
global $base_url;
$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Workflow', 'workflowpending');

	drupal_set_breadcrumb($breadcrumb);
	
  $limit = (int)getMessage('listpworkflow', 'code04', NULL);

  $header = array(
		array('data' => t('S. No.')),
        array('data' => t('Workflow Name'), 'field' => 'w.workflow_name', 'sort' => 'asc'),
	    array('data' => t('Task Current Date'), 'field' => 'wt.task_date', 'sort' => 'asc'),
		array('data' => t('Task Current Role'), 'field' => 'wdetail.role', 'sort' => 'asc'),
		array('data' => t('Action'),'class' => 'addeditviewlarge',),
	);
	



   /*	$pendingloansql = "SELECT wt.doc_id, wdetail.role AS role, task_date AS task, wt.level
LEVEL , workflow_name, home_url
FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_workflow_details wdetail
WHERE wt.doc_id = wd.doc_id
AND wd.workflow_id = wdetail.workflow_id
AND wdetail.workflow_id = w.workflow_id
AND wdetail.role !=0
AND wdetail.level = wt.level
AND wt.status =0
GROUP BY wt.doc_id ORDER BY workflow_name DESC"; */
$i=1;



if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
     $val = '%'.strtoupper($_REQUEST['searchtext']).'%'; $val=addslashes($val);	 
	 
	  $query = "SELECT wt.doc_id, wdetail.role AS role, wt.task_date AS task, wt.level
LEVEL , workflow_name, home_url
FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_workflow_details wdetail
WHERE wt.doc_id = wd.doc_id
AND wd.workflow_id = wdetail.workflow_id
AND wdetail.workflow_id = w.workflow_id
AND wdetail.role !=0
AND wdetail.level = wt.level
AND wt.status =0 
AND UPPER(workflow_name) LIKE '".$val."' 
OR UNIX_TIMESTAMP(task_date) = '".strtotime($_REQUEST['searchtext'])."'
GROUP BY wt.doc_id " .tablesort_sql($header); 
	 
$sqlcount1 = "SELECT COUNT(*) AS count  FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_workflow_details wdetail
WHERE wt.doc_id = wd.doc_id
AND wd.workflow_id = wdetail.workflow_id
AND wdetail.workflow_id = w.workflow_id
AND wdetail.role !=0
AND wdetail.level = wt.level
AND wt.status =0 AND UPPER(workflow_name) LIKE '".$val."'
GROUP BY wt.doc_id ";
	$count=0;
	$rscount1 = db_query($sqlcount1);
	while($rscounter1 = db_fetch_object($rscount1)){
	  $count1++;
	}
	 $_REQUEST['page']=0;

 }else{
    $query = "SELECT wt.doc_id, wdetail.role AS role, task_date AS task, wt.level
LEVEL , workflow_name, home_url
FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_workflow_details wdetail
WHERE wt.doc_id = wd.doc_id
AND wd.workflow_id = wdetail.workflow_id
AND wdetail.workflow_id = w.workflow_id
AND wdetail.role !=0
AND wdetail.level = wt.level
AND wt.status =0
GROUP BY wt.doc_id ".tablesort_sql($header);
 }
$count_query = "SELECT COUNT(*) FROM (" . $query . ") AS count_query";

//   $res = db_query($pendingloansql);
  //$output ='<table><tr><th>S. No</th><th>Workflow Name</th><th>Task Date</th><th>Task Current Role</th></tr>';
  // while($rs = db_fetch_object($res)){
      
      //$output .='<tr><td>'.$i.'</td><td>'.$rs->workflow_name.'</td><td>'.date('d-m-Y',strtotime($rs->task)).'</td><td>'.rolename($rs->role).'</td></tr>';
	  //$i++;
   //}
 //$output .='</table>';


//getCorporationBranch($uid);
global $base_url;
 $action = $base_url.'/workflowpending';

 $output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'listofalr', 'code03', array("0"=>$count1)))." | ".l('View All','workflowpending');
	}
	
	$output .='</td><td colspan="3" class="tblHeaderRight" align="center"></td></tr>';
	
	//$addurl = l(getMessage( 'listpworkflow', 'code01', NULL),"alr");
   	$lising = getMessage( 'listpworkflow', 'code02', NULL);
	
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight"><input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';

	$result = pager_query($query, $limit, 0, $count_query);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		
		$viewurl = l("View History","pendingdetails/".$row->doc_id,array('attributes' => array('target'=>'_blank')));
		
	
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => $row->workflow_name),
			array('data' => date('d-m-Y',strtotime($row->task))),
			array('data' => rolename($row->role)),
			array('data' => $viewurl),
		);
	}
	
if($rows== NULL)
	$header=NULL;
	
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	
	return $output;




}

function pendingdetails($doc_id){
	
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Workflow', 'workflowpending');
    // $breadcrumb[] = l('Details', 'pendingdetails');
	drupal_set_breadcrumb($breadcrumb);
	$output .= '<table cellpadding="2" cellspacing="1" border="0" id="wrapper"><tr><td class="tblHeaderLeft">Details</td></tr></table>';
	$query = "SELECT wt.doc_id, wdetail.role AS role, task_date AS task, wt.level
	LEVEL , workflow_name, home_url
	FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_workflow_details wdetail
	WHERE wt.doc_id = wd.doc_id
	AND wd.workflow_id = wdetail.workflow_id
	AND wdetail.workflow_id = w.workflow_id
	AND wdetail.role !=0
	AND wdetail.level = wt.level
	AND wt.doc_id='".$doc_id."'";
	$res = db_query($query);
	$header = array(
		array('data' => t('S. No.')),
        array('data' => t('Workflow Name'), 'field' => 'w.workflow_name', 'sort' => 'asc'),
	    array('data' => t('Task Current Date'), 'field' => 'tbl_workflow_task.task', 'sort' => 'asc'),
		array('data' => t('Task Current Role'), 'field' => 'wdetail.role', 'sort' => 'asc'),
		
	);
	$result = db_query($query);
	$counter =0;
	while($row = db_fetch_object($res)){
		$counter++;
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => $row->workflow_name),
			array('data' => date('d-m-Y',strtotime($row->task))),
			array('data' => rolename($row->role)),
		
		);
         
	}
	return $output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);

}

function task_start_date(){
  // $sql = "select 
}

/** 
* alr list
*/

function allalrilst(){
   global $user;
global $base_url;
$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of ALR', 'allalrilst');

	drupal_set_breadcrumb($breadcrumb);
$limit = (int)getMessage( 'listofalr', 'code04', NULL);

  $header = array(
		array('data' => t('S. No.')),
        array('data' => t('Account No.'), 'field' => 'account_number', 'sort' => 'asc'),
		array('data' => t('Time Stamp'), 'field' => 'timestamp', 'sort' => 'asc'),
		array('data' => t('Action'),'class' => 'addeditviewlarge',),
	);
	
	$breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
   
    if($array[0] == '' ) {
     $breadcrumb[] = l('List of ALR', 'allalrilst');
	 }  
	 drupal_set_breadcrumb($breadcrumb);
   
    if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
     $val = '%'.strtoupper($_REQUEST['searchtext']).'%'; $val=addslashes($val);	 
	 
	 $query = "SELECT  account_number,doc_id, timestamp FROM tbl_alr   where UPPER(account_number) LIKE '".$val."' OR timestamp LIKE '".strtotime($val)."' and status=0"  .tablesort_sql($header);
	 
	$sqlcount = "SELECT COUNT(*) AS count  FROM tbl_alr  where UPPER(account_number) LIKE '".$val."' OR timestamp LIKE '".strtotime($val)."' and status=0";  
	
	$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
	 $_REQUEST['page']=0;

 }else{
    $query = "SELECT  account_number,doc_id, timestamp FROM tbl_alr where  status=0" .tablesort_sql($header);
 }
 
 global $base_url;
 $action = $base_url.'/allalrilst';

 $output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
	$output .= t(getMessage( 'listofalr', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','allalrilst');
	}
	//$output .= " ".l('Create ALR','alr');
	$output .='</td><td colspan="3" class="tblHeaderRight" align="center"></td></tr>';
	
	$addurl = l(getMessage( 'listofalr', 'code01', NULL),"alr");
   	$lising = getMessage( 'listofalr', 'code02', NULL);
		
  if(getRole1($user->uid) == 13){
    $addurl = l(getMessage( 'listofalr', 'code01', NULL),"alr");
  }else{
    $addurl="";
  }


	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight"><input type="text" name="searchtext" value="'.$_POST['searchtext'].'" />
	<input type="submit" name="search" value="Search" /></td>
	</tr>
	</table></form>';

	$result = pager_query($query, 10);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($row=db_fetch_object($result)) {
		$counter++;
		
		$viewurl = l("View","viewdetails/".$row->account_number);
		$comments = l('Comments','allcomments/'.$row->doc_id,array('attributes' => array('target'=>'_blank')));
		$details = l('Account Detail','accountdetails/'.$row->account_number.'/'.$row->doc_id,array('attributes' => array('target'=>'_blank')));
	   //accountdetails/'.getAccountN($doc_id).'/'.$doc_id
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => $row->account_number),
			array('data' => date('d-m-Y',$row->timestamp)),
			array('data' => $viewurl. ' | ' .$comments. ' | '.$details),
		);
	}
	
if($rows== NULL)
	$header=NULL;
	
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	$output .= theme('pager', NULL, $limit,0 );
	
	return $output;
}


function viewdetails($account_number){
    $breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of ALR', 'allalrilst');
	$breadcrumb[] = l('Details', 'viewdetails/'.arg(1));
	drupal_set_breadcrumb($breadcrumb);
	global $base_url;
   //allalrilst
   $sql = "select * from tbl_writ where account_number='".$account_number."'";
   $res = db_query($sql);
   $i=1;
   $output.='<table id="wrapper"><tr><td class="tblHeaderLeft">View ALR</td></tr></table>';
   $output .='<table><tr><th>S. No.</th><th>Account No.</th><th>ALR Send Date</th><th>Due Date</th><th>Attached Documents</th><th>Status</th></tr>';
   while($rs = db_fetch_object($res)){
    
	if($i%2==0){
		$cl = 'even';
		}
		else{
			$cl = 'odd';
			}
		  
	  if($rs->documents){
	    $file = l('Download',$base_url.'/'.$rs->documents,array('attributes' => array('target'=>'_blank')));
	  }else{
	    $file ='NA';
	  }

      if($rs->status == 'writ'){
	     $status = 'Writ Send';
	  }else if($rs->status == 'summons'){
	     $status = 'Summons Send';
	  }else if($rs->status == 'amapp_property'){
	      $status = 'Movable property Send';
	  }else if($rs->status == 'sale'){
	     $status = 'Sale statement is send';
	  }else if($rs->status == 'warrant'){
	     $status = 'Warrant Issued';
	  }else if($rs->status == 'transferred'){
	     $status= "Property is transferred";
	  }
	  else if($rs->status == 'iamapp_property'){
	      $status = 'Immovable property Send';
	  }
	  if($rs->due_date){
	    $duedate = date('d-m-Y',$rs->due_date);
	  }else{
	    $duedate ='NA';
	  }
      
	  $output .='<tr class="'.$cl.'"><td>'.$i.'</td><td>'.$account_number.'</td><td>'.date('d-m-Y',$rs->current_time).'</td><td>'.$duedate.'</td><td>'.$file.'</td><td>'.$status.'</td></tr>';
	  $i++;
   } 
   $output .='</table>';
   return $output;
}


/**
 *@alr function
 */

 function alr(){
    $breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of ALR', 'allalrilst');
	 $breadcrumb[] = l('Create ALR', 'alr');
	drupal_set_breadcrumb($breadcrumb);

   $output ="";
   $output .='<form method="post" action=""><table><tr>';
   $output .='<td><b>Loan Account No.</b><input type="text" name="account"> Is ALR <select name="isalr" />
   <option value="">--select--</option>
   <option value="1">Yes</option>
   <option value="0">No</option>
   </select>
   </td><td><input type="submit" name="alrsub" value="Go" /></td>';
  $output .='</tr></table></form>';
  return drupal_get_form('alr_form');

 }


function alr_form(){

  $form['account'] = array(
     '#type' => 'textfield',
	 '#title' => '',
  );
  $form['isalr'] = array(
     '#type' => 'select',
	 '#title' => '',
     '#default_value' =>1,
	 '#options' => array('1'=>'Yes','0'=>'No')
  ); 
  $form['submit'] = array('#type' => 'submit','#value'=>'Go');
 return $form;
}

function alr_form_validate($form,&$form_state){
  $values = $form_state['values'];
  //echo '<pre>';
   // print_r($values);
	//exit;

 if($values['isalr'] == 0){
   form_set_error('isalr','We are unable to proceed your request..');
 }

  $sql = "select account_id  from tbl_loanee_detail where alr_status=0 and account_id='".$values['account']."'";
  $res = db_query($sql);
  if($rs = db_fetch_object($res)){
  
  }else{
    form_set_error('account','Account No. '.$values['account'].' is invalid or running for ALR. Please eneter another account number.');
  }
}


function alr_form_submit($form,&$form_state){
     $values = $form_state['values'];
   	 $time = time();
	 global $user;
	
	  $corp_branch  = getCorporationBranch($user->uid);
	 db_query("insert into tbl_workflow_docket (workflow_id,time,corp_branch) values (10,'".$time."','".$corp_branch."')");
	 $doc_id = db_last_insert_id('tbl_workflow_docket', 'doc_id');

    $sqlsmsalr=db_query("select * from tbl_loanee_detail account_id = '".$values['account']."'");
	$smsquery=db_fetch_object($sqlsmsalr);
	
	$smsmobile=$smsquery->mobile;
	$sms='91'.$smsmobile;
	
	$message='An  ALR Has been filed against your loan Account No:.'.$values['account'];
	customsendsms($sms,$message);
	
  //send sms

	//insertion in task table

	//db_query("insert into {tbl_workflow_task} (level,status,comment,doc_id) VALUES ('2',0,'','".$doc_id."')");
    global $user;
	$assignedbyuid = $user->uid;
    $doc_id =$doc_id; 
	$level = '2';
    createTask1($level ,$doc_id,$comment,$uid,$assignedbyuid,$Is_escalation,$writ_level);
    
    /*
	 DM Est (HOD Est) (13)               Level  1   
     Hod Loans (18)        Level  2
     GM(19)              Level  3
     MD(6)			     Level  4
	*/
    $sqlh = "select uid from users_roles where rid=18";
	$resh = db_query($sqlh);
	$rsh = db_fetch_object($resh);
	$huser = user_load($rsh->uid);

   $parameter = json_encode(array(0=>$huser->name,1=>$values['account']));
	
    createMail1('alr_mail_forward', $email,'',$parameter,'');

	//insertion in  alr table
	 db_query("insert into {tbl_alr} (doc_id,account_number,uid,timestamp) VALUES ('".$doc_id."','".$values['account']."','".$user->uid."','".$time."')");
	 db_query("update {tbl_loanee_detail} SET alr_status=1 WHERE account_id='".$values['account']."'");
	// drupal_set_message('ALR send successfully for '.$values['account']);

    $output =t(getMessage( 'listofalr', 'code09', array("0"=>$values['account'])));
	drupal_set_message($output);

	 drupal_goto('allalrilst');
}

if(isset($_REQUEST['alrsub'])){

 global $user;
if($_REQUEST['isalr'] == 1){
	 $time = time();
	 global $user;
	 $corp_branch  = getCorporationBranch($user->uid);
	 db_query("insert into tbl_workflow_docket (workflow_id,time,corp_branch) values (10,'".$time."','".$corp_branch."')");
	 $doc_id = db_last_insert_id('tbl_workflow_docket', 'doc_id');

	//insertion in task table

	//db_query("insert into {tbl_workflow_task} (level,status,comment,doc_id) VALUES ('2',0,'','".$doc_id."')");
        global $user;
	$assignedbyuid = $user->uid;
    $doc_id =$doc_id; 
	$level = '2';
    createTask1($level,$doc_id,$comment,$uid,$assignedbyuid,$Is_escalation,$writ_level);
	
	
	
	//insertion in  alr table
	  db_query("insert into {tbl_alr} (doc_id,account_number,uid,timestamp) VALUES ('".$doc_id."','".$_REQUEST['account']."','".$user->uid."','".$time."')");
	 db_query("update {tbl_loanee_detail} SET alr_status=1 WHERE account_id='".$_REQUEST['account']."'");
  }
}

/**
  *@ ALR Pending task

  */

  function alr_pending(){
    $breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	drupal_set_breadcrumb($breadcrumb);
	
	global $user;
	$cuser = user_load($user->uid);
    $roles = @implode(',',@array_flip($cuser->roles));
	$role = getRole1($user->uid);
	 // return "Pending task here";

	//Getting all pending task for logged in user role

     $pendingalrsql = "SELECT wt.doc_id, wt.writ_level,alr.account_number,alr.timestamp,wdetail.level,wt.doc_id FROM tbl_workflow_task wt, tbl_workflow_docket wd, tbl_workflow w, tbl_workflow_details wdetail ,tbl_alr alr  WHERE wt.doc_id = wd.doc_id AND wt.doc_id = alr.doc_id AND wd.workflow_id = wdetail.workflow_id AND wdetail.workflow_id = w.workflow_id AND wdetail.role = '".$role."' AND wdetail.level = wt.level AND wt.status = 0 AND w.workflow_id = 10 GROUP BY alr.doc_id";
   //drupal_set_message($pendingalrsql);
	$pendingalrres = db_query($pendingalrsql);

   //Arrear of Land Revenue (ALR) Recovery  (Pending)

	$output .='<table id="wrapper">';
	$output .='<tr><td class="tblHeaderLeft">Arrear of Land Revenue (ALR) Recovery  (Pending)</td><td align="right">'.l('View All ALR','allalrilst').'</td></tr>';
	$output .='</table>';
	$output .='<table>';
	$output .='<tr><th>S. No.</th><th>Account No.</th><th>ALR Date</th><th>Action</th></tr>';
	$i=0;
	$j=1;
	while($rspending = db_fetch_object($pendingalrres)){
		
		if($j%2==0){
			$cl = 'even';
			}
			else{
				$cl = 'odd';
				}
       $i++;
       
		$qlevel = $rspending->level-1;
		$flevel = $rspending->level+1;
		
      
        
		if($rspending->level == 5){
            $action = l('View','action_arl/view/'.$rspending->account_number.'/'.$rspending->level.'/'.$rspending->doc_id).' | ';
			if($rspending->writ_level == 'writ'){
	         	 $action .= l('Send Writ','action_arl/sent_writ/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';  
	        }else if($rspending->writ_level == 'summons'){
			    $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
		    else if($rspending->writ_level == 'mapp'){
			    $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Attach Movable Property','action_arl/mapp_property/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
            
			else if($rspending->writ_level == 'imapp'){
			   // $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Attach Immovable Property','action_arl/imapp_property/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
			else if($rspending->writ_level == 'sale'){
			   // $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Sent sale statement','action_arl/sale/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
			else if($rspending->writ_level == 'transferred'){
			   // $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Sent property for transferred','action_arl/transferred/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
			else if($rspending->writ_level == 'warrant'){
			   // $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Sent warrant','action_arl/warrant/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
		     $action .= l('Write Comment','allco/'.$rspending->doc_id). ' | ';
			 $action .= l('Close','action_arl/close/'.$rspending->account_number.'/5/'.$rspending->doc_id);
		}else if($rspending->level == 6){
		   $action = l('View','action_arl/view/'.$rspending->account_number.'/'.$rspending->level.'/'.$rspending->doc_id).' | ';
		    if($rspending->writ_level == 'writ'){
	         	 $action .= l('Sent Writ','action_arl/send_writ/'.$rspending->account_number.'/5/'.$rspending->doc_id).' | ';
	        }else if($rspending->writ_level == 'summons'){
			    $action .= l('Sent Summons','action_arl/send_summons/'.$rspending->account_number.'/5/'.$rspending->doc_id).' | ';
			}
			else if($rspending->writ_level == 'mapp'){
			    $action .= l('Attached Movable Property','action_arl/amapp_property/'.$rspending->account_number.'/5/'.$rspending->doc_id).' | ';
			}
			else if($rspending->writ_level == 'imapp'){
			    $action .= l('Attached Immovable Property','action_arl/iamapp_property/'.$rspending->account_number.'/5/'.$rspending->doc_id).' | ';
			}

			else if($rspending->writ_level == 'sale'){
			   // $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Send sale statement to Divisional Commissioner for approval','action_arl/ssale/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
            else if($rspending->writ_level == 'transferred'){
			   // $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Send property','action_arl/stransferred/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
			else if($rspending->writ_level == 'warrant'){
			   // $action .= l('Send Summons','action_arl/sent_summons/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
				$action .= l('Send warrant','action_arl/swarrant/'.$rspending->account_number.'/6/'.$rspending->doc_id).' | ';
			}
			 $action .= l('Write Comment','allco/'.$rspending->doc_id).' | ';
			 $action .= l('Close','action_arl/close/'.$rspending->account_number.'/6/'.$rspending->doc_id);

	    }else if($rspending->level == 1){
		   $action = l('View','action_arl/view/'.$rspending->account_number.'/'.$rspending->level.'/'.$rspending->doc_id).' | ';
		   $action .= l('Forward','action_arl/forward/'.$rspending->account_number.'/'.$flevel.'/'.$rspending->doc_id).' | ';
		    $action .= l('Write Comment','allco/'.$rspending->doc_id);
		}else if($rspending->level == 4){
		   $action = l('View','action_arl/view/'.$rspending->account_number.'/'.$rspending->level.'/'.$rspending->doc_id).' | ';
		   $action .= l('Query','action_arl/query/'.$rspending->account_number.'/'.$qlevel.'/'.$rspending->doc_id).' | ';
		   $action .= l('Reject','action_arl/reject/'.$rspending->account_number.'/'.$flevel.'/'.$rspending->doc_id).' | ';
		   $action .= l('Approved','action_arl/approved/'.$rspending->account_number.'/'.$flevel.'/'.$rspending->doc_id).' | ';
		    $action .= l('Write Comment','allco/'.$rspending->doc_id);
		}else {
		   $action = l('View','action_arl/view/'.$rspending->account_number.'/'.$rspending->level.'/'.$rspending->doc_id).' | ';
		   $action .= l('Query','action_arl/query/'.$rspending->account_number.'/'.$qlevel.'/'.$rspending->doc_id).' | ';
		   $action .= l('Reject','action_arl/reject/'.$rspending->account_number.'/'.$flevel.'/'.$rspending->doc_id).' | ';
		   $action .= l('Forward','action_arl/forward/'.$rspending->account_number.'/'.$flevel.'/'.$rspending->doc_id).' | ';
		    $action .= l('Write Comment','allco/'.$rspending->doc_id);
		}
      if($rspending->account_number){
	     $output .='<tr class="'.$cl.'"><td>'.$i.'</td><td>'.$rspending->account_number.'</td><td>'.date('d-m-Y',$rspending->timestamp).'</td><td>'.$action.'</td></tr>';
      }  
	  $j++; 
	}
  $output .='</table>';
  return $output;
  }


function action_arl($action_type,$account_number,$level,$doc_id){
  /*  
	
DM Est (HOD Est) (13)               Level  1   
Hod Loans (18)        Level  2
GM(19)              Level  3
MD(6)			     Level  4
DRO(22)		     Level  5
Dealing Hand(37)    Level  6
*/
	
	if($action_type == 'view'){
	   return view($doc_id);
	}else if($action_type == 'query'){
       
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	$breadcrumb[] = l('Query', 'action_arl/query/'.arg(2).'/'.arg(3));
    drupal_set_breadcrumb($breadcrumb);
	   
	   $output .='<form method="post" action=""><table>';
	   $output .='<tr><td width="20%"><b>Query : <span style="color:#ff0000;">*</span></b>
	   </td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" /><input type="hidden" name="account_number" value="'.$account_number.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" /></td><td><input type="submit" name="arlsubmitq" value="Query" /></td></tr>';
	  return  $output .='</table></form>';
	}else if($action_type == 'reject'){
	   db_query("delete from {tbl_alr} where account_number ='".$account_number."'");
	   db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."'");
	   db_query("update {tbl_loanee_detail} SET alr_status=0 WHERE account_id='".$account_number."'");
       

       


	   $name = rolename($level);
       $output =t(getMessage( 'listofalr', 'code11', array("0"=>$name,"1"=>$account_number)));
        drupal_set_message("ALR rejected for Account Number ".$account_number);
	   drupal_goto('alr_pending');
	}else if($action_type == 'forward'){
	   $olevel = $level-1;
	   db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level ='".$olevel."'");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level) VALUES (0,'".$doc_id."','".$level."')");
	        global $user;
	$assignedbyuid = $user->uid;
    $doc_id =$doc_id; 
	$level = $level;
    createTask1($level,$doc_id,$comment,$uid,$assignedbyuid,$Is_escalation,$writ_level);

       /*
	 DM Est (HOD Est) (13)               Level  1   
     Hod Loans (18)        Level  2
     GM(19)              Level  3
     MD(6)			     Level  4
	*/
	if($level == 2){
	  $rid = 18;
	}else if($level == 3){
	  $rid = 19; 
	}else if($level == 4){
	  $rid = 6;
	}
    $sqlh = "select uid from users_roles where rid='".$rid."'";
	$resh = db_query($sqlh);
	$rsh = db_fetch_object($resh);
	$huser = user_load($rsh->uid);

    $parameter = json_encode(array(0=>$huser->name,1=>$values['account']));
    createMail1('alr_mail_forward', $email,'',$parameter,'');
       

	   $name = rolename($olevel);
       $output =t(getMessage( 'listofalr', 'code12', array("0"=>$name,"1"=>rolename($level), "2" => $account_number)));
	   drupal_set_message("ALR has been forwarded for Account Number ".$account_number);
	   drupal_goto('alr_pending');




	}else if($action_type == 'approved'){
	   
	   
	    $sqlu = "select tbl_loan_detail.o_principal,tbl_loan_detail.o_interest,tbl_loan_detail.o_LD,tbl_loan_detail.o_other_charges,tbl_loan_detail.last_interest_calculated from 
	   tbl_loan_detail INNER JOIN tbl_loanee_detail ON (tbl_loanee_detail.reg_number=tbl_loan_detail.reg_number) where tbl_loanee_detail.account_id='".$account_number."'";
	   
	   $resu = db_query($sqlu);
	   $rsu = db_fetch_object($resu);
	   db_query("update tbl_alr set o_principal='".$rsu->o_principal."',	o_interest='".$rsu->o_interest."',o_LD='".$rsu->o_LD."',o_other_charges='".$rsu->o_other_charges."',last_interest_calculated='".$rsu->last_interest_calculated."' where account_number='".$account_number."'");
	   db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."'");

             /*
	 DM Est (HOD Est) (13)               Level  1   
     Hod Loans (18)        Level  2
     GM(19)              Level  3
     MD(6)			     Level  4
	*/
	if($level == 2){
	  $rid = 18;
	}else if($level == 3){
	  $rid = 19; 
	}else if($level == 4){
	  $rid = 6;
	}
    $sqlh = "select uid from users_roles where rid=22";
	$resh = db_query($sqlh);
	$rsh = db_fetch_object($resh);
	$huser = user_load($rsh->uid);

    $parameter = json_encode(array(0=>$huser->name,1=>$account_number));
    createMail1('alr_mail_approved', $email,'',$parameter,'');


	   db_query("update {tbl_loanee_detail} SET alr_status=2 WHERE account_id='".$account_number."'");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,'writ')");
           global $user;
	$assignedbyuid = $user->uid;
    $doc_id =$doc_id; 
	$level = '5';
	$writ_level = 'writ';
    createTask1($level,$doc_id,$comment,$uid,$assignedbyuid,$Is_escalation,$writ_level);
       $name = rolename($level);
       $output =t(getMessage( 'listofalr', 'code13', array("0"=>$name,"1" => $account_number)));
       drupal_set_message("ALR has been approved for Account Number ".$account_number);
	   drupal_goto('alr_pending');
	}else if ($action_type == 'sent_writ'){
         $breadcrumb[] = l('Home', '<front>');
        $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	    $breadcrumb[] = l('Writ', 'action_arl/sent_writ/'.arg(2).'/'.arg(3).'/'.arg(4));
		drupal_set_breadcrumb($breadcrumb);
       $output .='<form method="post" action=""><table>';
	   $output .='<tr><td><b>Writ : </b></td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" />
	   </td><td><input type="submit" name="writsubmitq" value="Send" /></td></tr>';
	  return  $output .='</table></form>';
		 
		
       //db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	  // db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	}else if ($action_type == 'sent_summons'){
           $breadcrumb[] = l('Home', '<front>');
        $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	    $breadcrumb[] = l('Summons', 'action_arl/sent_summons/'.arg(2).'/'.arg(3).'/'.arg(4));
		drupal_set_breadcrumb($breadcrumb);
	     $output .='<form method="post" action=""><table>';
	   $output .='<tr><td><b>Summons : </b></td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" />
	   </td><td><input type="submit" name="summonssubmitq" value="Send" /></td></tr>';
	  return  $output .='</table></form>';
	   
	  // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	}
	else if ($action_type == 'sale'){
           $breadcrumb[] = l('Home', '<front>');
        $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	    $breadcrumb[] = l('Sale', 'action_arl/sale/'.arg(2).'/'.arg(3).'/'.arg(4));
		drupal_set_breadcrumb($breadcrumb);
	     $output .='<form method="post" action=""><table>';
	   $output .='<tr><td><b>Remarks : </b></td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" />
	   </td><td><input type="submit" name="salesubmitq" value="Send" /></td></tr>';
	  return  $output .='</table></form>';
	   
	  // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	}
	
   else if ($action_type == 'warrant'){
          $breadcrumb[] = l('Home', '<front>');
        $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	    $breadcrumb[] = l('Warrant', 'action_arl/warrant/'.arg(2).'/'.arg(3).'/'.arg(4));
		drupal_set_breadcrumb($breadcrumb);
	     $output .='<form method="post" action=""><table>';
	   $output .='<tr><td><b>Remarks : </b></td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" />
	   </td><td><input type="submit" name="warrantsubmitq" value="Send" /></td></tr>';
	  return  $output .='</table></form>';
	   
	  // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	}
else if ($action_type == 'transferred'){
               $breadcrumb[] = l('Home', '<front>');
        $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	    $breadcrumb[] = l('Transferred', 'action_arl/transferred/'.arg(2).'/'.arg(3).'/'.arg(4));
		drupal_set_breadcrumb($breadcrumb);
	     $output .='<form method="post" action=""><table>';
	   $output .='<tr><td><b>Remarks : </b></td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" />
	   </td><td><input type="submit" name="transferredsubmitq" value="Send" /></td></tr>';
	  return  $output .='</table></form>';
	   
	  // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	}

	else if ($action_type == 'send_writ'){
      // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =5");
	  // db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 

      return drupal_get_form('sent_form','writ',$doc_id,$account_number);




	}else if ($action_type == 'send_summons'){
      // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =5");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	   return drupal_get_form('sent_form','summons',$doc_id,$account_number);
	}

   else if ($action_type == 'amapp_property'){
      // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =5");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	   return drupal_get_form('sent_form','amapp_property',$doc_id,$account_number);
	}
   else if ($action_type == 'iamapp_property'){
      // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =5");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	   return drupal_get_form('sent_form','iamapp_property',$doc_id,$account_number);
	}
	else if ($action_type == 'mapp_property'){
       $breadcrumb[] = l('Home', '<front>');
        $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	    $breadcrumb[] = l('Movable Property', 'action_arl/mapp_property/'.arg(2).'/'.arg(3).'/'.arg(4));
		drupal_set_breadcrumb($breadcrumb);
	     $output .='<form method="post" action=""><table>';
	   $output .='<tr><td><b>Remarks : </b></td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" />
	   </td><td><input type="submit" name="mapp_property" value="Send" /></td></tr>';
	  return  $output .='</table></form>';
	   
	  // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	}

	else if ($action_type == 'imapp_property'){
           $breadcrumb[] = l('Home', '<front>');
        $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	    $breadcrumb[] = l('Immovable Property', 'action_arl/imapp_property/'.arg(2).'/'.arg(3).'/'.arg(4));
		drupal_set_breadcrumb($breadcrumb);
	     $output .='<form method="post" action=""><table>';
	   $output .='<tr><td><b>Remarks : </b></td><td><TEXTAREA name="query" id="query" onkeypress="return textonlywithdotnemaxquery(event,200);"></TEXTAREA><input type="hidden" name="level" value="'.$level.'" />
	   <input type="hidden" name="doc_id" value="'.$doc_id.'" />
	   </td><td><input type="submit" name="immapp_property" value="Send" /></td></tr>';
	  return  $output .='</table></form>';
	   
	  // db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level)  VALUES (0,'".$doc_id."',5,2)"); 
	}else if($action_type == 'ssale'){
	   $time =strtotime(date('Y-m-d'));
	   db_query("insert into {tbl_writ} (`current_time`,`account_number`,`status`) values('".$time."','".$account_number."','sale')");
	   
	   db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
	             global $user;
	$assignedbyuid = $user->uid;
    $doc_id =$doc_id; 
	$level = '5';
	$writ_level = 'warrant';
    createTask1($level,$doc_id,$comment,$uid,$assignedbyuid,$Is_escalation,$writ_level);
      // db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level) VALUES (0,'".$doc_id."',5,'warrant')");
	   
	   $name = rolename($level);
       $output =t(getMessage( 'listofalr', 'code15', array("0"=>$account_number)));
       drupal_set_message($output);
	   drupal_goto('alr_pending');
	}

	else if($action_type == 'swarrant'){
	   
	     $time =strtotime(date('Y-m-d'));
	   db_query("insert into {tbl_writ} (`current_time`,`account_number`,`status`) values('".$time."','".$account_number."','warrant')");
	   db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
       //db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level) VALUES (0,'".$doc_id."',5,'transferred')");
	             global $user;
	$assignedbyuid = $user->uid;
    $doc_id =$doc_id; 
	$level = '5';
	$writ_level = 'transferred';
    createTask1($level,$doc_id,$comment,$uid,$assignedbyuid,$Is_escalation,$writ_level);
	   $output =t(getMessage( 'listofalr', 'code16', array("0"=>$account_number)));
       drupal_set_message($output);
	   drupal_goto('alr_pending');
	}

	else if($action_type == 'stransferred'){
	      $time =strtotime(date('Y-m-d'));
		  global $user;
	   db_query("insert into {tbl_writ} (`current_time`,`account_number`,`status`) values('".$time."','".$account_number."','transferred')");
		 db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."' AND level =6");
      
        db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level,assignedbyuid) VALUES (0,'".$doc_id."',5,'final','".$user->uid."')");
	    $output =t(getMessage( 'listofalr', 'code17', array("0"=>$account_number)));
        drupal_set_message($output);
	   drupal_goto('alr_pending');
	}
	
	else if($action_type == 'close'){
	      $time =strtotime(date('Y-m-d'));
		  global $user;
	     db_query("insert into {tbl_writ} (`current_time`,`account_number`,`status`) values('".$time."','".$account_number."','close')");
		 db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$doc_id."'");
		      
       db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level,assignedbyuid) VALUES (1,'".$doc_id."','".$level."','final','".$user->uid."')");
		
		           /*
	 DM Est (HOD Est) (13)               Level  1   
     Hod Loans (18)        Level  2
     GM(19)              Level  3
     MD(6)			     Level  4
	*/
	if($level == 2){
	  $rid = 18;
	}else if($level == 3){
	  $rid = 19; 
	}else if($level == 4){
	  $rid = 6;
	}
    $sqlh = "select uid from users_roles where rid=6";
	$resh = db_query($sqlh);
	$rsh = db_fetch_object($resh);
	$huser = user_load($rsh->uid);

    $parameter = json_encode(array(0=>$huser->name,1=>$account_number));
    createMail1('alr_mail_closed', $email,'',$parameter,'');
		
		db_query("update {tbl_loanee_detail} SET alr_status=3 WHERE account_id='".$account_number."'");
        drupal_set_message("ALR has been closed Successfully.");
	   drupal_goto('alr_pending');
	}
	
}

if(isset($_REQUEST['arlsubmitq']) && $_REQUEST['query'] != ''){
  //   
       $olevel = $_REQUEST['level']+1;
	  // echo "update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level ='".$olevel."'";exit;
       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level ='".$olevel."'");
       
	    global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = $_REQUEST['level'];
	$writ_level = '';
	$comment = $_REQUEST['query'];
	$Is_escalation = '';
    //echo getalrview($account_id);
	createTask1($level,$doc_id ,$comment,$uid,$assignedbyuid ,$Is_escalation,$writ_level);
	           /*
	 DM Est (HOD Est) (13)               Level  1   
     Hod Loans (18)        Level  2
     GM(19)              Level  3
     MD(6)			     Level  4
	*/
	if($level == 2){
	  $rid = 18;
	      $sqlh = "select uid from users_roles where rid=18";
	$resh = db_query($sqlh);
	$rsh = db_fetch_object($resh);
	$huser = user_load($rsh->uid);

    $parameter = json_encode(array(0=>$huser->name,1=>$_REQUEST['account_number']));
    createMail1('alr_mail_query', $email,'',$parameter,'');
	}else if($level == 3){
	  $rid = 19; 
	      $sqlh = "select uid from users_roles where rid=19";
	$resh = db_query($sqlh);
	$rsh = db_fetch_object($resh);
	$huser = user_load($rsh->uid);

    $parameter = json_encode(array(0=>$huser->name,1=>$_REQUEST['account_number']));
    createMail1('alr_mail_query', $email,'',$parameter,'');
	}else if($level == 4){
	  $rid = 6;
	      $sqlh = "select uid from users_roles where rid=6";
	$resh = db_query($sqlh);
	$rsh = db_fetch_object($resh);
	$huser = user_load($rsh->uid);

    $parameter = json_encode(array(0=>$huser->name,1=>$_REQUEST['account_number']));
    createMail1('alr_mail_query', $email,'',$parameter,'');
	}else if($level == 1){
	 
	$duid = getLoanDM($_REQUEST['account_number']);
	$huser = user_load($duid);
    
    $parameter = json_encode(array(0=>$huser->name,1=>$_REQUEST['account_number']));
    createMail1('alr_mail_query', $email,'',$parameter,'');
	}



	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,uid) VALUES (0,'".$_REQUEST['doc_id']."','".$_REQUEST['level']."','".$_REQUEST['query']."','".$user->uid."')");
     
   /*
   DM Est (HOD Est) (13)               Level  1   
Hod Loans (18)        Level  2
GM(19)              Level  3
MD(6)			     Level  4
DRO(22)		     Level  5
Dealing Hand(37)    Level  6
   
   */
  
   //if($olevel == 1){
      
   //}
   // $name = rolename($olevel);
	//$output = getMessage( 'listofalr', 'code10', array("0"=>$account_number));
	drupal_set_message("Query has been send successfully.");
	   drupal_goto('alr_pending');
}


if(isset($_REQUEST['mapp_property']) && $_REQUEST['query'] != ''){
  //   
       $olevel = $_REQUEST['level']+1;
	  // echo "update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level ='".$olevel."'";exit;
       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level =5");
       
	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = '6';
	$writ_level = 'mapp';
	$comment = $_REQUEST['query'];
    createTask1($level ,$doc_id,$comment,$uid ,$assignedbyuid ,$Is_escalation ,$writ_level );
	   
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,writ_level,uid) VALUES (0,'".$_REQUEST['doc_id']."',6,'".$_REQUEST['query']."','mapp','".$user->uid."')");
   	  drupal_set_message("Attached Movable Property.");
         //$output =t(getMessage( 'listofalr', 'code18', array("0"=>$account_number,"1"=>"Movable Prperty")));
         //drupal_set-message($output);

	   drupal_goto('alr_pending');
}




if(isset($_REQUEST['immapp_property']) && $_REQUEST['query'] != ''){
  //   
       $olevel = $_REQUEST['level']+1;
	  // echo "update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level ='".$olevel."'";exit;
       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level =5");

   	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = '6';
	$writ_level = 'imapp';
	$comment = $_REQUEST['query'];
    createTask1($level ,$doc_id ,$comment,$uid,$assignedbyuid ,$Is_escalation,$writ_level);

      // db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,writ_level,uid) VALUES (0,'".$_REQUEST['doc_id']."',6,'".$_REQUEST['query']."','imapp','".$user->uid."')");
	    drupal_set_message("Attached Immovable Property.");
	   //drupal_goto('alr_pending');
	   drupal_goto('alr_pending');
}



if(isset($_REQUEST['writsubmitq']) && $_REQUEST['query'] != ''){

       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level =5");
       
	      	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = '6';
	$writ_level = 'writ';
	$comment = $_REQUEST['query'];
    createTask1($level,$doc_id ,$comment ,$uid ,$assignedbyuid,$Is_escalation ,$writ_level );
	   
	//   db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,writ_level,uid) VALUES (0,'".$_REQUEST['doc_id']."',6,'".$_REQUEST['query']."','writ','".$user->uid."')");

	     drupal_set_message("Writ has been send successfully.");
	   drupal_goto('alr_pending');
}

if(isset($_REQUEST['salesubmitq']) && $_REQUEST['query'] != ''){

       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level =5");

	      	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = '6';
	$writ_level = 'sale';
	$comment = $_REQUEST['query'];
    createTask1($level ,$doc_id ,$comment ,$uid ,$assignedbyuid ,$Is_escalation ,$writ_level);

       //db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,writ_level,uid) VALUES (0,'".$_REQUEST['doc_id']."',6,'".$_REQUEST['query']."','sale','".$user->uid."')");
	   drupal_set_message("Sale has been Transferred successfully.");
	   drupal_goto('alr_pending');
}
if(isset($_REQUEST['warrantsubmitq']) && $_REQUEST['query'] != ''){

       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level =5");
     	      	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = '6';
	$writ_level = 'warrant';
	$comment = $_REQUEST['query'];
    createTask1($level,$doc_id ,$comment ,$uid ,$assignedbyuid ,$Is_escalation ,$writ_level );
	  
	  
	  // db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,writ_level,uid) VALUES (0,'".$_REQUEST['doc_id']."',6,'".$_REQUEST['query']."','warrant','".$user->uid."')");
	   
	  drupal_set_message("Warrant has been send successfully.");
       //drupal_set_message($output);
	   drupal_goto('alr_pending');
}
if(isset($_REQUEST['transferredsubmitq']) && $_REQUEST['query'] != ''){

       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level =5");
        	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = '6';
	$writ_level = 'transferred';
	$comment = $_REQUEST['query'];
    createTask1($level,$doc_id ,$comment,$uid ,$assignedbyuid,$Is_escalation,$writ_level);
	  
	  
	  // db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,writ_level,uid) VALUES (0,'".$_REQUEST['doc_id']."',6,'".$_REQUEST['query']."','transferred','".$user->uid."')");
	   
	   //$output = t(getMessage('listofalr', 'code21', array('0'=>'Property Transferred')));
       drupal_set_message("Property has been Transferred successfully.");
	   drupal_goto('alr_pending');
}
if(isset($_REQUEST['summonssubmitq']) && $_REQUEST['query'] != ''){
  
       db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$_REQUEST['doc_id']."' AND level =5");
       
	           	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $_REQUEST['doc_id']; 
	$level = '6';
	$writ_level = 'summons';
	$comment = $_REQUEST['query'];
    createTask1($level,$doc_id ,$comment,$uid ,$assignedbyuid,$Is_escalation,$writ_level );
	   
	   //db_query("insert into {tbl_workflow_task} (status,doc_id,level,comment,writ_level,uid) VALUES (0,'".$_REQUEST['doc_id']."',6,'".$_REQUEST['query']."','summons','".$user->uid."')");
	  // $output = t(getMessage('listofalr', 'code21', array('0'=>'SUMMONS')));
       drupal_set_message("Summons has been send successfully.");
	   drupal_goto('alr_pending');
}




function sent_form($form_state,$staus_name,$doc_id,$account_number){
  
   
   	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	$breadcrumb[] = l('Sent', 'action_arl/'.arg(1).'/'.arg(2).'/'.arg(3));
    drupal_set_breadcrumb($breadcrumb);
	   
  
  $form['#attributes']['enctype'] = 'multipart/form-data';
  
  $form['doc_id'] = array(
	'#type' =>'hidden',
	'#default_value'=> $doc_id,
	);
   
  $form['account_number'] = array(
	'#type' =>'hidden',
	'#default_value'=> $account_number,
	);
    $form['type'] = array(
	'#type' =>'hidden',
	'#default_value'=> $staus_name,
	);

   if($staus_name == 'writ' || $staus_name == 'summons'){
      $form['due_date'] = array(
			'#type' => 'date_popup',
			'#date_format' => 'd-m-Y',
			'#title' => 'Due Date',
			'#required' => TRUE,
			'#size' => '10',
			'#default_value' => $node->date_from,
	 );
   }

   $form['documents'] = array(
			'#type'  => 'file',
			'#title' => 'Upload File',
			'#size' => 30,
		    '#required' => FALSE,
	        '#description' => t('File Format .doc,.xls, .xlsx, .pdf, .zip, .rar'),
  );

 $form['submit'] = array(
   '#type' => 'submit',
   '#value' => 'Send', 	 
 );
  return $form;

}


function alrtasksearch_form(){
 
   $form['writ_level'] = array(
			'#type' => 'select',
			'#title' => '',
			'#required' => FALSE,
		    '#options' => array(''=>'All','writ'=>'Writ','summons'=>'Summons'), 
		
	 );
  $form['date_from'] = array(
			'#type' => 'date_popup',
			'#date_format' => 'd-m-Y',
			'#title' => '',
			'#required' => TRUE,
			'#size' => '10',
		
	 );

   $form['date_to'] = array(
			'#type' => 'date_popup',
			'#date_format' => 'd-m-Y',
			'#title' => '',
			'#required' => TRUE,
			'#size' => '10',
			
	 );

	 $form['submit'] = array(
      '#type' =>'button',
	  '#default_value' =>'Generate Report',
  ); 
  return $form;

}

/**
 *@ hook_theme 
*/

 function alr_theme() {
	
	return array(
		
		'alrtasksearch_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'alrtasksearch_form',
                                 ),
		'alr_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'alr_form',
                                 ),	
		'alr_send_comment_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'alr_send_comment_form',
                                 ),	
			'alr_reply_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'alr_comment_search_form',
                                 ),	
       'sent_form' => array(
								'arguments' => array('form' => NULL),
								'template' => 'sent_form',
                                 ),	
		//alr_send_comment_form	 alr_comment_search_form sent_form
								 
 );
        
}

function sent_form_validate($form, &$form_state) {
	//print_r($form_state['values']);
   $time = time();
  $date = strtotime($form_state['values']['due_date']);
  if($date){
	  if($date < $time){
		form_set_error('due_date','Due Date should be greater than current date.');
	  }//exit;
  }
  $type = $form_state['values']['documents'];
  $exc = strtolower(findexts($_FILES['files']['name']['documents']));
  if($_FILES['files']['name']['documents']){
  // '#description' => t('File Format .doc,.xls, .pdf, .zip, .rar'),
   if($exc == 'doc' || $exc == 'xls' || $exc == 'pdf' || $exc == 'zip' ||  $exc == 'rar' ||  $exc == 'xlsx'){}else{
     form_set_error('documents','Please upload file with valid format..');
   }
  } 
  
 
}

function findexts($filename)
{
return end(explode(".", $filename));
}



function sent_form_submit($form,&$form_state){
    
	$createdon = time();
	$values = $form_state['values'];
	$target_path = "sites/default/files/";
	$extension = findexts($_FILES['files']['name']['documents']);

	if($_FILES['files']['name']['documents']){
		$filename = $createdon.'.'.$extension;
		@chmod("sites/default/files", 0777);
		move_uploaded_file($_FILES['files']['tmp_name']['documents'], $target_path.$filename);
		@chmod($target_path.$filename, 0777);
		$filesize = $_FILES['files']['size']['documents']/1024;
		$filesize .='kb';
		$filename = $target_path.$createdon.'.'.$extension;
    }
    $time = time();

    if($values['type'] == 'writ'){
	  $writ_level = 'summons';
	  $name = 'WRIT';
	  
	  //send sms
	}
	if($values['type'] == 'summons'){
	  
       $name = 'Summons';
	   $writ_level = 'mapp';
	   //send sms


	}
	if($values['type'] == 'amapp_property'){
	  $writ_level = 'imapp';
	  $name = 'Movable property';
	  
	}
	if($values['type'] == 'iamapp_property'){
	  $writ_level = 'sale';
	  
	  $name = 'Immovable property';
	}

	db_query("update {tbl_workflow_task} SET status=1 WHERE doc_id='".$values['doc_id']."' AND level =6");
    
	
	           	       global $user;
	$assignedbyuid = $user->uid;
    $doc_id = $values['doc_id']; 
	$level = '5';
	$writ_level = $writ_level;
    createTask1($level,$doc_id,$comment,$uid ,$assignedbyuid ,$Is_escalation ,$writ_level);
	
	//db_query("insert into {tbl_workflow_task} (status,doc_id,level,writ_level) VALUES (0,'".$values['doc_id']."',5,'".$writ_level."')");
	db_query("insert into {tbl_writ} (`due_date`,`current_time`,`documents`,`account_number`,`status`) values('".strtotime($values['due_date'])."','".$time."','".$filename."','".$values['account_number']."','".$values['type']."')");
	//echo "insert into tbl_writ (due_date,current_time,documents,account_number,status) //values('".$values['due_date']."','".$time."','".$filename."','".$values['account_number']."','".$values['type']."')";exit;

   	  // $name = rolename($level);
       $output =t(getMessage('listofalr', 'code14', array("0"=>$name,"1" => $values['account_number'])));
       drupal_set_message($output);

	drupal_goto('alr_pending');
}

//view


function getAccountN($doc_id){
  $sql = "select account_number  from tbl_alr where doc_id='".$doc_id."'";
  $res = db_query($sql);
  $rs = db_fetch_object($res);
  return $rs->account_number;
}

function view($doc_id){
    
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	$breadcrumb[] = l('View', 'action_arl/view/'.arg(2).'/'.arg(3));
    drupal_set_breadcrumb($breadcrumb);
   
   


   $sql = "select assignedbyuid,comment,uid,task_date from tbl_workflow_task where doc_id='".$doc_id."'";
   $res = db_query($sql);
   $output ='<table id="wrapper"><tr><td class="tblHeaderLeft">'.'View All Query'.'</td><td align="right">'.l('View Account Details','accountdetails/'.getAccountN($doc_id).'/'.$doc_id).' | '.l('Comment(s)','allcomments/'.$doc_id).'</td></tr>';
   $output .='</table>';
   $output .='<table cellpadding="2" cellspacing="1" border="0" id="form-conntainer"><tr><th>Query/ Remarks Date</th><th>Query/Remarks</th><th>Query/Remarks By</th></tr>';
   $i=1;
   while($rs = db_fetch_object($res)){
	   if($i%2==0){
		  $cl = 'odd'; 
		   }
		   else{
		   $cl = 'even';
   }
	   $cuser = user_load($rs->assignedbyuid);
	   $name = $cuser->name;
	   if($rs->comment){
       $output .='<tr class="'.$cl.'"><td>'.date('d-m-Y',strtotime($rs->task_date)).'</td><td>'.$rs->comment.'</td><td>'.$name.'</td></tr>';
	   $i++;
	   }
	   
   }

   return $output .='</table>';
}


function allcomments($doc_id){

      global $user;
	global $base_url;
	global $xpathObj;
	$limit = (int)getMessage('dsjerti_management', 'code04', NULL);
  
  $header = array(
		array('data' => t('S. No.')),
        array('data' => t('Comment Date'), 'field' => 'comment_date', 'sort' => 'asc'),
        array('data' => t('Comment'), 'field' => 'comment', 'sort' => 'asc'),
	    array('data' => t('Commented By'),'field' => 'commentedby', 'sort' => 'asc'),
		array('data' => t('Commented To'),'field' => 'commentedto', 'sort' => 'asc'),
		   
	);
	
	$array = explode(',',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	$breadcrumb[] = l('All Comments', 'allcomments/'.arg(1));
	drupal_set_breadcrumb($breadcrumb);
	
 if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext']!=''){
    $val = '%'.strtoupper($_REQUEST['searchtext']).'%';	 
	$ro=date("Y-m-d",strtotime(substr($_REQUEST['searchtext'],0,10)));
		 	
	 $query = "select * from tbl_loan_comment inner join role r1 on (tbl_loan_comment.commentedby= r1.rid) inner join role r2 on (tbl_loan_comment.commentedto= r2.rid)  where tbl_loan_comment.doc_id='".$doc_id."' and  (tbl_loan_comment.comment like '$val' or  tbl_loan_comment.comment_date like '%".$ro."%' or r1.name like '".$val."' or r2.name like '".$val."')".tablesort_sql($header);
   
   $sqlcount = "select COUNT(*) AS count from tbl_loan_comment inner join role r1 on (tbl_loan_comment.commentedby= r1.rid) inner join role r2 on (tbl_loan_comment.commentedto= r2.rid)  where tbl_loan_comment.doc_id='".$doc_id."' and  (tbl_loan_comment.comment like '$val' or  tbl_loan_comment.comment_date like '%".$ro."%' or r1.name like '".$val."' or r2.name like '".$val."')".tablesort_sql($header);
		$rscount = db_query($sqlcount);
	$rscounter = db_fetch_object($rscount);
	$_REQUEST['page']=0;
	}else{
  $query = "select * from tbl_loan_comment where doc_id='".$doc_id."'".tablesort_sql($header);
  
	}
 
  global $base_url;
$action = $base_url.'/allcomments'.'/'.$doc_id;
 $output = '<form method="post" action="'.$action.'"><table width="100%" border="0" cellspacing="1" cellpadding="1" id="wrapper">
	<tr><td colspan="3" class="searchrecord">';
	if(isset($_REQUEST['searchtext']) && $_REQUEST['searchtext'] != ''){
	$output .= t(getMessage( 'dsjecomment', 'code03', array("0"=>$rscounter->count)))." | ".l('View All','/allcomments'.'/'.$doc_id);
	}
	$addurl = l(getMessage( 'dsjecomment', 'code01', NULL),'alr_send-comment/'.$doc_id.'/'.$user->uid);
	$output .='</td></tr>';
	 
   	$lising = getMessage('dsjecomment', 'code02', NULL);
		
	$output .='<tr>
	<td colspan="3" class="tblHeaderLeft">'.$lising.'<span class="addrecord">'.$addurl.'</span></td>
	<td colspan="3" class="tblHeaderRight"><input type="text" name="searchtext" value="'.$_POST['searchtext'].'">
	<input type="submit" name="search" value="Search"></td>
	</tr>
	</table></form>';
 
	$result = db_query($query);

	if($_REQUEST['page']){
     $counter = $_REQUEST['page']*$limit;
	}else{
	 $counter = 0;
    }
	while($rs=db_fetch_object($result)) {
		$counter++;
		 $cuser = user_load($rs->uid);
	   $name = $cuser->name;if($rs->comment){
		   
		$rows[] = array(
			
			array('data' => $counter),
			array('data' => date('d-m-Y',strtotime($rs->comment_date))),
			array('data' => $rs->comment),
			array('data' => rolename($rs->commentedby)),
			array('data' => rolename($rs->commentedto)),
			
						
						);  
	}
	}
	 
	$output .= theme_table($header,$rows, $attributes = array(), $caption = NULL);
	
	$output .= theme('pager', NULL, $limit,0 );
	
	return $output;


}


/*function allcomments($doc_id){
   $array = explode(',',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('List of Pending Task', 'alr_pending');
	$breadcrumb[] = l('All Comments', 'allcomments/'.arg(1));
	drupal_set_breadcrumb($breadcrumb);
global $user;
   $sql = "select * from tbl_loan_comment where doc_id='".$doc_id."'";
   $res = db_query($sql);
     
   $output ='<table cellspacing="1" cellpadding="1" border="0" width="100%" id="wrapper"><tr><td class="tblHeaderLeft">All Comments <span class="addrecord">'.l('Add Comment','alr_send-comment/'.$doc_id.'/'.$user->uid).'</span></td><td colspan="3" align="right">'.l('View Account Details','accountdetails/'.getAccountN($doc_id).'/'.$doc_id).'</td></tr><tr><th>Comment Date</th><th>Comment</th><th>Commented By</th><th>Commented To</th></tr>';
   
   $i=1;
   while($rs = db_fetch_object($res)){
	   if($i%2==0){
		   $cl = 'even';
		   }
		   else{
			$cl = 'odd';   
			   }
	   
	   $cuser = user_load($rs->uid);
	   $name = $cuser->name;if($rs->comment){
       $output .='<tr class="'.$cl.'"><td>'.date('d-m-Y',strtotime($rs->comment_date)).'</td><td>'.$rs->comment.'</td><td>'.rolename($rs->commentedby).'</td><td>'.rolename($rs->commentedto).'</td></tr>';
	   }
	   $i++;
   }

   return $output .='</table>';
}*/

function rolename($rid){
  $sql = "select name from role where rid='".$rid."'";
  $res = db_query($sql);
  $rs = db_fetch_object($res);
  return $rs->name;
}

/** comment here **/

function alr_reply_form($form_state,$doc_id,$level,$cid){
	global $user;
    $array = explode(',',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l('Pending Comments', 'alr_pending-comment-list');
	$breadcrumb[] = l('Reply Comments', 'alr_comment-reply-form/'.arg(1).'/'.arg(2).'/'.arg(3));
	drupal_set_breadcrumb($breadcrumb);


 $form['empid'] = array(
	'#type' => 'hidden',
	'#value'=>$level,
	);

 $form['cid'] = array(
	'#type' => 'hidden',
	'#value'=>$cid,
	);
 $form['doc_id'] = array(
	'#type' => 'hidden',
	'#value'=>$doc_id,
	);
 
	$form['comment'] = array(
	'#type' =>'textarea',
	'#title' => t('Query/Comment'),
	'#required' => TRUE,
	'#default_value' =>'',
	'#maxlength' =>200,
	'#attributes' => array('onkeypress' =>'return textonlywithdotnemax(event,"edit-comment",200)'),
	);
	$form['submit'] = array(
	'#type' => 'submit',
		'#value' =>t('Send'),
	);
return $form;
} 

function alr_reply_form_submit($form,&$form_state){
global $user;
$to = $form_state['values']['empid'];
$doc_id = $form_state['values']['doc_id'];
$reply = $form_state['values']['comment'];
$cid = $form_state['values']['cid'];

    //db_query("update tbl_workflow_task  SET status=2 where doc_id='".$doc_id."' AND level=1");
//	db_query("update tbl_workflow_task  SET status=0,comment='".$reply."' where doc_id='".$doc_id."' AND level=2");
	//db_query("update tbl_resignation  SET status=6 where doc_id='".$doc_id."'");
	db_query("update tbl_loan_comment SET status=1 where  id='".$cid."'");
	
	db_query("insert into tbl_loan_comment (commentedby,commentedto,doc_id,comment,status) VALUES ('".getRole1($user->uid)."','".$to."','".$doc_id."','".$reply."',0)");
	//db_query("update tbl_loan_comment SET status=6 where commentedby=2 AND commentedto=1 AND doc_id='".$doc_id."'");
	
	//db_query("insert into tbl_loan_comment (commentedby,commentedto,doc_id,comment,status) VALUES ('".$level."','".$to."','".$doc_id."','".$reply."',0)");
	
	//$msg = t(getMessage('resignation', 'code07', array('0'=>'HOD')));
		drupal_set_message("Reply has been sent sucessfully.");

		
				drupal_goto('alr_pending-comment-list');
	




}


function alr_comment_creply_page($doc_id,$level,$cid){

$output = drupal_get_form('alr_reply_form',$doc_id,$level,$cid);
return $output;

}


function alr_comment_search_form($form_state,$doc_id){

$form['search_box']=array(
'#type' => 'textfield',
'#title' => '',
'#required' => TRUE,
'#size' => 60,
);
$form['doc_id']=array(
	'#type' => 'hidden',
	'#default_value' => $doc_id,
	'#required' => False,
	'#size' => 60,
);
$form['search'] = array(
'#type' => 'submit',
	'#value' =>t('search'),
);
return $form;
}




function alr_comment_search_form_submit($form,&$form_state){
	$keydata = $form_state['values']['search_box'];
	$doc_id = $form_state['values']['doc_id'];
    drupal_goto('alr_comment-search-list/'.$keydata.'/'.$doc_id);

}

function alr_comment_list_page($doc_id){

global $user;
    $array = explode(',',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('List of Pending Task(s)', 'alr_pending');
	$breadcrumb[] = l('List of Comments', 'allco/'.arg(1));
	drupal_set_breadcrumb($breadcrumb);
    
	
	
	$sql = "SELECT * FROM tbl_loan_comment where doc_id='".$doc_id."' AND commentedto='".getRole1($user->uid)."' and status=0";
	$output = alr_commentsearch($sql,$doc_id) ;
	
    return $output;
}

function alr_comment_search_page($keydata,$doc_id){
    global $user;
	$array = explode(',',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('List of Pending Task(s)', 'alr_pending');
	$breadcrumb[] = l('List of Comments', 'allco/'.arg(1));
	drupal_set_breadcrumb($breadcrumb);
   
 $val = '%'.strtoupper($keydata).'%'; $val=addslashes($val);

 $sql = " SELECT * FROM tbl_loan_comment where (UPPER(comment) LIKE '".$val."'  OR UPPER(comment_date) LIKE '%".$val."%')   AND commentedto='".getRole1($user->uid)."' AND status=0";
$output = alr_commentsearch($sql,$doc_id) ;
	
return $output;
}

function alr_pending_comment_page(){

global $user;
$array = explode(',',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('List of Pending Comment (S)', 'alr_pending-comment-list');
	drupal_set_breadcrumb($breadcrumb);
    $to = getRole1($user->uid);
    $doc_id ='';
    
	$sql = "SELECT * FROM tbl_loan_comment where commentedto='".$to."' AND status=0";
	$output = alr_commentsearch($sql,$doc_id) ;
	
return $output;

}


function alr_commentsearch($sqlquery,$doc_id){
global $user;
$limit =(int)getMessage('resignation', 'code04', NULL);
$header = array(
		array('data' => t('S.No')),
		array('data' => t('Comment'), 'field' => 'comment', 'sort' => 'desc'),
		array('data' => t('Commented by'), 'field' => 'commentedby', 'sort' => 'asc'),
		array('data' => t('Commented to'), 'field' => 'commentedto', 'sort' => 'asc'),
		array('data' => t('Commented On'), 'field' => 'comment_date', 'sort' => 'desc'),
		array('data' => t('Action')),
	);

	$sql = $sqlquery.tablesort_sql($header);
	$count_query = "SELECT COUNT(*) as mycount FROM (" . $sql . ") AS count_query";
	$cres = db_query($count_query);
	$crs = db_fetch_object($cres);
	$totalcount = $crs->mycount;
	$result = pager_query($sql,10,0,$count_query);
if($result){
   $query = "SELECT r.* FROM tbl_workflow w, tbl_workflow_details wdetail, role r WHERE w.workflow_id = wdetail.workflow_id AND r.rid = wdetail.role AND w.workflow_name = 'Arrear of Land Revenue (ALR) Recovery' "; 
	$res = db_query($query);
	while($row = db_fetch_object($res))
	{
		$role[$row->rid] = $row->name;
	} 



while($rs = db_fetch_object($result)){
	    $counter++;	    


$doc_id2=$rs->doc_id;
$level = $rs->commentedby;
$me = getRole1($user->uid);
//$close = l('Close','');
//$ssl = "select status,id from tbl_loan_comment where doc_id='".$doc_id2."' AND commentedto='".$me."' ORDER BY comment_date DESC";
//$sres = db_query($ssl);
//$sr = db_fetch_object($sres);
//if($sr->status == 0){
    $links = l('Reply','alr_comment-reply-form/'.$doc_id2.'/'.$level.'/'.$rs->id);
//}

	  	$rows[] = array(
			array('data' => $counter),
			array('data' => ucwords($rs->comment)),
			array('data' =>$role[$rs->commentedby]),
			array('data' => $role[$rs->commentedto]),
			array('data' => date("d-m-Y H:i:s",strtotime($rs->comment_date))),
			array('data' =>$links),
		);
	
	  }
}

if($doc_id == ""){
  $doc_id = $doc_id2;
}

if($rows== NULL)
	$header=NULL;
//$output .='<div class="uploadcss">';	
    if(arg(0)=='alr_comment-search-list'){
	 $records = t(getMessage('resignation', 'code03', array("0"=>$totalcount)));
	 $output .='<table  id="wrapper" class="searchrecord"><tr><td>'.$records.' | '.l('View All','alr_pending-comment-list').'</td></tr></table>';
	}
	$title = t(getMessage('resignation', 'code11',NULL));
	 $output .='<table id="wrapper"><tr><td class="tblHeaderLeft">'.$title.'<span class="addrecord">'.l('Add Comment','alr_send-comment/'.$doc_id.'/'.$user->uid).'</span></td><td class="tblHeaderRight1">'.drupal_get_form('alr_comment_search_form',$doc_id).'</td></tr></table>';
	 
	
	$output .=theme_table($header,$rows);
	 $output .=theme('pager', NULL, 20,0 );
// $output .='<div>';
  
	return $output;
  }





function alr_send_comment_form($form_state,$doc_id,$level){
global $user;
    $array = explode(',',$_GET['q']);
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	//alr_pending
	$breadcrumb[] = l('List of Pending Task(s)', 'alr_pending');
	$breadcrumb[] = l('List of Pending Comment(s)', 'allco/'.$doc_id);
	$breadcrumb[] = l('Write Comment', 'alr_send-comment/'.arg(1));
		
	drupal_set_breadcrumb($breadcrumb);


 $form['empid'] = array(
	'#type' => 'hidden',
	'#value'=>$level,
	);
 $form['doc_id'] = array(
	'#type' => 'hidden',
	'#value'=>$doc_id,
	);
	$form['query_to'] = array(
	'#type' => 'select', 
    '#title' => t(''), 
     '#required' => TRUE, 
	'#options' => alr_commenttolist($doc_id),
    );
	$form['comment'] = array(
	'#type' =>'textarea',
	'#title' => t(''),
	'#required' => TRUE,
	'#default_value' =>'',
	'#maxlength' =>200,
	'#attributes' => array('onkeypress' =>'return textonlywithdotnemax(event,"edit-comment",200)'),
	);
	$form['submit'] = array(
	'#type' => 'submit',
		'#value' =>t('Send'),
	);
return $form;
} 


function alr_send_comment_page($doc_id,$level){
 global $user;

 $output .=drupal_get_form('alr_send_comment_form',$doc_id,$level); 
return $output;
}

function alr_send_comment_form_submit($form,&$form_state){
global $user;

$emp_id = $form_state['values']['empid'];
$doc_id = $form_state['values']['doc_id'];
$reply = $form_state['values']['comment'];
$query_to = $form_state['values']['query_to'];


  db_query("insert into tbl_loan_comment (commentedby,commentedto,doc_id,comment,status) VALUES ('".getRole1($user->uid)."','".$query_to."','".$doc_id."','".$reply."',0)");

 drupal_set_message("Comment has been send.");
	drupal_goto('allco/'.$doc_id);

	//drupal_goto('viewprofile/'.$emp_id);



}


function alr_commenttolist($doc_id){
	
	global $user;
$query = "SELECT r.* FROM tbl_workflow w, tbl_workflow_details wdetail, role r WHERE w.workflow_id = wdetail.workflow_id AND r.rid = wdetail.role AND w.workflow_name = 'Arrear of Land Revenue (ALR) Recovery' AND r.rid !='".getRole1($user->uid)."'"; 
			$res = db_query($query);
			$senderarray[''] = '--Select--';
			if($res){
				while($row = db_fetch_object($res))
				{
					$senderarray[$row->rid] = ucwords($row->name);
				}
			}


			
return $senderarray;


}